// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.qos

/** JVM-side surface for the native Rust `CongestionControl` enum. */
public enum class CongestionControl(public val value: Int) {
    DROP(0),
    BLOCK(1),
    BLOCK_FIRST(2);

    public companion object {
        @JvmStatic
        public fun fromInt(value: Int): CongestionControl = entries.first { it.value == value }
    }
}
