// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.qos

/** JVM-side surface for the native Rust `CongestionControl` enum. */
public enum class CongestionControl(public val value: Int) {
    DROP(0),
    BLOCK(1),
    BLOCK_FIRST(2);

    public companion object {
        @JvmStatic
        public fun fromInt(value: Int): CongestionControl = entries.first { it.value == value }
    }
}

/** JVM-side surface for the native Rust `Priority` enum. */
public enum class Priority(public val value: Int) {
    REAL_TIME(1),
    INTERACTIVE_HIGH(2),
    INTERACTIVE_LOW(3),
    DATA_HIGH(4),
    DATA(5),
    DATA_LOW(6),
    BACKGROUND(7);

    public companion object {
        @JvmStatic
        public fun fromInt(value: Int): Priority = entries.first { it.value == value }
    }
}

/** JVM-side surface for the native Rust `Reliability` enum. */
public enum class Reliability(public val value: Int) {
    BEST_EFFORT(0),
    RELIABLE(1);

    public companion object {
        @JvmStatic
        public fun fromInt(value: Int): Reliability = entries.first { it.value == value }
    }
}
