// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.qos

/** JVM-side surface for the native Rust `Reliability` enum. */
public enum class Reliability(public val value: Int) {
    BEST_EFFORT(0),
    RELIABLE(1);

    public companion object {
        @JvmStatic
        public fun fromInt(value: Int): Reliability = entries.first { it.value == value }
    }
}
