// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.errors

import io.zenoh.jni.ZError
import io.zenoh.jni.ZException
import io.zenoh.jni.withSortedHandleLocks
import io.zenoh.jni.JNINative

public fun zErrorMessage(e: ZError, onError: (String?) -> String = { __de_je -> throw ZException(__de_je) }): String {
    if (e.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(e) {
    val e_ptr = e.ptr
    JNINative.zErrorMessage(e_ptr, __cap)
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

