// Auto-generated mechanical JNI shim. Each wrapper exports the legacy
// JNI symbol and forwards to the same-named Rust fn in zenoh_jni.
// Delete entries here as their callers move to autogenerated wrappers.

#![allow(non_snake_case)]
#![allow(clippy::not_unsafe_ptr_arg_deref)]

use jni::{objects::{JByteArray, JClass, JString}, sys::{jboolean, jint, jlong}, JNIEnv};
use zenoh_jni::zenoh::{key_expr::KeyExpr, query::Query};

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNIQuery_replySuccessViaJNI(
    env: JNIEnv,
    _class: JClass,
    query_ptr: *const Query,
    key_expr_ptr: /*nullable*/ *const KeyExpr<'static>,
    key_expr_str: JString,
    payload: JByteArray,
    encoding_id: jint,
    encoding_schema: /*nullable*/ JString,
    timestamp_enabled: jboolean,
    timestamp_ntp_64: jlong,
    attachment: /*nullable*/ JByteArray,
    qos_express: jboolean,
) {
    zenoh_jni::query::Java_io_zenoh_jni_JNIQuery_replySuccessViaJNI(env, _class, query_ptr, key_expr_ptr, key_expr_str, payload, encoding_id, encoding_schema, timestamp_enabled, timestamp_ntp_64, attachment, qos_express)
}

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNIQuery_replyErrorViaJNI(
    env: JNIEnv,
    _class: JClass,
    query_ptr: *const Query,
    payload: JByteArray,
    encoding_id: jint,
    encoding_schema: /*nullable*/ JString,
) {
    zenoh_jni::query::Java_io_zenoh_jni_JNIQuery_replyErrorViaJNI(env, _class, query_ptr, payload, encoding_id, encoding_schema)
}

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNIQuery_replyDeleteViaJNI(
    env: JNIEnv,
    _class: JClass,
    query_ptr: *const Query,
    key_expr_ptr: /*nullable*/ *const KeyExpr<'static>,
    key_expr_str: JString,
    timestamp_enabled: jboolean,
    timestamp_ntp_64: jlong,
    attachment: /*nullable*/ JByteArray,
    qos_express: jboolean,
) {
    zenoh_jni::query::Java_io_zenoh_jni_JNIQuery_replyDeleteViaJNI(env, _class, query_ptr, key_expr_ptr, key_expr_str, timestamp_enabled, timestamp_ntp_64, attachment, qos_express)
}

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNIQuery_freePtrViaJNI(
    _env: JNIEnv,
    _class: JClass,
    query_ptr: *const Query,
) {
    zenoh_jni::query::Java_io_zenoh_jni_JNIQuery_freePtrViaJNI(_env, _class, query_ptr)
}
