// Auto-generated mechanical JNI shim. Each wrapper exports the legacy
// JNI symbol and forwards to the same-named Rust fn in zenoh_jni.
// Delete entries here as their callers move to autogenerated wrappers.

#![allow(non_snake_case)]
#![allow(clippy::not_unsafe_ptr_arg_deref)]

use jni::{objects::{JByteArray, JClass, JObject, JString}, sys::jint, JNIEnv};
use zenoh_jni::zenoh::{key_expr::KeyExpr, query::Querier};

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNIQuerier_getViaJNI(
    env: JNIEnv,
    _class: JClass,
    querier_ptr: *const Querier,
    key_expr_ptr: /*nullable*/ *const KeyExpr<'static>,
    key_expr_str: JString,
    selector_params: /*nullable*/ JString,
    callback: JObject,
    on_close: JObject,
    attachment: /*nullable*/ JByteArray,
    payload: /*nullable*/ JByteArray,
    encoding_id: jint,
    encoding_schema: /*nullable*/ JString,
) {
    zenoh_jni::querier::Java_io_zenoh_jni_JNIQuerier_getViaJNI(env, _class, querier_ptr, key_expr_ptr, key_expr_str, selector_params, callback, on_close, attachment, payload, encoding_id, encoding_schema)
}

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNIQuerier_freePtrViaJNI(
    _env: JNIEnv,
    _class: JClass,
    querier_ptr: *const Querier<'static>,
) {
    zenoh_jni::querier::Java_io_zenoh_jni_JNIQuerier_freePtrViaJNI(_env, _class, querier_ptr)
}
