// Auto-generated mechanical JNI shim. Each wrapper exports the legacy
// JNI symbol and forwards to the same-named Rust fn in zenoh_jni.
// Delete entries here as their callers move to autogenerated wrappers.

#![allow(non_snake_case)]
#![allow(clippy::not_unsafe_ptr_arg_deref)]

use jni::{objects::JClass, JNIEnv};
use zenoh_jni::zenoh::query::Queryable;

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNIQueryable_freePtrViaJNI(
    _env: JNIEnv,
    _class: JClass,
    queryable_ptr: *const Queryable<()>,
) {
    zenoh_jni::queryable::Java_io_zenoh_jni_JNIQueryable_freePtrViaJNI(
        _env,
        _class,
        queryable_ptr,
    )
}
