// Auto-generated mechanical JNI shim. Each wrapper exports the legacy
// JNI symbol and forwards to the same-named Rust fn in zenoh_jni.
// Delete entries here as their callers move to autogenerated wrappers.

#![allow(non_snake_case)]
#![allow(clippy::not_unsafe_ptr_arg_deref)]

use jni::{objects::{JClass, JObject}, sys::jint, JNIEnv};
use zenoh_jni::zenoh::{scouting::Scout, Config};

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNIScout_00024Companion_scoutViaJNI(
    env: JNIEnv,
    _class: JClass,
    whatAmI: jint,
    callback: JObject,
    on_close: JObject,
    config_ptr: /*nullable=*/ *const Config,
) -> *const Scout<()> {
    zenoh_jni::scouting::Java_io_zenoh_jni_JNIScout_00024Companion_scoutViaJNI(env, _class, whatAmI, callback, on_close, config_ptr)
}

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNIScout_00024Companion_freePtrViaJNI(
    _env: JNIEnv,
    _class: JClass,
    scout_ptr: *const Scout<()>,
) {
    zenoh_jni::scouting::Java_io_zenoh_jni_JNIScout_00024Companion_freePtrViaJNI(
        _env, _class, scout_ptr,
    )
}
