// Auto-generated mechanical JNI shim. Each wrapper exports the legacy
// JNI symbol and forwards to the same-named Rust fn in zenoh_jni.
// Delete entries here as their callers move to autogenerated wrappers.

#![allow(non_snake_case)]
#![allow(clippy::not_unsafe_ptr_arg_deref)]

use jni::{objects::{JByteArray, JClass, JObject, JString}, sys::{jboolean, jbyteArray, jint, jlong, jobject}, JNIEnv};
use zenoh_jni::zenoh::{config::Config, key_expr::KeyExpr, pubsub::{Publisher, Subscriber}, query::{Querier, Queryable}, session::Session};

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNISession_00024Companion_openSessionViaJNI(
    env: JNIEnv,
    _class: JClass,
    config_ptr: *const Config,
) -> *const Session {
    zenoh_jni::session::Java_io_zenoh_jni_JNISession_00024Companion_openSessionViaJNI(env, _class, config_ptr)
}

#[no_mangle]
pub extern "C" fn Java_io_zenoh_jni_JNISession_openSessionWithJsonConfigViaJNI(
    env: JNIEnv,
    _class: JClass,
    json_config: JString,
) -> *const Session {
    zenoh_jni::session::Java_io_zenoh_jni_JNISession_openSessionWithJsonConfigViaJNI(env, _class, json_config)
}

#[no_mangle]
pub extern "C" fn Java_io_zenoh_jni_JNISession_openSessionWithYamlConfigViaJNI(
    env: JNIEnv,
    _class: JClass,
    yaml_config: JString,
) -> *const Session {
    zenoh_jni::session::Java_io_zenoh_jni_JNISession_openSessionWithYamlConfigViaJNI(env, _class, yaml_config)
}

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNISession_closeSessionViaJNI(
    env: JNIEnv,
    _class: JClass,
    session_ptr: *const Session,
) {
    zenoh_jni::session::Java_io_zenoh_jni_JNISession_closeSessionViaJNI(env, _class, session_ptr)
}

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNISession_declarePublisherViaJNI(
    env: JNIEnv,
    _class: JClass,
    key_expr_ptr: /*nullable*/ *const KeyExpr<'static>,
    key_expr_str: JString,
    session_ptr: *const Session,
    congestion_control: jint,
    priority: jint,
    is_express: jboolean,
    reliability: jint,
) -> *const Publisher<'static> {
    zenoh_jni::session::Java_io_zenoh_jni_JNISession_declarePublisherViaJNI(env, _class, key_expr_ptr, key_expr_str, session_ptr, congestion_control, priority, is_express, reliability)
}

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNISession_putViaJNI(
    env: JNIEnv,
    _class: JClass,
    key_expr_ptr: /*nullable*/ *const KeyExpr<'static>,
    key_expr_str: JString,
    session_ptr: *const Session,
    payload: JByteArray,
    encoding_id: jint,
    encoding_schema: JString,
    congestion_control: jint,
    priority: jint,
    is_express: jboolean,
    attachment: JByteArray,
    reliability: jint,
) {
    zenoh_jni::session::Java_io_zenoh_jni_JNISession_putViaJNI(env, _class, key_expr_ptr, key_expr_str, session_ptr, payload, encoding_id, encoding_schema, congestion_control, priority, is_express, attachment, reliability)
}

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNISession_deleteViaJNI(
    env: JNIEnv,
    _class: JClass,
    key_expr_ptr: /*nullable*/ *const KeyExpr<'static>,
    key_expr_str: JString,
    session_ptr: *const Session,
    congestion_control: jint,
    priority: jint,
    is_express: jboolean,
    attachment: JByteArray,
    reliability: jint,
) {
    zenoh_jni::session::Java_io_zenoh_jni_JNISession_deleteViaJNI(env, _class, key_expr_ptr, key_expr_str, session_ptr, congestion_control, priority, is_express, attachment, reliability)
}

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNISession_declareSubscriberViaJNI(
    env: JNIEnv,
    _class: JClass,
    key_expr_ptr: /*nullable*/ *const KeyExpr<'static>,
    key_expr_str: JString,
    session_ptr: *const Session,
    callback: JObject,
    on_close: JObject,
) -> *const Subscriber<()> {
    zenoh_jni::session::Java_io_zenoh_jni_JNISession_declareSubscriberViaJNI(env, _class, key_expr_ptr, key_expr_str, session_ptr, callback, on_close)
}

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNISession_declareQuerierViaJNI(
    env: JNIEnv,
    _class: JClass,
    key_expr_ptr: /*nullable*/ *const KeyExpr<'static>,
    key_expr_str: JString,
    session_ptr: *const Session,
    target: jint,
    consolidation: jint,
    congestion_control: jint,
    priority: jint,
    is_express: jboolean,
    timeout_ms: jlong,
    accept_replies: jint,
) -> *const Querier<'static> {
    zenoh_jni::session::Java_io_zenoh_jni_JNISession_declareQuerierViaJNI(env, _class, key_expr_ptr, key_expr_str, session_ptr, target, consolidation, congestion_control, priority, is_express, timeout_ms, accept_replies)
}

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNISession_declareQueryableViaJNI(
    env: JNIEnv,
    _class: JClass,
    key_expr_ptr: /*nullable*/ *const KeyExpr<'static>,
    key_expr_str: JString,
    session_ptr: *const Session,
    callback: JObject,
    on_close: JObject,
    complete: jboolean,
) -> *const Queryable<()> {
    zenoh_jni::session::Java_io_zenoh_jni_JNISession_declareQueryableViaJNI(env, _class, key_expr_ptr, key_expr_str, session_ptr, callback, on_close, complete)
}

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNISession_declareKeyExprViaJNI(
    env: JNIEnv,
    _class: JClass,
    session_ptr: *const Session,
    key_expr_str: JString,
) -> *const KeyExpr<'static> {
    zenoh_jni::session::Java_io_zenoh_jni_JNISession_declareKeyExprViaJNI(env, _class, session_ptr, key_expr_str)
}

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNISession_undeclareKeyExprViaJNI(
    env: JNIEnv,
    _class: JClass,
    session_ptr: *const Session,
    key_expr_ptr: *const KeyExpr<'static>,
) {
    zenoh_jni::session::Java_io_zenoh_jni_JNISession_undeclareKeyExprViaJNI(env, _class, session_ptr, key_expr_ptr)
}

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNISession_getViaJNI(
    env: JNIEnv,
    _class: JClass,
    key_expr_ptr: /*nullable*/ *const KeyExpr<'static>,
    key_expr_str: JString,
    selector_params: /*nullable*/ JString,
    session_ptr: *const Session,
    callback: JObject,
    on_close: JObject,
    timeout_ms: jlong,
    target: jint,
    consolidation: jint,
    attachment: /*nullable*/ JByteArray,
    payload: /*nullable*/ JByteArray,
    encoding_id: jint,
    encoding_schema: /*nullable*/ JString,
    congestion_control: jint,
    priority: jint,
    is_express: jboolean,
    accept_replies: jint,
) {
    zenoh_jni::session::Java_io_zenoh_jni_JNISession_getViaJNI(env, _class, key_expr_ptr, key_expr_str, selector_params, session_ptr, callback, on_close, timeout_ms, target, consolidation, attachment, payload, encoding_id, encoding_schema, congestion_control, priority, is_express, accept_replies)
}

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNISession_getPeersZidViaJNI(
    env: JNIEnv,
    _class: JClass,
    session_ptr: *const Session,
) -> jobject {
    zenoh_jni::session::Java_io_zenoh_jni_JNISession_getPeersZidViaJNI(env, _class, session_ptr)
}

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNISession_getRoutersZidViaJNI(
    env: JNIEnv,
    _class: JClass,
    session_ptr: *const Session,
) -> jobject {
    zenoh_jni::session::Java_io_zenoh_jni_JNISession_getRoutersZidViaJNI(env, _class, session_ptr)
}

#[no_mangle]
pub unsafe extern "C" fn Java_io_zenoh_jni_JNISession_getZidViaJNI(
    env: JNIEnv,
    _class: JClass,
    session_ptr: *const Session,
) -> jbyteArray {
    zenoh_jni::session::Java_io_zenoh_jni_JNISession_getZidViaJNI(env, _class, session_ptr)
}
