// Auto-generated mechanical JNI shim. Each wrapper exports the legacy
// JNI symbol and forwards to the same-named Rust fn in zenoh_jni.
// Delete entries here as their callers move to autogenerated wrappers.

#![allow(non_snake_case)]
#![allow(clippy::not_unsafe_ptr_arg_deref)]

use jni::{objects::{JClass, JObject}, sys::jobject, JNIEnv};

#[no_mangle]
pub extern "C" fn Java_io_zenoh_jni_JNIZBytes_serializeViaJNI(
    env: JNIEnv,
    _class: JClass,
    any: JObject,
    token_type: JObject,
) -> jobject {
    zenoh_jni::zbytes::Java_io_zenoh_jni_JNIZBytes_serializeViaJNI(env, _class, any, token_type)
}

#[no_mangle]
pub extern "C" fn Java_io_zenoh_jni_JNIZBytes_deserializeViaJNI(
    env: JNIEnv,
    _class: JClass,
    zbytes: JObject,
    jtype: JObject,
) -> jobject {
    zenoh_jni::zbytes::Java_io_zenoh_jni_JNIZBytes_deserializeViaJNI(env, _class, zbytes, jtype)
}
