// Auto-generated mechanical JNI shim. Each wrapper exports the legacy
// JNI symbol and forwards to the same-named Rust fn in zenoh_jni.
// Delete entries here as their callers move to autogenerated wrappers.

#![allow(non_snake_case)]
#![allow(clippy::not_unsafe_ptr_arg_deref)]

use jni::{objects::{JByteArray, JClass}, sys::jstring, JNIEnv};

#[no_mangle]
pub extern "C" fn Java_io_zenoh_jni_JNIZenohId_toStringViaJNI(
    env: JNIEnv,
    _class: JClass,
    zenoh_id: JByteArray,
) -> jstring {
    zenoh_jni::zenoh_id::Java_io_zenoh_jni_JNIZenohId_toStringViaJNI(env, _class, zenoh_id)
}
