// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni.keyexpr

import io.zenoh.jni.Error
import io.zenoh.jni.JniBindingError
import io.zenoh.jni.JNINative

@Throws(Error::class, JniBindingError::class)
public fun keyexprValidate(s: String): String =
    JNINative.keyexprValidate(s)

