// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.keyexpr

import io.zenoh.jni.ErrorHolder
import io.zenoh.jni.ErrorSink
import io.zenoh.jni.ZException
import io.zenoh.jni.keyexpr.SetIntersectionLevel
import io.zenoh.jni.keyexpr.ZKeyExpr
import io.zenoh.jni.withSortedHandleLocks
import io.zenoh.jni.JNINative

public fun zKeyexprTryFrom(s: String): ZKeyExpr {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZKeyExpr(JNINative.zKeyexprTryFrom(s, __sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zKeyexprAutocanonize(s: String): ZKeyExpr {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZKeyExpr(JNINative.zKeyexprAutocanonize(s, __sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zKeyexprIntersects(a: ZKeyExpr, b: ZKeyExpr): Boolean {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(a, b) {
    val a_ptr = a.ptr
    if (a_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val b_ptr = b.ptr
    if (b_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zKeyexprIntersects(a_ptr, b_ptr, __sink)
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zKeyexprIncludes(a: ZKeyExpr, b: ZKeyExpr): Boolean {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(a, b) {
    val a_ptr = a.ptr
    if (a_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val b_ptr = b.ptr
    if (b_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zKeyexprIncludes(a_ptr, b_ptr, __sink)
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zKeyexprRelationTo(a: ZKeyExpr, b: ZKeyExpr): SetIntersectionLevel {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(a, b) {
    val a_ptr = a.ptr
    if (a_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val b_ptr = b.ptr
    if (b_ptr == 0L) throw ZException("Operation on a closed native handle.")
    SetIntersectionLevel.fromInt(JNINative.zKeyexprRelationTo(a_ptr, b_ptr, __sink))
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zKeyexprJoin(a: ZKeyExpr, b: String): ZKeyExpr {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(a) {
    val a_ptr = a.ptr
    if (a_ptr == 0L) throw ZException("Operation on a closed native handle.")
    ZKeyExpr(JNINative.zKeyexprJoin(a_ptr, b, __sink))
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zKeyexprConcat(a: ZKeyExpr, b: String): ZKeyExpr {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(a) {
    val a_ptr = a.ptr
    if (a_ptr == 0L) throw ZException("Operation on a closed native handle.")
    ZKeyExpr(JNINative.zKeyexprConcat(a_ptr, b, __sink))
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zKeyexprClone(ke: ZKeyExpr): ZKeyExpr {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(ke) {
    val ke_ptr = ke.ptr
    if (ke_ptr == 0L) throw ZException("Operation on a closed native handle.")
    ZKeyExpr(JNINative.zKeyexprClone(ke_ptr, __sink))
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zKeyexprToString(ke: ZKeyExpr): String {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(ke) {
    val ke_ptr = ke.ptr
    if (ke_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zKeyexprToString(ke_ptr, __sink)
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

