// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.keyexpr

import io.zenoh.jni.Error
import io.zenoh.jni.JNINative
import io.zenoh.jni.JniBindingError

public data class KeyExpr(
    val keyExprString: String,
    val keyExprNative: ZKeyExpr?,
) : AutoCloseable {
    override fun close() {
        keyExprNative?.close()
    }

    public companion object {
        @JvmStatic
        public fun fromParts(
            keyExprString: String,
            keyExprNative: Long
        ): KeyExpr =
            KeyExpr(keyExprString, if (keyExprNative == 0L) null else ZKeyExpr(keyExprNative))
        @Throws(Error::class, JniBindingError::class)
        public fun keyexprTryFrom(s: String): KeyExpr =
            JNINative.keyexprTryFrom(s)


        @Throws(Error::class, JniBindingError::class)
        public fun keyexprAutocanonize(s: String): KeyExpr =
            JNINative.keyexprAutocanonize(s)


        @Throws(Error::class, JniBindingError::class)
        public fun keyexprIntersects(a: KeyExpr, b: KeyExpr): Boolean =
            JNINative.keyexprIntersects(a, b)


        @Throws(Error::class, JniBindingError::class)
        public fun keyexprIncludes(a: KeyExpr, b: KeyExpr): Boolean =
            JNINative.keyexprIncludes(a, b)


        @Throws(Error::class, JniBindingError::class)
        public fun keyexprRelationTo(a: KeyExpr, b: KeyExpr): SetIntersectionLevel =
            SetIntersectionLevel.fromInt(JNINative.keyexprRelationTo(a, b))


        @Throws(Error::class, JniBindingError::class)
        public fun keyexprJoin(a: KeyExpr, b: String): KeyExpr =
            JNINative.keyexprJoin(a, b)


        @Throws(Error::class, JniBindingError::class)
        public fun keyexprConcat(a: KeyExpr, b: String): KeyExpr =
            JNINative.keyexprConcat(a, b)

    }
}
