// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.keyexpr

/** JVM-side surface for the native Rust `SetIntersectionLevel` enum. */
public enum class SetIntersectionLevel(public val value: Int) {
    DISJOINT(0),
    INTERSECTS(1),
    INCLUDES(2),
    EQUALS(3);

    public companion object {
        @JvmStatic
        public fun fromInt(value: Int): SetIntersectionLevel = entries.first { it.value == value }
    }
}
