// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.keyexpr

import io.zenoh.jni.Error
import io.zenoh.jni.JNINative
import io.zenoh.jni.JniBindingError
import io.zenoh.jni.NativeHandle
import io.zenoh.jni.withSortedHandleLocks

/** Typed handle for a native Zenoh `ZKeyExpr`. */
public class ZKeyExpr(initialPtr: Long) : NativeHandle(initialPtr) {
    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZKeyExpr {
        val p = ptr
        ptr = 0L
        return ZKeyExpr(p)
    }

    @Throws(JniBindingError::class)
    public fun zKeyexprIntersects(b: ZKeyExpr): Boolean {
        val __locks = ArrayList<NativeHandle>()
        __locks.add(this)
        __locks.add(b)
        return withSortedHandleLocks(__locks) {
        val a_ptr = this.ptr
        if (a_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        val b_ptr = b.ptr
        if (b_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zKeyexprIntersects(a_ptr, b_ptr)
        }
    }

    @Throws(JniBindingError::class)
    public fun zKeyexprIncludes(b: ZKeyExpr): Boolean {
        val __locks = ArrayList<NativeHandle>()
        __locks.add(this)
        __locks.add(b)
        return withSortedHandleLocks(__locks) {
        val a_ptr = this.ptr
        if (a_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        val b_ptr = b.ptr
        if (b_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zKeyexprIncludes(a_ptr, b_ptr)
        }
    }

    @Throws(JniBindingError::class)
    public fun zKeyexprRelationTo(b: ZKeyExpr): SetIntersectionLevel {
        val __locks = ArrayList<NativeHandle>()
        __locks.add(this)
        __locks.add(b)
        return withSortedHandleLocks(__locks) {
        val a_ptr = this.ptr
        if (a_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        val b_ptr = b.ptr
        if (b_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        SetIntersectionLevel.fromInt(JNINative.zKeyexprRelationTo(a_ptr, b_ptr))
        }
    }

    @Throws(Error::class, JniBindingError::class)
    public fun zKeyexprJoin(b: String): ZKeyExpr {
        val __locks = ArrayList<NativeHandle>()
        __locks.add(this)
        return withSortedHandleLocks(__locks) {
        val a_ptr = this.ptr
        if (a_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        ZKeyExpr(JNINative.zKeyexprJoin(a_ptr, b))
        }
    }

    @Throws(Error::class, JniBindingError::class)
    public fun zKeyexprConcat(b: String): ZKeyExpr {
        val __locks = ArrayList<NativeHandle>()
        __locks.add(this)
        return withSortedHandleLocks(__locks) {
        val a_ptr = this.ptr
        if (a_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        ZKeyExpr(JNINative.zKeyexprConcat(a_ptr, b))
        }
    }

    @Throws(JniBindingError::class)
    public fun zKeyexprClone(): ZKeyExpr {
        val __locks = ArrayList<NativeHandle>()
        __locks.add(this)
        return withSortedHandleLocks(__locks) {
        val ke_ptr = this.ptr
        if (ke_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        ZKeyExpr(JNINative.zKeyexprClone(ke_ptr))
        }
    }

    @Throws(JniBindingError::class)
    public fun zKeyexprToString(): String {
        val __locks = ArrayList<NativeHandle>()
        __locks.add(this)
        return withSortedHandleLocks(__locks) {
        val ke_ptr = this.ptr
        if (ke_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zKeyexprToString(ke_ptr)
        }
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)

        @Throws(Error::class, JniBindingError::class)
        public fun zKeyexprTryFrom(s: String): ZKeyExpr =
            ZKeyExpr(JNINative.zKeyexprTryFrom(s))

        @Throws(Error::class, JniBindingError::class)
        public fun zKeyexprAutocanonize(s: String): ZKeyExpr =
            ZKeyExpr(JNINative.zKeyexprAutocanonize(s))
    }
}
