// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni.keyexpr

import io.zenoh.jni.Error
import io.zenoh.jni.JNINative
import io.zenoh.jni.JNINativeHandle
import io.zenoh.jni.JniBindingError

/** Typed [JNINativeHandle] for a native Zenoh `ZKeyExpr`. */
public class ZKeyExpr(initialPtr: Long) : JNINativeHandle(initialPtr), AutoCloseable {
    private val cleanable: java.lang.ref.Cleaner.Cleanable =
        JNINativeHandle.CLEANER.register(this, Cleanup(state))

    override fun close() = cleanable.clean()

    private class Cleanup(private val state: JNINativeHandle.State) : Runnable {
        override fun run() = state.freeOnce { ZKeyExpr.freePtr(it) }
    }

    @Throws(JniBindingError::class)
    public fun zKeyexprIntersects(b: JNINativeHandle): Boolean =
        withPtr { a_ptr ->
        b.withPtr { b_ptr ->
        JNINative.zKeyexprIntersects(a_ptr, b_ptr)
    }
    }

    @Throws(JniBindingError::class)
    public fun zKeyexprIncludes(b: JNINativeHandle): Boolean =
        withPtr { a_ptr ->
        b.withPtr { b_ptr ->
        JNINative.zKeyexprIncludes(a_ptr, b_ptr)
    }
    }

    @Throws(JniBindingError::class)
    public fun zKeyexprRelationTo(b: JNINativeHandle): SetIntersectionLevel =
        withPtr { a_ptr ->
        b.withPtr { b_ptr ->
        JNINative.zKeyexprRelationTo(a_ptr, b_ptr)
    }
    }

    @Throws(Error::class, JniBindingError::class)
    public fun zKeyexprJoin(b: String): ZKeyExpr =
        withPtr { a_ptr ->
        ZKeyExpr(JNINative.zKeyexprJoin(a_ptr, b))
    }

    @Throws(Error::class, JniBindingError::class)
    public fun zKeyexprConcat(b: String): ZKeyExpr =
        withPtr { a_ptr ->
        ZKeyExpr(JNINative.zKeyexprConcat(a_ptr, b))
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)

        @Throws(Error::class, JniBindingError::class)
        public fun zKeyexprTryFrom(s: String): ZKeyExpr =
            ZKeyExpr(JNINative.zKeyexprTryFrom(s))

        @Throws(Error::class, JniBindingError::class)
        public fun zKeyexprAutocanonize(s: String): ZKeyExpr =
            ZKeyExpr(JNINative.zKeyexprAutocanonize(s))
    }
}
