// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.sample

import io.zenoh.jni.ErrorHolder
import io.zenoh.jni.ErrorSink
import io.zenoh.jni.ZException
import io.zenoh.jni.bytes.ZEncoding
import io.zenoh.jni.bytes.ZZBytes
import io.zenoh.jni.keyexpr.ZKeyExpr
import io.zenoh.jni.qos.CongestionControl
import io.zenoh.jni.qos.Priority
import io.zenoh.jni.sample.SampleKind
import io.zenoh.jni.sample.ZSample
import io.zenoh.jni.time.ZTimestamp
import io.zenoh.jni.withSortedHandleLocks
import io.zenoh.jni.JNINative

public fun zSampleKeyExpr(s: ZSample): ZKeyExpr {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(s) {
    val s_ptr = s.ptr
    if (s_ptr == 0L) throw ZException("Operation on a closed native handle.")
    ZKeyExpr(JNINative.zSampleKeyExpr(s_ptr, __sink))
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zSamplePayload(s: ZSample): ZZBytes {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(s) {
    val s_ptr = s.ptr
    if (s_ptr == 0L) throw ZException("Operation on a closed native handle.")
    ZZBytes(JNINative.zSamplePayload(s_ptr, __sink))
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zSampleEncoding(s: ZSample): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(s) {
    val s_ptr = s.ptr
    if (s_ptr == 0L) throw ZException("Operation on a closed native handle.")
    ZEncoding(JNINative.zSampleEncoding(s_ptr, __sink))
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zSampleKind(s: ZSample): SampleKind {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(s) {
    val s_ptr = s.ptr
    if (s_ptr == 0L) throw ZException("Operation on a closed native handle.")
    SampleKind.fromInt(JNINative.zSampleKind(s_ptr, __sink))
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zSampleTimestamp(s: ZSample): ZTimestamp? {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(s) {
    val s_ptr = s.ptr
    if (s_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zSampleTimestamp(s_ptr, __sink).let { if (it == 0L) null else ZTimestamp(it) }
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zSampleExpress(s: ZSample): Boolean {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(s) {
    val s_ptr = s.ptr
    if (s_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zSampleExpress(s_ptr, __sink)
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zSamplePriority(s: ZSample): Priority {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(s) {
    val s_ptr = s.ptr
    if (s_ptr == 0L) throw ZException("Operation on a closed native handle.")
    Priority.fromInt(JNINative.zSamplePriority(s_ptr, __sink))
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zSampleCongestionControl(s: ZSample): CongestionControl {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(s) {
    val s_ptr = s.ptr
    if (s_ptr == 0L) throw ZException("Operation on a closed native handle.")
    CongestionControl.fromInt(JNINative.zSampleCongestionControl(s_ptr, __sink))
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zSampleAttachment(s: ZSample): ZZBytes? {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(s) {
    val s_ptr = s.ptr
    if (s_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zSampleAttachment(s_ptr, __sink).let { if (it == 0L) null else ZZBytes(it) }
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

