// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni.sample

/** JVM-side surface for the native Rust `SampleKind` enum. */
public enum class SampleKind(public val value: Int) {
    PUT(0),
    DELETE(1);

    public companion object {
        @JvmStatic
        public fun fromInt(value: Int): SampleKind = entries.first { it.value == value }
    }
}
