// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni.sample

import io.zenoh.jni.bytes.Encoding
import io.zenoh.jni.bytes.ZBytes
import io.zenoh.jni.keyexpr.KeyExpr
import io.zenoh.jni.qos.CongestionControl
import io.zenoh.jni.qos.Priority
import io.zenoh.jni.time.Timestamp

public data class Sample(
    val keyExpr: KeyExpr,
    val payload: ZBytes,
    val encoding: Encoding,
    val kind: SampleKind,
    val timestamp: Timestamp?,
    val express: Boolean,
    val priority: Priority,
    val congestionControl: CongestionControl,
    val attachment: ZBytes?,
) {
    public companion object {
    }
}
