// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.sample

import io.zenoh.jni.NativeHandle

/** Typed handle for a native Zenoh `ZSample`. */
public class ZSample(initialPtr: Long) : NativeHandle(initialPtr) {
    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZSample {
        val p = ptr
        ptr = 0L
        return ZSample(p)
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}
