// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.time

import io.zenoh.jni.ErrorHolder
import io.zenoh.jni.ErrorSink
import io.zenoh.jni.ZException
import io.zenoh.jni.time.ZTimestamp
import io.zenoh.jni.withSortedHandleLocks
import io.zenoh.jni.JNINative

public fun zTimestampNtp64(t: ZTimestamp): Long {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(t) {
    val t_ptr = t.ptr
    if (t_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zTimestampNtp64(t_ptr, __sink)
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zTimestampId(t: ZTimestamp): ByteArray {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(t) {
    val t_ptr = t.ptr
    if (t_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zTimestampId(t_ptr, __sink)
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

