// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.time

import io.zenoh.jni.JNINative
import io.zenoh.jni.JniBindingError
import io.zenoh.jni.NativeHandle
import io.zenoh.jni.withSortedHandleLocks

/** Typed handle for a native Zenoh `ZTimestamp`. */
public class ZTimestamp(initialPtr: Long) : NativeHandle(initialPtr) {
    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZTimestamp {
        val p = ptr
        ptr = 0L
        return ZTimestamp(p)
    }

    @Throws(JniBindingError::class)
    public fun zTimestampNtp64(): Long {
        val __locks = ArrayList<NativeHandle>()
        __locks.add(this)
        return withSortedHandleLocks(__locks) {
        val t_ptr = this.ptr
        if (t_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zTimestampNtp64(t_ptr)
        }
    }

    @Throws(JniBindingError::class)
    public fun zTimestampId(): ByteArray {
        val __locks = ArrayList<NativeHandle>()
        __locks.add(this)
        return withSortedHandleLocks(__locks) {
        val t_ptr = this.ptr
        if (t_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zTimestampId(t_ptr)
        }
    }

    @Throws(JniBindingError::class)
    public fun zTimestampExpand(): Timestamp {
        val __locks = ArrayList<NativeHandle>()
        __locks.add(this)
        return withSortedHandleLocks(__locks) {
        val t_ptr = this.ptr
        if (t_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zTimestampExpand(t_ptr)
        }
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}
