// Generated by build.rs into OUT_DIR.
use zenoh_flat::Error;

include!(concat!(env!("OUT_DIR"), "/zenoh_flat_jni.rs"));

// Mechanical shim re-exporting the legacy zenoh-jni Java_… symbols through
// thin wrappers that forward to zenoh_jni::<module>::Java_…. Delete entries
// as their callers migrate to autogenerated wrappers over zenoh-flat.
pub mod outdated;
