// Generated `kotlin_enum` decoders use bare type idents (e.g. `WhatAmI`)
// matching the wrapper fn's `v: <ident>` signature. Bring upstream
// enums into scope so those decoders resolve at the include site.
use zenoh_flat::CongestionControl;
use zenoh_flat::ConsolidationMode;
use zenoh_flat::Priority;
use zenoh_flat::QueryTarget;
use zenoh_flat::Reliability;
use zenoh_flat::ReplyKeyExpr;
use zenoh_flat::SampleKind;
use zenoh_flat::SetIntersectionLevel;
use zenoh_flat::WhatAmI;

// Generated by build.rs into OUT_DIR.
include!(concat!(env!("OUT_DIR"), "/zenoh_flat_jni.rs"));

// Hand-written ZBytes serialization JNI. Java-specific (walks reflect.Type,
// builds java.util collections), so it lives here rather than in the
// language-agnostic zenoh-flat. Throws io.zenoh.jni.JniBindingError via the
// generated `throw_JniBindingError`.
#[cfg(feature = "zenoh-ext")]
mod zbytes;
