// Generated `kotlin_enum` decoders use bare type idents (e.g. `WhatAmI`)
// matching the wrapper fn's `v: <ident>` signature. Bring upstream
// enums into scope so those decoders resolve at the include site.
use zenoh_flat::WhatAmI;
use zenoh_flat::SetIntersectionLevel;
use zenoh_flat::CongestionControl;
use zenoh_flat::Priority;
use zenoh_flat::Reliability;

// Generated by build.rs into OUT_DIR.
include!(concat!(env!("OUT_DIR"), "/zenoh_flat_jni.rs"));

// Mechanical shim re-exporting the legacy zenoh-jni Java_… symbols through
// thin wrappers that forward to zenoh_jni::<module>::Java_…. Delete entries
// as their callers migrate to autogenerated wrappers over zenoh-flat.
pub mod outdated;
