// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni.logger

import io.zenoh.jni.JniBindingError
import io.zenoh.jni.JNINative

@Throws(JniBindingError::class)
public fun initAndroidLogs(filter: String) =
    JNINative.initAndroidLogs(filter)

@Throws(JniBindingError::class)
public fun initZenohLogsFromEnvOr(fallbackFilter: String) =
    JNINative.initZenohLogsFromEnvOr(fallbackFilter)

public fun tryInitZenohLogsFromEnv() =
    JNINative.tryInitZenohLogsFromEnv()

