// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.config

import io.zenoh.jni.JniBindingError
import io.zenoh.jni.config.ZZenohId
import io.zenoh.jni.JNINative

@Throws(JniBindingError::class)
public fun zZenohIdToBytes(z: ZZenohId): ByteArray =
    JNINative.zZenohIdToBytes(z.bytes)

@Throws(JniBindingError::class)
public fun zZenohIdToString(z: ZZenohId): String =
    JNINative.zZenohIdToString(z.bytes)

