// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.config

/** JVM-side surface for the native Rust `WhatAmI` enum. */
public enum class WhatAmI(public val value: Int) {
    ROUTER(1),
    PEER(2),
    CLIENT(4);

    public companion object {
        @JvmStatic
        public fun fromInt(value: Int): WhatAmI = entries.first { it.value == value }
    }
}
