// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.config

import io.zenoh.jni.Error
import io.zenoh.jni.JNINative
import io.zenoh.jni.JniBindingError

/** Typed handle for a native Zenoh `ZConfig`. */
public class ZConfig(initialPtr: Long) : AutoCloseable {
    @Volatile internal var ptr: Long = initialPtr

    public fun peek(): Long = ptr
    public fun isClosed(): Boolean = ptr == 0L

    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZConfig {
        val p = ptr
        ptr = 0L
        return ZConfig(p)
    }

    @Throws(Error::class, JniBindingError::class)
    public fun zConfigGetJson(key: String): String {
        synchronized(this) {
            val c_ptr = this.ptr
            if (c_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
            return JNINative.zConfigGetJson(c_ptr, key)
        }
    }

    @Throws(Error::class, JniBindingError::class)
    public fun zConfigInsertJson5(key: String, value: String) {
        synchronized(this) {
            val c_ptr = this.ptr
            if (c_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
            JNINative.zConfigInsertJson5(c_ptr, key, value)
        }
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)

        @Throws(JniBindingError::class)
        public fun zConfigDefault(): ZConfig =
            ZConfig(JNINative.zConfigDefault())

        @Throws(Error::class, JniBindingError::class)
        public fun zConfigFromFile(path: String): ZConfig =
            ZConfig(JNINative.zConfigFromFile(path))

        @Throws(Error::class, JniBindingError::class)
        public fun zConfigFromJson(s: String): ZConfig =
            ZConfig(JNINative.zConfigFromJson(s))

        @Throws(Error::class, JniBindingError::class)
        public fun zConfigFromJson5(s: String): ZConfig =
            ZConfig(JNINative.zConfigFromJson5(s))

        @Throws(Error::class, JniBindingError::class)
        public fun zConfigFromYaml(s: String): ZConfig =
            ZConfig(JNINative.zConfigFromYaml(s))
    }
}
