// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.config

import io.zenoh.jni.Error
import io.zenoh.jni.JNINative
import io.zenoh.jni.JniBindingError
import io.zenoh.jni.NativeHandle
import io.zenoh.jni.withSortedHandleLocks

/** Typed handle for a native Zenoh `ZConfig`. */
public class ZConfig(initialPtr: Long) : NativeHandle(initialPtr) {
    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZConfig {
        val p = ptr
        ptr = 0L
        return ZConfig(p)
    }

    @Throws(Error::class, JniBindingError::class)
    public fun zConfigGetJson(key: String): String {
        return withSortedHandleLocks(this) {
        val c_ptr = this.ptr
        if (c_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zConfigGetJson(c_ptr, key)
        }
    }

    @Throws(Error::class, JniBindingError::class)
    public fun zConfigInsertJson5(key: String, value: String) {
        withSortedHandleLocks(this) {
        val c_ptr = this.ptr
        if (c_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zConfigInsertJson5(c_ptr, key, value)
        }
    }

    @Throws(JniBindingError::class)
    public fun zConfigClone(): ZConfig {
        return withSortedHandleLocks(this) {
        val c_ptr = this.ptr
        if (c_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        ZConfig(JNINative.zConfigClone(c_ptr))
        }
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)

        @Throws(JniBindingError::class)
        public fun zConfigDefault(): ZConfig =
            ZConfig(JNINative.zConfigDefault())

        @Throws(Error::class, JniBindingError::class)
        public fun zConfigFromFile(path: String): ZConfig =
            ZConfig(JNINative.zConfigFromFile(path))

        @Throws(Error::class, JniBindingError::class)
        public fun zConfigFromJson(s: String): ZConfig =
            ZConfig(JNINative.zConfigFromJson(s))

        @Throws(Error::class, JniBindingError::class)
        public fun zConfigFromJson5(s: String): ZConfig =
            ZConfig(JNINative.zConfigFromJson5(s))

        @Throws(Error::class, JniBindingError::class)
        public fun zConfigFromYaml(s: String): ZConfig =
            ZConfig(JNINative.zConfigFromYaml(s))
    }
}
