// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.config

import io.zenoh.jni.JNINative
import io.zenoh.jni.JniBindingError

@JvmInline
public value class ZenohId(val bytes: ByteArray) {
    public companion object {
        @Throws(JniBindingError::class)
        public fun zenohIdToString(bytes: ByteArray): String =
            JNINative.zenohIdToString(bytes)

    }
}
