// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.config

import io.zenoh.jni.JNINative
import io.zenoh.jni.JniBindingError
import io.zenoh.jni.NativeHandle
import io.zenoh.jni.withSortedHandleLocks

/** Typed handle for a native Zenoh `ZZenohId`. */
public class ZZenohId(initialPtr: Long) : NativeHandle(initialPtr) {
    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZZenohId {
        val p = ptr
        ptr = 0L
        return ZZenohId(p)
    }

    @Throws(JniBindingError::class)
    public fun zZenohIdToBytes(): ByteArray {
        val __locks = ArrayList<NativeHandle>()
        __locks.add(this)
        return withSortedHandleLocks(__locks) {
        val z_ptr = this.ptr
        if (z_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zZenohIdToBytes(z_ptr)
        }
    }

    @Throws(JniBindingError::class)
    public fun zZenohIdToString(): String {
        val __locks = ArrayList<NativeHandle>()
        __locks.add(this)
        return withSortedHandleLocks(__locks) {
        val z_ptr = this.ptr
        if (z_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zZenohIdToString(z_ptr)
        }
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}
