// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.config

/** Typed by-value wrapper for the native Rust `ZZenohId` (a `Copy` blob carried
 *  as its raw bytes; `@JvmInline`-erased to `ByteArray` at the JNI boundary). */
@JvmInline
public value class ZZenohId(public val bytes: ByteArray)
