// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni.config

import io.zenoh.jni.JNINative
import io.zenoh.jni.JniBindingError

/** Typed handle for a native Zenoh `ZZenohId`. */
public class ZZenohId(initialPtr: Long) : AutoCloseable {
    @Volatile internal var ptr: Long = initialPtr

    public fun peek(): Long = ptr
    public fun isClosed(): Boolean = ptr == 0L

    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZZenohId {
        val p = ptr
        ptr = 0L
        return ZZenohId(p)
    }

    @Throws(JniBindingError::class)
    public fun zZenohIdToBytes(): ByteArray {
        synchronized(this) {
            val z_ptr = this.ptr
            if (z_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
            return JNINative.zZenohIdToBytes(z_ptr)
        }
    }

    @Throws(JniBindingError::class)
    public fun zZenohIdToString(): String {
        synchronized(this) {
            val z_ptr = this.ptr
            if (z_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
            return JNINative.zZenohIdToString(z_ptr)
        }
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}
