// Auto-generated by JniGen - do not edit by hand.
package io.zenoh.jni.callbacks

import io.zenoh.jni.config.WhatAmI
import io.zenoh.jni.config.ZenohId

public fun interface HelloCallback {
    fun run(
        p0_whatami: Int,
        p0_zid: ByteArray,
        p0_locators: List<String>,
    )
}
