// Auto-generated by JniGen - do not edit by hand.
package io.zenoh.jni.callbacks

import io.zenoh.jni.bytes.Encoding
import io.zenoh.jni.bytes.ZBytes
import io.zenoh.jni.keyexpr.KeyExpr
import io.zenoh.jni.keyexpr.ZKeyExpr
import io.zenoh.jni.query.ReplyKeyExpr
import io.zenoh.jni.query.ZQuery

public fun interface QueryCallback {
    fun run(
        p0_keyExpr_keyExprString: String,
        p0_keyExpr_keyExprNative: Long,
        p0_parameters: String,
        p0_payload: ByteArray?,
        p0_encoding__present: Boolean,
        p0_encoding_id: Int,
        p0_encoding_schema: String?,
        p0_attachment: ByteArray?,
        p0_acceptsReplies: Int,
        p0_query: Long,
    )
}
