// Auto-generated by JniGen - do not edit by hand.
package io.zenoh.jni.callbacks

import io.zenoh.jni.bytes.Encoding
import io.zenoh.jni.bytes.ZBytes
import io.zenoh.jni.config.ZenohId
import io.zenoh.jni.keyexpr.KeyExpr
import io.zenoh.jni.keyexpr.ZKeyExpr
import io.zenoh.jni.qos.CongestionControl
import io.zenoh.jni.qos.Priority
import io.zenoh.jni.sample.Sample
import io.zenoh.jni.sample.SampleKind
import io.zenoh.jni.time.Timestamp

public fun interface ReplyCallback {
    fun run(
        p0_replierZid: ByteArray?,
        p0_replierEid: Int,
        p0_sample__present: Boolean,
        p0_sample_keyExpr_keyExprString: String?,
        p0_sample_keyExpr_keyExprNative: Long,
        p0_sample_payload: ByteArray?,
        p0_sample_encoding_id: Int,
        p0_sample_encoding_schema: String?,
        p0_sample_kind: Int,
        p0_sample_timestamp__present: Boolean,
        p0_sample_timestamp_ntp64: Long,
        p0_sample_timestamp_id: ByteArray?,
        p0_sample_express: Boolean,
        p0_sample_priority: Int,
        p0_sample_congestionControl: Int,
        p0_sample_attachment: ByteArray?,
        p0_errorPayload: ByteArray?,
        p0_errorEncoding__present: Boolean,
        p0_errorEncoding_id: Int,
        p0_errorEncoding_schema: String?,
    )
}
