// Auto-generated by JniGen - do not edit by hand.
package io.zenoh.jni.callbacks

import io.zenoh.jni.bytes.Encoding
import io.zenoh.jni.bytes.ZBytes
import io.zenoh.jni.keyexpr.KeyExpr
import io.zenoh.jni.keyexpr.ZKeyExpr
import io.zenoh.jni.qos.CongestionControl
import io.zenoh.jni.qos.Priority
import io.zenoh.jni.sample.SampleKind
import io.zenoh.jni.time.Timestamp

public fun interface SampleCallback {
    fun run(
        p0_keyExpr_keyExprString: String,
        p0_keyExpr_keyExprNative: Long,
        p0_payload: ByteArray,
        p0_encoding_id: Int,
        p0_encoding_schema: String?,
        p0_kind: Int,
        p0_timestamp__present: Boolean,
        p0_timestamp_ntp64: Long,
        p0_timestamp_id: ByteArray?,
        p0_express: Boolean,
        p0_priority: Int,
        p0_congestionControl: Int,
        p0_attachment: ByteArray?,
    )
}
