use crate::kotlin::kotlin_ext::KotlinFile;

pub(crate) fn emit_exception(package: &str, class_name: &str, rust_doc_name: &str) -> KotlinFile {
    KotlinFile {
        contents: render_exception_source(package, class_name, rust_doc_name),
        package: package.to_string(),
        class_name: class_name.to_string(),
    }
}

fn render_exception_source(package: &str, class_name: &str, rust_doc_name: &str) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by JniExt - do not edit by hand.\n");
    if !package.is_empty() {
        s.push_str(&format!("package {}\n\n", package));
    }
    s.push_str(&format!(
        "/** JVM-side surface for the native Rust `{}` error. */\n",
        rust_doc_name
    ));
    s.push_str(&format!(
        "public class {}(override val message: String? = null) : Exception()\n",
        class_name
    ));
    s
}
