use crate::kotlin::kotlin_ext::KotlinFile;

pub(crate) fn emit_native_lib_loader(package: &str, lib_name: &str) -> KotlinFile {
    KotlinFile {
        package: package.to_string(),
        class_name: "NativeLibLoader".into(),
        contents: render_native_lib_loader_source(package, lib_name),
    }
}

fn render_native_lib_loader_source(package: &str, lib_name: &str) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by JniExt - do not edit by hand.\n");
    if !package.is_empty() {
        out.push_str(&format!("package {}\n\n", package));
    }
    out.push_str("import java.io.File\n");
    out.push_str("import java.io.FileInputStream\n");
    out.push_str("import java.io.FileOutputStream\n");
    out.push_str("import java.io.InputStream\n");
    out.push_str("import java.util.zip.ZipInputStream\n\n");
    out.push_str(&format!(
        "internal object NativeLibLoader {{\n\
         \x20   private const val LIB_NAME = \"{lib_name}\"\n\
         \n\
         \x20   init {{\n\
         \x20       if (tryLoadingLocalLibrary().isFailure) {{\n\
         \x20           val target = determineTarget().getOrThrow()\n\
         \x20           tryLoadingLibraryFromJarPackage(target).getOrThrow()\n\
         \x20       }}\n\
         \x20   }}\n\
         \n\
         \x20   private fun determineTarget(): Result<Target> = runCatching {{\n\
         \x20       val osName = System.getProperty(\"os.name\").lowercase()\n\
         \x20       val osArch = System.getProperty(\"os.arch\").lowercase()\n\
         \x20       val target = when {{\n\
         \x20           osName.contains(\"win\") -> when {{\n\
         \x20               osArch.contains(\"x86_64\") || osArch.contains(\"amd64\") || osArch.contains(\"x64\") ->\n\
         \x20                   Target.WINDOWS_X86_64_MSVC\n\
         \x20               osArch.contains(\"aarch64\") || osArch.contains(\"arm64\") ->\n\
         \x20                   Target.WINDOWS_AARCH64_MSVC\n\
         \x20               else -> throw UnsupportedOperationException(\"Unsupported architecture on Windows: $osArch\")\n\
         \x20           }}\n\
         \x20           osName.contains(\"mac\") || osName.contains(\"darwin\") || osName.contains(\"os x\") -> when {{\n\
         \x20               osArch.contains(\"x86_64\") || osArch.contains(\"amd64\") || osArch.contains(\"x64\") ->\n\
         \x20                   Target.APPLE_X86_64\n\
         \x20               osArch.contains(\"aarch64\") || osArch.contains(\"arm64\") ->\n\
         \x20                   Target.APPLE_AARCH64\n\
         \x20               else -> throw UnsupportedOperationException(\"Unsupported architecture on macOS: $osArch\")\n\
         \x20           }}\n\
         \x20           osName.contains(\"nix\") || osName.contains(\"nux\") || osName.contains(\"aix\") -> when {{\n\
         \x20               osArch.contains(\"x86_64\") || osArch.contains(\"amd64\") || osArch.contains(\"x64\") ->\n\
         \x20                   Target.LINUX_X86_64\n\
         \x20               osArch.contains(\"aarch64\") || osArch.contains(\"arm64\") ->\n\
         \x20                   Target.LINUX_AARCH64\n\
         \x20               else -> throw UnsupportedOperationException(\"Unsupported architecture on Linux/Unix: $osArch\")\n\
         \x20           }}\n\
         \x20           else -> throw UnsupportedOperationException(\"Unsupported platform: $osName\")\n\
         \x20       }}\n\
         \x20       target\n\
         \x20   }}\n\
         \n\
         \x20   private fun unzipLibrary(compressedLib: InputStream): Result<File> = runCatching {{\n\
         \x20       val zipInputStream = ZipInputStream(compressedLib)\n\
         \x20       val buffer = ByteArray(1024)\n\
         \x20       val zipEntry = zipInputStream.nextEntry!!\n\
         \x20       val library = File.createTempFile(zipEntry.name, \".tmp\")\n\
         \x20       library.deleteOnExit()\n\
         \x20       val parent = library.parentFile\n\
         \x20       if (!parent.exists()) parent.mkdirs()\n\
         \x20       val fileOutputStream = FileOutputStream(library)\n\
         \x20       var len: Int\n\
         \x20       while (zipInputStream.read(buffer).also {{ len = it }} > 0) {{\n\
         \x20           fileOutputStream.write(buffer, 0, len)\n\
         \x20       }}\n\
         \x20       fileOutputStream.close()\n\
         \x20       zipInputStream.closeEntry()\n\
         \x20       zipInputStream.close()\n\
         \x20       library\n\
         \x20   }}\n\
         \n\
         \x20   private fun loadLibraryAsInputStream(target: Target): Result<InputStream> = runCatching {{\n\
         \x20       val targetName = \"$target/$target.zip\"\n\
         \x20       val libUrl = ClassLoader.getSystemClassLoader().getResourceAsStream(targetName)\n\
         \x20           ?: javaClass.classLoader.getResourceAsStream(targetName)!!\n\
         \x20       val uncompressedLibFile = unzipLibrary(libUrl)\n\
         \x20       FileInputStream(uncompressedLibFile.getOrThrow())\n\
         \x20   }}\n\
         \n\
         \x20   @Suppress(\"UnsafeDynamicallyLoadedCode\")\n\
         \x20   private fun loadNativeLib(inputStream: InputStream) {{\n\
         \x20       val tempLib = File.createTempFile(\"tempLib\", \".tmp\")\n\
         \x20       tempLib.deleteOnExit()\n\
         \x20       FileOutputStream(tempLib).use {{ output -> inputStream.copyTo(output) }}\n\
         \x20       System.load(tempLib.absolutePath)\n\
         \x20   }}\n\
         \n\
         \x20   private fun tryLoadingLibraryFromJarPackage(target: Target): Result<Unit> = runCatching {{\n\
         \x20       val lib: Result<InputStream> = loadLibraryAsInputStream(target)\n\
         \x20       lib.onSuccess {{ loadNativeLib(it) }}.onFailure {{ throw Exception(\"Unable to load native lib: $it\") }}\n\
         \x20   }}\n\
         \n\
         \x20   private fun tryLoadingLocalLibrary(): Result<Unit> = runCatching {{\n\
         \x20       val lib = ClassLoader.getSystemClassLoader().findLibraryStream(LIB_NAME)\n\
         \x20           ?: javaClass.classLoader.findLibraryStream(LIB_NAME)\n\
         \x20       if (lib != null) {{\n\
         \x20           loadNativeLib(lib)\n\
         \x20       }} else {{\n\
         \x20           throw Exception(\"Unable to load local native lib.\")\n\
         \x20       }}\n\
         \x20   }}\n\
         }}\n\
         \n\
         private fun ClassLoader.findLibraryStream(libraryName: String): InputStream? {{\n\
         \x20   val libraryExtensions = listOf(\".dylib\", \".so\", \".dll\")\n\
         \x20   for (extension in libraryExtensions) {{\n\
         \x20       val resourcePath = \"lib$libraryName$extension\"\n\
         \x20       val inputStream = getResourceAsStream(resourcePath)\n\
         \x20       if (inputStream != null) return inputStream\n\
         \x20   }}\n\
         \x20   return null\n\
         }}\n",
    ));
    out
}
