use crate::kotlin::kotlin_ext::KotlinFile;

pub(crate) fn emit_native_handle(package: &str, exception_fqn: &str) -> KotlinFile {
    KotlinFile {
        package: package.to_string(),
        class_name: "NativeHandle".into(),
        contents: render_native_handle_source(package, exception_fqn),
    }
}

fn render_native_handle_source(package: &str, exception_fqn: &str) -> String {
    let exc_short = exception_fqn.rsplit('.').next().unwrap_or(exception_fqn);
    let exception_pkg = exception_fqn.rsplit_once('.').map(|(p, _)| p).unwrap_or("");
    let import_line = if exception_fqn.contains('.') && exception_pkg != package {
        format!("import {}\n", exception_fqn)
    } else {
        String::new()
    };
    let body = r#"
__EXCEPTION_IMPORT__
import java.util.concurrent.locks.ReentrantReadWriteLock
import kotlin.concurrent.read
import kotlin.concurrent.write

/**
 * Race-free wrapper around a raw `Box<T>` pointer obtained from native
 * code via `Box::into_raw(Box::new(v))`. Pairs the pointer with a
 * `ReentrantReadWriteLock` so that borrow-style JNI calls run in
 * parallel under the read lock and consume/free serialise against
 * them under the write lock.
 *
 * This is the Java-side half of the type-conversion rule for opaque
 * handles: `&T` parameters route through [withPtr] (borrow); by-value
 * `T` parameters route through [consume] (write lock, slot stays
 * valid during the action, then null-ed in `finally`); destructor
 * entry points without a matching `#[prebindgen]` fn use [free]. The
 * auto-generated wrappers in `JNIWrappers.kt` are the only callers
 * that need to know which mode applies.
 *
 * Marked `open` so the hand-maintained `JNI*.kt` typed-handle classes
 * can subclass for type safety while inheriting the lock contract.
 */
public open class NativeHandle(initial: Long) {
    private val lock = ReentrantReadWriteLock()

    /** Volatile so [peek] is atomic on 32-bit JVMs and observes the
     *  write done by [free] / [consume] without holding the lock. */
    @Volatile private var ptr: Long = initial

    /**
     * Run [block] with the live pointer under the read lock. Throws
    * [ZError] if [free] has already released the handle. Multiple
    * concurrent invocations run in parallel; only [free]/[consume]
     * are serialised against them.
     */
    @Throws(ZError::class)
    public fun <T> withPtr(block: (Long) -> T): T = lock.read {
        val p = ptr
        if (p == 0L) throw ZError("Operation on a closed native handle.")
        block(p)
    }

    /**
     * Take the pointer under the write lock and pass it to [freeFn]
     * exactly once. Subsequent [free] calls are no-ops. Blocks until
     * all in-flight [withPtr] calls finish.
     */
    public fun free(freeFn: (Long) -> Unit) {
        lock.write {
            val p = ptr
            if (p == 0L) return@write
            ptr = 0L
            freeFn(p)
        }
    }

    /**
     * Consume the pointer: take it under the write lock, run [action]
     * with the captured pointer, then null the slot - even if [action]
     * throws. Used by the generator-emitted wrappers whose Rust side
     * runs `*Box::from_raw(...)` - i.e. by-value `T` opaque-handle
     * parameters and `impl Into<T>` arms with `IntoSourceMode::Consume`.
     *
     * The slot stays valid during [action] so the wrapper can pass the
     * typed handle to JNI and have JNI extract the pointer via [peek]
     * - symmetric with [withPtr] for the Borrow path. Unique-ownership
     * is still guaranteed: the write lock excludes every other
    * [withPtr] / [consume] / [free], and the `finally` clause
     * unconditionally nulls the slot before the lock is released, so
    * the next [withPtr] / [consume] / [free] sees `ptr == 0` and
     * cannot reach the freed allocation.
     *
     * Throws if the handle has already been closed/consumed.
     */
    @Throws(ZError::class)
    public fun <R> consume(action: (Long) -> R): R = lock.write {
        val p = ptr
        if (p == 0L) throw ZError("Operation on a closed native handle.")
        try {
            action(p)
        } finally {
            ptr = 0L
        }
    }

    /** True iff [free] has run. */
    public fun isClosed(): Boolean = lock.read { ptr == 0L }

    /**
     * Read the current pointer value without holding the lock.
     * Returns `0L` if the handle has been closed/consumed.
     */
    public fun peek(): Long = ptr
}
"#;
    let import_replacement = if import_line.is_empty() {
        String::new()
    } else {
        import_line.trim_end_matches('\n').to_string()
    };
    let body = body
        .replace("__EXCEPTION_IMPORT__\n", &if import_replacement.is_empty() {
            String::new()
        } else {
            format!("{}\n", import_replacement)
        })
        .replace("ZError", exc_short);

    let mut out = String::new();
    out.push_str("// Auto-generated by JniExt - do not edit by hand.\n");
    if !package.is_empty() {
        out.push_str(&format!("package {}\n", package));
    }
    out.push_str(&body);
    out
}
