// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni.bytes

import io.zenoh.jni.JNINative
import io.zenoh.jni.JniBindingError

public data class Encoding(
    val id: Int,
    val schema: String?,
) {
    @Throws(JniBindingError::class)
    public fun encodingToString(): String =
        JNINative.encodingToString(this)


    public companion object {
        @Throws(JniBindingError::class)
        public fun encodingFromString(s: String): Encoding =
            JNINative.encodingFromString(s)


        @Throws(JniBindingError::class)
        public fun encodingZenohBytes(): Encoding =
            JNINative.encodingZenohBytes()


        @Throws(JniBindingError::class)
        public fun encodingZenohString(): Encoding =
            JNINative.encodingZenohString()


        @Throws(JniBindingError::class)
        public fun encodingZenohSerialized(): Encoding =
            JNINative.encodingZenohSerialized()


        @Throws(JniBindingError::class)
        public fun encodingApplicationOctetStream(): Encoding =
            JNINative.encodingApplicationOctetStream()


        @Throws(JniBindingError::class)
        public fun encodingTextPlain(): Encoding =
            JNINative.encodingTextPlain()


        @Throws(JniBindingError::class)
        public fun encodingApplicationJson(): Encoding =
            JNINative.encodingApplicationJson()


        @Throws(JniBindingError::class)
        public fun encodingTextJson(): Encoding =
            JNINative.encodingTextJson()


        @Throws(JniBindingError::class)
        public fun encodingApplicationCdr(): Encoding =
            JNINative.encodingApplicationCdr()


        @Throws(JniBindingError::class)
        public fun encodingApplicationCbor(): Encoding =
            JNINative.encodingApplicationCbor()


        @Throws(JniBindingError::class)
        public fun encodingApplicationYaml(): Encoding =
            JNINative.encodingApplicationYaml()


        @Throws(JniBindingError::class)
        public fun encodingTextYaml(): Encoding =
            JNINative.encodingTextYaml()


        @Throws(JniBindingError::class)
        public fun encodingTextJson5(): Encoding =
            JNINative.encodingTextJson5()


        @Throws(JniBindingError::class)
        public fun encodingApplicationPythonSerializedObject(): Encoding =
            JNINative.encodingApplicationPythonSerializedObject()


        @Throws(JniBindingError::class)
        public fun encodingApplicationProtobuf(): Encoding =
            JNINative.encodingApplicationProtobuf()


        @Throws(JniBindingError::class)
        public fun encodingApplicationJavaSerializedObject(): Encoding =
            JNINative.encodingApplicationJavaSerializedObject()


        @Throws(JniBindingError::class)
        public fun encodingApplicationOpenmetricsText(): Encoding =
            JNINative.encodingApplicationOpenmetricsText()


        @Throws(JniBindingError::class)
        public fun encodingImagePng(): Encoding =
            JNINative.encodingImagePng()


        @Throws(JniBindingError::class)
        public fun encodingImageJpeg(): Encoding =
            JNINative.encodingImageJpeg()


        @Throws(JniBindingError::class)
        public fun encodingImageGif(): Encoding =
            JNINative.encodingImageGif()


        @Throws(JniBindingError::class)
        public fun encodingImageBmp(): Encoding =
            JNINative.encodingImageBmp()


        @Throws(JniBindingError::class)
        public fun encodingImageWebp(): Encoding =
            JNINative.encodingImageWebp()


        @Throws(JniBindingError::class)
        public fun encodingApplicationXml(): Encoding =
            JNINative.encodingApplicationXml()


        @Throws(JniBindingError::class)
        public fun encodingApplicationXWwwFormUrlencoded(): Encoding =
            JNINative.encodingApplicationXWwwFormUrlencoded()


        @Throws(JniBindingError::class)
        public fun encodingTextHtml(): Encoding =
            JNINative.encodingTextHtml()


        @Throws(JniBindingError::class)
        public fun encodingTextXml(): Encoding =
            JNINative.encodingTextXml()


        @Throws(JniBindingError::class)
        public fun encodingTextCss(): Encoding =
            JNINative.encodingTextCss()


        @Throws(JniBindingError::class)
        public fun encodingTextJavascript(): Encoding =
            JNINative.encodingTextJavascript()


        @Throws(JniBindingError::class)
        public fun encodingTextMarkdown(): Encoding =
            JNINative.encodingTextMarkdown()


        @Throws(JniBindingError::class)
        public fun encodingTextCsv(): Encoding =
            JNINative.encodingTextCsv()


        @Throws(JniBindingError::class)
        public fun encodingApplicationSql(): Encoding =
            JNINative.encodingApplicationSql()


        @Throws(JniBindingError::class)
        public fun encodingApplicationCoapPayload(): Encoding =
            JNINative.encodingApplicationCoapPayload()


        @Throws(JniBindingError::class)
        public fun encodingApplicationJsonPatchJson(): Encoding =
            JNINative.encodingApplicationJsonPatchJson()


        @Throws(JniBindingError::class)
        public fun encodingApplicationJsonSeq(): Encoding =
            JNINative.encodingApplicationJsonSeq()


        @Throws(JniBindingError::class)
        public fun encodingApplicationJsonpath(): Encoding =
            JNINative.encodingApplicationJsonpath()


        @Throws(JniBindingError::class)
        public fun encodingApplicationJwt(): Encoding =
            JNINative.encodingApplicationJwt()


        @Throws(JniBindingError::class)
        public fun encodingApplicationMp4(): Encoding =
            JNINative.encodingApplicationMp4()


        @Throws(JniBindingError::class)
        public fun encodingApplicationSoapXml(): Encoding =
            JNINative.encodingApplicationSoapXml()


        @Throws(JniBindingError::class)
        public fun encodingApplicationYang(): Encoding =
            JNINative.encodingApplicationYang()


        @Throws(JniBindingError::class)
        public fun encodingAudioAac(): Encoding =
            JNINative.encodingAudioAac()


        @Throws(JniBindingError::class)
        public fun encodingAudioFlac(): Encoding =
            JNINative.encodingAudioFlac()


        @Throws(JniBindingError::class)
        public fun encodingAudioMp4(): Encoding =
            JNINative.encodingAudioMp4()


        @Throws(JniBindingError::class)
        public fun encodingAudioOgg(): Encoding =
            JNINative.encodingAudioOgg()


        @Throws(JniBindingError::class)
        public fun encodingAudioVorbis(): Encoding =
            JNINative.encodingAudioVorbis()


        @Throws(JniBindingError::class)
        public fun encodingVideoH261(): Encoding =
            JNINative.encodingVideoH261()


        @Throws(JniBindingError::class)
        public fun encodingVideoH263(): Encoding =
            JNINative.encodingVideoH263()


        @Throws(JniBindingError::class)
        public fun encodingVideoH264(): Encoding =
            JNINative.encodingVideoH264()


        @Throws(JniBindingError::class)
        public fun encodingVideoH265(): Encoding =
            JNINative.encodingVideoH265()


        @Throws(JniBindingError::class)
        public fun encodingVideoH266(): Encoding =
            JNINative.encodingVideoH266()


        @Throws(JniBindingError::class)
        public fun encodingVideoMp4(): Encoding =
            JNINative.encodingVideoMp4()


        @Throws(JniBindingError::class)
        public fun encodingVideoOgg(): Encoding =
            JNINative.encodingVideoOgg()


        @Throws(JniBindingError::class)
        public fun encodingVideoRaw(): Encoding =
            JNINative.encodingVideoRaw()


        @Throws(JniBindingError::class)
        public fun encodingVideoVp8(): Encoding =
            JNINative.encodingVideoVp8()


        @Throws(JniBindingError::class)
        public fun encodingVideoVp9(): Encoding =
            JNINative.encodingVideoVp9()

    }
}
