// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni.bytes

import io.zenoh.jni.JNINative
import io.zenoh.jni.JniBindingError

public data class Encoding(
    val id: Int,
    val schema: String?,
) {
    @Throws(JniBindingError::class)
    public fun zEncodingToString(): String =
        JNINative.zEncodingToString(this)


    public companion object {
        @Throws(JniBindingError::class)
        public fun zEncodingZenohBytes(): Encoding =
            JNINative.zEncodingZenohBytes()


        @Throws(JniBindingError::class)
        public fun zEncodingZenohString(): Encoding =
            JNINative.zEncodingZenohString()


        @Throws(JniBindingError::class)
        public fun zEncodingZenohSerialized(): Encoding =
            JNINative.zEncodingZenohSerialized()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationOctetStream(): Encoding =
            JNINative.zEncodingApplicationOctetStream()


        @Throws(JniBindingError::class)
        public fun zEncodingTextPlain(): Encoding =
            JNINative.zEncodingTextPlain()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationJson(): Encoding =
            JNINative.zEncodingApplicationJson()


        @Throws(JniBindingError::class)
        public fun zEncodingTextJson(): Encoding =
            JNINative.zEncodingTextJson()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationCdr(): Encoding =
            JNINative.zEncodingApplicationCdr()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationCbor(): Encoding =
            JNINative.zEncodingApplicationCbor()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationYaml(): Encoding =
            JNINative.zEncodingApplicationYaml()


        @Throws(JniBindingError::class)
        public fun zEncodingTextYaml(): Encoding =
            JNINative.zEncodingTextYaml()


        @Throws(JniBindingError::class)
        public fun zEncodingTextJson5(): Encoding =
            JNINative.zEncodingTextJson5()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationPythonSerializedObject(): Encoding =
            JNINative.zEncodingApplicationPythonSerializedObject()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationProtobuf(): Encoding =
            JNINative.zEncodingApplicationProtobuf()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationJavaSerializedObject(): Encoding =
            JNINative.zEncodingApplicationJavaSerializedObject()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationOpenmetricsText(): Encoding =
            JNINative.zEncodingApplicationOpenmetricsText()


        @Throws(JniBindingError::class)
        public fun zEncodingImagePng(): Encoding =
            JNINative.zEncodingImagePng()


        @Throws(JniBindingError::class)
        public fun zEncodingImageJpeg(): Encoding =
            JNINative.zEncodingImageJpeg()


        @Throws(JniBindingError::class)
        public fun zEncodingImageGif(): Encoding =
            JNINative.zEncodingImageGif()


        @Throws(JniBindingError::class)
        public fun zEncodingImageBmp(): Encoding =
            JNINative.zEncodingImageBmp()


        @Throws(JniBindingError::class)
        public fun zEncodingImageWebp(): Encoding =
            JNINative.zEncodingImageWebp()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationXml(): Encoding =
            JNINative.zEncodingApplicationXml()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationXWwwFormUrlencoded(): Encoding =
            JNINative.zEncodingApplicationXWwwFormUrlencoded()


        @Throws(JniBindingError::class)
        public fun zEncodingTextHtml(): Encoding =
            JNINative.zEncodingTextHtml()


        @Throws(JniBindingError::class)
        public fun zEncodingTextXml(): Encoding =
            JNINative.zEncodingTextXml()


        @Throws(JniBindingError::class)
        public fun zEncodingTextCss(): Encoding =
            JNINative.zEncodingTextCss()


        @Throws(JniBindingError::class)
        public fun zEncodingTextJavascript(): Encoding =
            JNINative.zEncodingTextJavascript()


        @Throws(JniBindingError::class)
        public fun zEncodingTextMarkdown(): Encoding =
            JNINative.zEncodingTextMarkdown()


        @Throws(JniBindingError::class)
        public fun zEncodingTextCsv(): Encoding =
            JNINative.zEncodingTextCsv()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationSql(): Encoding =
            JNINative.zEncodingApplicationSql()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationCoapPayload(): Encoding =
            JNINative.zEncodingApplicationCoapPayload()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationJsonPatchJson(): Encoding =
            JNINative.zEncodingApplicationJsonPatchJson()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationJsonSeq(): Encoding =
            JNINative.zEncodingApplicationJsonSeq()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationJsonpath(): Encoding =
            JNINative.zEncodingApplicationJsonpath()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationJwt(): Encoding =
            JNINative.zEncodingApplicationJwt()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationMp4(): Encoding =
            JNINative.zEncodingApplicationMp4()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationSoapXml(): Encoding =
            JNINative.zEncodingApplicationSoapXml()


        @Throws(JniBindingError::class)
        public fun zEncodingApplicationYang(): Encoding =
            JNINative.zEncodingApplicationYang()


        @Throws(JniBindingError::class)
        public fun zEncodingAudioAac(): Encoding =
            JNINative.zEncodingAudioAac()


        @Throws(JniBindingError::class)
        public fun zEncodingAudioFlac(): Encoding =
            JNINative.zEncodingAudioFlac()


        @Throws(JniBindingError::class)
        public fun zEncodingAudioMp4(): Encoding =
            JNINative.zEncodingAudioMp4()


        @Throws(JniBindingError::class)
        public fun zEncodingAudioOgg(): Encoding =
            JNINative.zEncodingAudioOgg()


        @Throws(JniBindingError::class)
        public fun zEncodingAudioVorbis(): Encoding =
            JNINative.zEncodingAudioVorbis()


        @Throws(JniBindingError::class)
        public fun zEncodingVideoH261(): Encoding =
            JNINative.zEncodingVideoH261()


        @Throws(JniBindingError::class)
        public fun zEncodingVideoH263(): Encoding =
            JNINative.zEncodingVideoH263()


        @Throws(JniBindingError::class)
        public fun zEncodingVideoH264(): Encoding =
            JNINative.zEncodingVideoH264()


        @Throws(JniBindingError::class)
        public fun zEncodingVideoH265(): Encoding =
            JNINative.zEncodingVideoH265()


        @Throws(JniBindingError::class)
        public fun zEncodingVideoH266(): Encoding =
            JNINative.zEncodingVideoH266()


        @Throws(JniBindingError::class)
        public fun zEncodingVideoMp4(): Encoding =
            JNINative.zEncodingVideoMp4()


        @Throws(JniBindingError::class)
        public fun zEncodingVideoOgg(): Encoding =
            JNINative.zEncodingVideoOgg()


        @Throws(JniBindingError::class)
        public fun zEncodingVideoRaw(): Encoding =
            JNINative.zEncodingVideoRaw()


        @Throws(JniBindingError::class)
        public fun zEncodingVideoVp8(): Encoding =
            JNINative.zEncodingVideoVp8()


        @Throws(JniBindingError::class)
        public fun zEncodingVideoVp9(): Encoding =
            JNINative.zEncodingVideoVp9()

    }
}
