// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.bytes

import io.zenoh.jni.ErrorHolder
import io.zenoh.jni.ErrorSink
import io.zenoh.jni.ZException
import io.zenoh.jni.bytes.ZEncoding
import io.zenoh.jni.bytes.ZZBytes
import io.zenoh.jni.withSortedHandleLocks
import io.zenoh.jni.JNINative

public fun zZbytesToBytes(z: ZZBytes): ByteArray {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(z) {
    val z_ptr = z.ptr
    if (z_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zZbytesToBytes(z_ptr, __sink)
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zZbytesClone(z: ZZBytes): ZZBytes {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(z) {
    val z_ptr = z.ptr
    if (z_ptr == 0L) throw ZException("Operation on a closed native handle.")
    ZZBytes(JNINative.zZbytesClone(z_ptr, __sink))
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zZbytesFromVec(bytes: ByteArray): ZZBytes {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZZBytes(JNINative.zZbytesFromVec(bytes, __sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingId(e: ZEncoding): Int {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(e) {
    val e_ptr = e.ptr
    if (e_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zEncodingId(e_ptr, __sink)
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingSchema(e: ZEncoding): String {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(e) {
    val e_ptr = e.ptr
    if (e_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zEncodingSchema(e_ptr, __sink)
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingToString(e: ZEncoding): String {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(e) {
    val e_ptr = e.ptr
    if (e_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zEncodingToString(e_ptr, __sink)
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingClone(e: ZEncoding): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(e) {
    val e_ptr = e.ptr
    if (e_ptr == 0L) throw ZException("Operation on a closed native handle.")
    ZEncoding(JNINative.zEncodingClone(e_ptr, __sink))
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingFromString(s: String): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingFromString(s, __sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingWithSchema(e: ZEncoding, schema: String): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(e) {
    val e_ptr = e.ptr
    if (e_ptr == 0L) throw ZException("Operation on a closed native handle.")
    ZEncoding(JNINative.zEncodingWithSchema(e_ptr, schema, __sink))
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingZenohBytes(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingZenohBytes(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingZenohString(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingZenohString(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingZenohSerialized(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingZenohSerialized(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationOctetStream(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationOctetStream(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingTextPlain(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingTextPlain(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationJson(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationJson(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingTextJson(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingTextJson(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationCdr(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationCdr(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationCbor(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationCbor(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationYaml(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationYaml(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingTextYaml(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingTextYaml(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingTextJson5(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingTextJson5(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationPythonSerializedObject(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationPythonSerializedObject(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationProtobuf(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationProtobuf(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationJavaSerializedObject(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationJavaSerializedObject(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationOpenmetricsText(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationOpenmetricsText(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingImagePng(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingImagePng(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingImageJpeg(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingImageJpeg(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingImageGif(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingImageGif(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingImageBmp(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingImageBmp(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingImageWebp(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingImageWebp(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationXml(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationXml(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationXWwwFormUrlencoded(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationXWwwFormUrlencoded(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingTextHtml(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingTextHtml(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingTextXml(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingTextXml(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingTextCss(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingTextCss(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingTextJavascript(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingTextJavascript(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingTextMarkdown(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingTextMarkdown(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingTextCsv(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingTextCsv(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationSql(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationSql(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationCoapPayload(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationCoapPayload(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationJsonPatchJson(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationJsonPatchJson(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationJsonSeq(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationJsonSeq(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationJsonpath(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationJsonpath(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationJwt(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationJwt(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationMp4(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationMp4(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationSoapXml(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationSoapXml(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingApplicationYang(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingApplicationYang(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingAudioAac(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingAudioAac(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingAudioFlac(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingAudioFlac(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingAudioMp4(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingAudioMp4(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingAudioOgg(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingAudioOgg(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingAudioVorbis(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingAudioVorbis(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingVideoH261(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingVideoH261(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingVideoH263(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingVideoH263(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingVideoH264(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingVideoH264(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingVideoH265(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingVideoH265(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingVideoH266(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingVideoH266(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingVideoMp4(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingVideoMp4(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingVideoOgg(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingVideoOgg(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingVideoRaw(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingVideoRaw(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingVideoVp8(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingVideoVp8(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zEncodingVideoVp9(): ZEncoding {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = ZEncoding(JNINative.zEncodingVideoVp9(__sink))
    __err.message?.let { throw ZException(it) }
    return __ret
}

