// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.bytes

import io.zenoh.jni.ZException
import io.zenoh.jni.bytes.ZEncoding
import io.zenoh.jni.bytes.ZZBytes
import io.zenoh.jni.withSortedHandleLocks
import io.zenoh.jni.JNINative

public fun zZbytesToBytes(z: ZZBytes, onError: (String?) -> ByteArray = { __de_je -> throw ZException(__de_je) }): ByteArray {
    if (z.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(z) {
    val z_ptr = z.ptr
    JNINative.zZbytesToBytes(z_ptr, __cap)
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zZbytesClone(z: ZZBytes, onError: (String?) -> ZZBytes = { __de_je -> throw ZException(__de_je) }): ZZBytes {
    if (z.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(z) {
    val z_ptr = z.ptr
    ZZBytes(JNINative.zZbytesClone(z_ptr, __cap))
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zZbytesFromVec(bytes: ByteArray, onError: (String?) -> ZZBytes = { __de_je -> throw ZException(__de_je) }): ZZBytes {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZZBytes(JNINative.zZbytesFromVec(bytes, __cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingId(e: ZEncoding, onError: (String?) -> Int = { __de_je -> throw ZException(__de_je) }): Int {
    if (e.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(e) {
    val e_ptr = e.ptr
    JNINative.zEncodingId(e_ptr, __cap)
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingSchema(e: ZEncoding, onError: (String?) -> String? = { __de_je -> throw ZException(__de_je) }): String? {
    if (e.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(e) {
    val e_ptr = e.ptr
    JNINative.zEncodingSchema(e_ptr, __cap)
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingToString(e: ZEncoding, onError: (String?) -> String = { __de_je -> throw ZException(__de_je) }): String {
    if (e.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(e) {
    val e_ptr = e.ptr
    JNINative.zEncodingToString(e_ptr, __cap)
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingClone(e: ZEncoding, onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    if (e.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(e) {
    val e_ptr = e.ptr
    ZEncoding(JNINative.zEncodingClone(e_ptr, __cap))
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingFromString(s: String, onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingFromString(s, __cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingWithSchema(e: ZEncoding, schema: String, onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    if (e.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(e) {
    val e_ptr = e.ptr
    ZEncoding(JNINative.zEncodingWithSchema(e_ptr, schema, __cap))
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingZenohBytes(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingZenohBytes(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingZenohString(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingZenohString(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingZenohSerialized(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingZenohSerialized(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationOctetStream(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationOctetStream(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingTextPlain(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingTextPlain(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationJson(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationJson(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingTextJson(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingTextJson(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationCdr(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationCdr(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationCbor(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationCbor(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationYaml(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationYaml(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingTextYaml(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingTextYaml(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingTextJson5(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingTextJson5(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationPythonSerializedObject(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationPythonSerializedObject(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationProtobuf(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationProtobuf(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationJavaSerializedObject(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationJavaSerializedObject(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationOpenmetricsText(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationOpenmetricsText(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingImagePng(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingImagePng(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingImageJpeg(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingImageJpeg(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingImageGif(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingImageGif(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingImageBmp(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingImageBmp(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingImageWebp(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingImageWebp(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationXml(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationXml(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationXWwwFormUrlencoded(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationXWwwFormUrlencoded(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingTextHtml(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingTextHtml(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingTextXml(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingTextXml(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingTextCss(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingTextCss(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingTextJavascript(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingTextJavascript(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingTextMarkdown(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingTextMarkdown(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingTextCsv(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingTextCsv(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationSql(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationSql(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationCoapPayload(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationCoapPayload(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationJsonPatchJson(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationJsonPatchJson(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationJsonSeq(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationJsonSeq(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationJsonpath(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationJsonpath(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationJwt(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationJwt(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationMp4(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationMp4(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationSoapXml(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationSoapXml(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingApplicationYang(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingApplicationYang(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingAudioAac(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingAudioAac(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingAudioFlac(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingAudioFlac(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingAudioMp4(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingAudioMp4(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingAudioOgg(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingAudioOgg(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingAudioVorbis(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingAudioVorbis(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingVideoH261(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingVideoH261(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingVideoH263(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingVideoH263(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingVideoH264(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingVideoH264(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingVideoH265(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingVideoH265(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingVideoH266(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingVideoH266(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingVideoMp4(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingVideoMp4(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingVideoOgg(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingVideoOgg(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingVideoRaw(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingVideoRaw(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingVideoVp8(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingVideoVp8(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zEncodingVideoVp9(onError: (String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) }): ZEncoding {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZEncoding(JNINative.zEncodingVideoVp9(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

