// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni.bytes

import io.zenoh.jni.JNINative
import io.zenoh.jni.JniBindingError

/** Typed handle for a native Zenoh `ZZBytes`. */
public class ZZBytes(initialPtr: Long) : AutoCloseable {
    @Volatile internal var ptr: Long = initialPtr

    public fun peek(): Long = ptr
    public fun isClosed(): Boolean = ptr == 0L

    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZZBytes {
        val p = ptr
        ptr = 0L
        return ZZBytes(p)
    }

    @Throws(JniBindingError::class)
    public fun zZbytesToBytes(): ByteArray {
        synchronized(this) {
            val z_ptr = this.ptr
            if (z_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
            return JNINative.zZbytesToBytes(z_ptr)
        }
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)

        @Throws(JniBindingError::class)
        public fun zZbytesFromBytes(bytes: ByteArray): ZZBytes =
            ZZBytes(JNINative.zZbytesFromBytes(bytes))
    }
}
