// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni.bytes

import io.zenoh.jni.JNINative
import io.zenoh.jni.JNINativeHandle
import io.zenoh.jni.JniBindingError

/** Typed [JNINativeHandle] for a native Zenoh `ZZBytes`. */
public class ZZBytes(initialPtr: Long) : JNINativeHandle(initialPtr), AutoCloseable {
    private val cleanable: java.lang.ref.Cleaner.Cleanable =
        JNINativeHandle.CLEANER.register(this, Cleanup(state))

    override fun close() = cleanable.clean()

    private class Cleanup(private val state: JNINativeHandle.State) : Runnable {
        override fun run() = state.freeOnce { ZZBytes.freePtr(it) }
    }

    @Throws(JniBindingError::class)
    public fun zZbytesToBytes(): ByteArray =
        withPtr { z_ptr ->
        JNINative.zZbytesToBytes(z_ptr)
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)

        @Throws(JniBindingError::class)
        public fun zZbytesFromBytes(bytes: ByteArray): ZZBytes =
            ZZBytes(JNINative.zZbytesFromBytes(bytes))
    }
}
