// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.liveliness

/** Typed handle for a native Zenoh `ZLivelinessToken`. */
public class ZLivelinessToken(initialPtr: Long) : AutoCloseable {
    @Volatile internal var ptr: Long = initialPtr

    public fun peek(): Long = ptr
    public fun isClosed(): Boolean = ptr == 0L

    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZLivelinessToken {
        val p = ptr
        ptr = 0L
        return ZLivelinessToken(p)
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}
