[package]
name = "zenoh-flat"
version = "1.9.0"
edition = "2024"

[dependencies]
zenoh = { version = "1.9.0", git = "https://github.com/eclipse-zenoh/zenoh.git", branch = "main", features = ["unstable", "internal"], default-features = false }
zenoh-ext = { version = "1.9.0", git = "https://github.com/eclipse-zenoh/zenoh.git", branch = "main", features = ["internal"], default-features = false, optional = true }
tracing = { version = "0.1" , features = ["log"] }
prebindgen = "0.4.1"
prebindgen-proc-macro = "0.4.1"
json5 = "0.4.1"
serde_yaml = "0.9.19"

[build-dependencies]
prebindgen = "0.4.1"
