// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.scouting

import io.zenoh.jni.config.WhatAmI
import io.zenoh.jni.config.ZenohId

public data class Hello(
    val whatami: WhatAmI,
    val zid: ZenohId,
    val locators: List<String>,
) {
    public companion object {
        @JvmStatic
        public fun fromParts(
            whatami: Int,
            zid: ByteArray,
            locators: List<String>
        ): Hello = Hello(
            WhatAmI.fromInt(whatami),
            ZenohId(zid),
            locators
        )
    }
}
