// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.scouting

import io.zenoh.jni.ErrorHolder
import io.zenoh.jni.ErrorSink
import io.zenoh.jni.NativeHandle
import io.zenoh.jni.ZException
import io.zenoh.jni.callbacks.Callback
import io.zenoh.jni.callbacks.ZHelloCallback
import io.zenoh.jni.config.WhatAmI
import io.zenoh.jni.config.ZConfig
import io.zenoh.jni.config.ZZenohId
import io.zenoh.jni.scouting.ZHello
import io.zenoh.jni.scouting.ZScout
import io.zenoh.jni.withSortedHandleLocks
import io.zenoh.jni.JNINative

public fun zHelloWhatami(h: ZHello): WhatAmI {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(h) {
    val h_ptr = h.ptr
    if (h_ptr == 0L) throw ZException("Operation on a closed native handle.")
    WhatAmI.fromInt(JNINative.zHelloWhatami(h_ptr, __sink))
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zHelloZid(h: ZHello): ZZenohId {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(h) {
    val h_ptr = h.ptr
    if (h_ptr == 0L) throw ZException("Operation on a closed native handle.")
    ZZenohId(JNINative.zHelloZid(h_ptr, __sink))
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zHelloLocators(h: ZHello): List<String> {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(h) {
    val h_ptr = h.ptr
    if (h_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zHelloLocators(h_ptr, __sink)
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zScout(whatami: Int, config: ZConfig?, callback: ZHelloCallback, onClose: Callback): ZScout {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = run {
    val __locks = ArrayList<NativeHandle>()
    config?.let { __locks.add(it) }
    withSortedHandleLocks(__locks) {
    val config_ptr = config?.ptr ?: 0L
    if (config != null && config_ptr == 0L) throw ZException("Operation on a closed native handle.")
    ZScout(JNINative.zScout(whatami, config_ptr, callback, onClose, __sink))
    }
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

