// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.scouting

import io.zenoh.jni.NativeHandle
import io.zenoh.jni.ZException
import io.zenoh.jni.config.WhatAmI
import io.zenoh.jni.config.ZConfig
import io.zenoh.jni.config.ZZenohId
import io.zenoh.jni.scouting.ZHello
import io.zenoh.jni.scouting.ZScout
import io.zenoh.jni.withSortedHandleLocks
import io.zenoh.jni.JNINative

public fun zHelloWhatami(h: ZHello, onError: (String?) -> WhatAmI = { __de_je -> throw ZException(__de_je) }): WhatAmI {
    if (h.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(h) {
    val h_ptr = h.ptr
    WhatAmI.fromInt(JNINative.zHelloWhatami(h_ptr, __cap))
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zHelloZid(h: ZHello, onError: (String?) -> ZZenohId = { __de_je -> throw ZException(__de_je) }): ZZenohId {
    if (h.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(h) {
    val h_ptr = h.ptr
    ZZenohId(JNINative.zHelloZid(h_ptr, __cap))
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zHelloLocators(h: ZHello, onError: (String?) -> List<String> = { __de_je -> throw ZException(__de_je) }): List<String> {
    if (h.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(h) {
    val h_ptr = h.ptr
    JNINative.zHelloLocators(h_ptr, __cap)
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zScout(whatami: Int, config: ZConfig?, callback: (ZHello) -> Unit, onClose: () -> Unit, onError: (String?, String) -> ZScout = { __de_je, __de_z0 -> throw ZException(__de_je ?: __de_z0) }): ZScout {
    if (config != null && config.ptr == 0L) return onError("Operation on a closed native handle.", "")
    var __cap_failed = false
    var __cap_je: String? = null
    var __cap_ze0: String? = null
    val __cap = { __je: String?, __ze0: String? -> __cap_failed = true; __cap_je = __je; __cap_ze0 = __ze0 }
    val __ret = run {
    val __locks = ArrayList<NativeHandle>()
    config?.let { __locks.add(it) }
    withSortedHandleLocks(__locks) {
    val config_ptr = config?.ptr ?: 0L
    ZScout(JNINative.zScout(whatami, config_ptr, callback, onClose, __cap))
    }
    }
    if (__cap_failed) return onError(__cap_je, (__cap_ze0 ?: ""))
    return __ret
}

