// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.config

import io.zenoh.jni.JNINative
import io.zenoh.jni.JniErrorHandler
import io.zenoh.jni.JniErrorHandlerCapture
import io.zenoh.jni.NativeHandle
import io.zenoh.jni.errors.ZErrorHandler
import io.zenoh.jni.errors.ZErrorHandlerCapture
import io.zenoh.jni.withSortedHandleLocks

/** JVM-side surface for the native Rust `WhatAmI` enum. */
public enum class WhatAmI(public val value: Int) {
    ROUTER(1),
    PEER(2),
    CLIENT(4);

    public companion object {
        @JvmStatic
        public fun fromInt(value: Int): WhatAmI = entries.first { it.value == value }
    }
}

/**
 * Typed by-value wrapper for the native Rust `ZZenohId` (a `Copy` blob carried
 * as its raw bytes; `@JvmInline`-erased to `ByteArray` at the JNI boundary).
 */
@JvmInline
public value class ZZenohId(public val bytes: ByteArray)

/** Typed handle for a native Zenoh `ZConfig`. */
public class ZConfig(initialPtr: Long) : NativeHandle(initialPtr) {
    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZConfig {
        val p = ptr
        ptr = 0L
        return ZConfig(p)
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}

public fun zConfigDefault(onError: JniErrorHandler<ZConfig>): ZConfig {
    val __cap = JniErrorHandlerCapture.acquire()
    val __ret = ZConfig(JNINative.zConfigDefault(__cap))
    if (__cap.failed) return onError.run(__cap.je)
    return __ret
}

public fun zConfigFromFile(path: String, onError: ZErrorHandler<ZConfig>): ZConfig {
    val __cap = ZErrorHandlerCapture.acquire()
    val __ret = ZConfig(JNINative.zConfigFromFile(path, __cap))
    if (__cap.failed) return onError.run(__cap.je, __cap.ze0!!)
    return __ret
}

public fun zConfigFromJson(s: String, onError: ZErrorHandler<ZConfig>): ZConfig {
    val __cap = ZErrorHandlerCapture.acquire()
    val __ret = ZConfig(JNINative.zConfigFromJson(s, __cap))
    if (__cap.failed) return onError.run(__cap.je, __cap.ze0!!)
    return __ret
}

public fun zConfigFromJson5(s: String, onError: ZErrorHandler<ZConfig>): ZConfig {
    val __cap = ZErrorHandlerCapture.acquire()
    val __ret = ZConfig(JNINative.zConfigFromJson5(s, __cap))
    if (__cap.failed) return onError.run(__cap.je, __cap.ze0!!)
    return __ret
}

public fun zConfigFromYaml(s: String, onError: ZErrorHandler<ZConfig>): ZConfig {
    val __cap = ZErrorHandlerCapture.acquire()
    val __ret = ZConfig(JNINative.zConfigFromYaml(s, __cap))
    if (__cap.failed) return onError.run(__cap.je, __cap.ze0!!)
    return __ret
}

public fun zConfigGetJson(c: ZConfig, key: String, onError: JniErrorHandler<String>): String {
    if (c.ptr == 0L) return onError.run("Operation on a closed native handle.")
    val __cap = JniErrorHandlerCapture.acquire()
    val __ret = withSortedHandleLocks(c) {
        val c_ptr = c.ptr
        JNINative.zConfigGetJson(c_ptr, key, __cap)
    }
    if (__cap.failed) return onError.run(__cap.je)
    return __ret
}

public fun zConfigInsertJson5(c: ZConfig, key: String, value: String, onError: ZErrorHandler<Unit>) {
    if (c.ptr == 0L) { onError.run("Operation on a closed native handle.", ""); return }
    val __cap = ZErrorHandlerCapture.acquire()
    withSortedHandleLocks(c) {
        val c_ptr = c.ptr
        JNINative.zConfigInsertJson5(c_ptr, key, value, __cap)
    }
    if (__cap.failed) return onError.run(__cap.je, __cap.ze0!!)
}

public fun zConfigClone(c: ZConfig, onError: JniErrorHandler<ZConfig>): ZConfig {
    if (c.ptr == 0L) return onError.run("Operation on a closed native handle.")
    val __cap = JniErrorHandlerCapture.acquire()
    val __ret = withSortedHandleLocks(c) {
        val c_ptr = c.ptr
        ZConfig(JNINative.zConfigClone(c_ptr, __cap))
    }
    if (__cap.failed) return onError.run(__cap.je)
    return __ret
}

public fun zZenohIdToBytes(z: ZZenohId, onError: JniErrorHandler<ByteArray>): ByteArray {
    val __cap = JniErrorHandlerCapture.acquire()
    val __ret = JNINative.zZenohIdToBytes(z.bytes, __cap)
    if (__cap.failed) return onError.run(__cap.je)
    return __ret
}

public fun zZenohIdToString(z: ZZenohId, onError: JniErrorHandler<String>): String {
    val __cap = JniErrorHandlerCapture.acquire()
    val __ret = JNINative.zZenohIdToString(z.bytes, __cap)
    if (__cap.failed) return onError.run(__cap.je)
    return __ret
}
