// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.config

import io.zenoh.jni.JNINative
import io.zenoh.jni.NativeHandle
import io.zenoh.jni.withSortedHandleLocks

/** JVM-side surface for the native Rust `WhatAmI` enum. */
public enum class WhatAmI(public val value: Int) {
    ROUTER(1),
    PEER(2),
    CLIENT(4);

    public companion object {
        @JvmStatic
        public fun fromInt(value: Int): WhatAmI = entries.first { it.value == value }
    }
}

/**
 * Typed by-value wrapper for the native Rust `ZZenohId` (a `Copy` blob carried
 * as its raw bytes; `@JvmInline`-erased to `ByteArray` at the JNI boundary).
 */
@JvmInline
public value class ZZenohId(public val bytes: ByteArray)

/** Typed handle for a native Zenoh `ZConfig`. */
public class ZConfig(initialPtr: Long) : NativeHandle(initialPtr) {
    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZConfig {
        val p = ptr
        ptr = 0L
        return ZConfig(p)
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}

public fun zConfigDefault(onError: (je: String?) -> ZConfig): ZConfig {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = ZConfig(JNINative.zConfigDefault(__cap))
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zConfigFromFile(
    path: String,
    onError: (je: String?, message: String) -> ZConfig,
): ZConfig {
    var __cap_failed = false
    var __cap_je: String? = null
    var __cap_ze0: String? = null
    val __cap = {
        __je: String?,
        __ze0: String?,
        ->
        __cap_failed = true; __cap_je = __je; __cap_ze0 = __ze0
    }
    val __ret = ZConfig(JNINative.zConfigFromFile(path, __cap))
    if (__cap_failed) return onError(__cap_je, (__cap_ze0 ?: ""))
    return __ret
}

public fun zConfigFromJson(s: String, onError: (je: String?, message: String) -> ZConfig): ZConfig {
    var __cap_failed = false
    var __cap_je: String? = null
    var __cap_ze0: String? = null
    val __cap = {
        __je: String?,
        __ze0: String?,
        ->
        __cap_failed = true; __cap_je = __je; __cap_ze0 = __ze0
    }
    val __ret = ZConfig(JNINative.zConfigFromJson(s, __cap))
    if (__cap_failed) return onError(__cap_je, (__cap_ze0 ?: ""))
    return __ret
}

public fun zConfigFromJson5(s: String, onError: (je: String?, message: String) -> ZConfig): ZConfig {
    var __cap_failed = false
    var __cap_je: String? = null
    var __cap_ze0: String? = null
    val __cap = {
        __je: String?,
        __ze0: String?,
        ->
        __cap_failed = true; __cap_je = __je; __cap_ze0 = __ze0
    }
    val __ret = ZConfig(JNINative.zConfigFromJson5(s, __cap))
    if (__cap_failed) return onError(__cap_je, (__cap_ze0 ?: ""))
    return __ret
}

public fun zConfigFromYaml(s: String, onError: (je: String?, message: String) -> ZConfig): ZConfig {
    var __cap_failed = false
    var __cap_je: String? = null
    var __cap_ze0: String? = null
    val __cap = {
        __je: String?,
        __ze0: String?,
        ->
        __cap_failed = true; __cap_je = __je; __cap_ze0 = __ze0
    }
    val __ret = ZConfig(JNINative.zConfigFromYaml(s, __cap))
    if (__cap_failed) return onError(__cap_je, (__cap_ze0 ?: ""))
    return __ret
}

public fun zConfigGetJson(c: ZConfig, key: String, onError: (je: String?) -> String): String {
    if (c.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(c) {
        val c_ptr = c.ptr
        JNINative.zConfigGetJson(c_ptr, key, __cap)
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zConfigInsertJson5(
    c: ZConfig,
    key: String,
    value: String,
    onError: (je: String?, message: String) -> Unit,
) {
    if (c.ptr == 0L) { onError("Operation on a closed native handle.", ""); return }
    var __cap_failed = false
    var __cap_je: String? = null
    var __cap_ze0: String? = null
    val __cap = {
        __je: String?,
        __ze0: String?,
        ->
        __cap_failed = true; __cap_je = __je; __cap_ze0 = __ze0
    }
    withSortedHandleLocks(c) {
        val c_ptr = c.ptr
        JNINative.zConfigInsertJson5(c_ptr, key, value, __cap)
    }
    if (__cap_failed) return onError(__cap_je, (__cap_ze0 ?: ""))
}

public fun zConfigClone(c: ZConfig, onError: (je: String?) -> ZConfig): ZConfig {
    if (c.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(c) {
        val c_ptr = c.ptr
        ZConfig(JNINative.zConfigClone(c_ptr, __cap))
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zZenohIdToBytes(z: ZZenohId, onError: (je: String?) -> ByteArray): ByteArray {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = JNINative.zZenohIdToBytes(z.bytes, __cap)
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zZenohIdToString(z: ZZenohId, onError: (je: String?) -> String): String {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = JNINative.zZenohIdToString(z.bytes, __cap)
    if (__cap_failed) return onError(__cap_je)
    return __ret
}
