// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.errors

import io.zenoh.jni.JNINative
import io.zenoh.jni.JniErrorHandler
import io.zenoh.jni.JniErrorHandlerCapture
import io.zenoh.jni.NativeHandle
import io.zenoh.jni.withSortedHandleLocks

/** Typed handle for a native Zenoh `ZError`. */
public class ZError(initialPtr: Long) : NativeHandle(initialPtr) {
    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZError {
        val p = ptr
        ptr = 0L
        return ZError(p)
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}

public fun interface ZErrorHandler<out R> {
    public fun run(je: String?, message: String): R
}

internal class ZErrorHandlerCapture : ZErrorHandler<Unit> {
    @JvmField var failed: Boolean = false
    @JvmField var je: String? = null
    @JvmField var ze0: String? = null
    override fun run(je: String?, message: String) { failed = true; this.je = je; this.ze0 = message }
    companion object {
        private val TL: ThreadLocal<ZErrorHandlerCapture> = ThreadLocal.withInitial { ZErrorHandlerCapture() }
        @JvmStatic fun acquire(): ZErrorHandlerCapture {
            val c = TL.get()
            c.failed = false; c.je = null; c.ze0 = null
            return c
        }
    }
}

public fun zErrorMessage(e: ZError, onError: JniErrorHandler<String>): String {
    if (e.ptr == 0L) return onError.run("Operation on a closed native handle.")
    val __cap = JniErrorHandlerCapture.acquire()
    val __ret = withSortedHandleLocks(e) {
        val e_ptr = e.ptr
        JNINative.zErrorMessage(e_ptr, __cap)
    }
    if (__cap.failed) return onError.run(__cap.je)
    return __ret
}
