// Auto-generated by JniExt - do not edit by hand.
package io.zenoh.jni

/** JVM-side surface for the native Rust `Error` error. */
public class Error(override val message: String? = null) : Exception()
