// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni

/** JVM-side surface for the native Rust `JniBindingError` error. */
public class JniBindingError(override val message: String? = null) : Exception()
