// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni

import io.zenoh.jni.KeyExpr
import io.zenoh.jni.ZConfig
import io.zenoh.jni.ZKeyExpr

internal object JNINative {
    external fun keyexprAutocanonize(s: String): KeyExpr
    external fun keyexprConcat(a: Any, b: String): KeyExpr
    external fun keyexprIncludes(a: Any, b: Any): Boolean
    external fun keyexprIntersects(a: Any, b: Any): Boolean
    external fun keyexprJoin(a: Any, b: String): KeyExpr
    external fun keyexprRelationTo(a: Any, b: Any): Int
    external fun keyexprTryFrom(s: String): KeyExpr
    external fun zConfigDefault(): Long
    external fun zConfigFromFile(path: String): Long
    external fun zConfigFromJson(s: String): Long
    external fun zConfigFromJson5(s: String): Long
    external fun zConfigFromYaml(s: String): Long
    external fun zConfigGetJson(c: Long, key: String): String
    external fun zConfigInsertJson5(c: Long, key: String, value: String)
    external fun zKeyexprAutocanonize(s: String): Long
    external fun zKeyexprConcat(a: Long, b: String): Long
    external fun zKeyexprIncludes(a: Long, b: Long): Boolean
    external fun zKeyexprIntersects(a: Long, b: Long): Boolean
    external fun zKeyexprJoin(a: Long, b: String): Long
    external fun zKeyexprRelationTo(a: Long, b: Long): Int
    external fun zKeyexprTryFrom(s: String): Long
}
