// Auto-generated by JniExt - do not edit by hand.
package io.zenoh.jni

import java.lang.ref.Cleaner
import java.util.concurrent.locks.ReentrantReadWriteLock
import kotlin.concurrent.read
import kotlin.concurrent.write

/**
 * Minimal race-free wrapper around a raw `Box<T>` pointer obtained from
 * native code via `Box::into_raw(Box::new(v))`. Pairs the pointer with a
 * `ReentrantReadWriteLock` so borrow-style JNI calls run in parallel
 * under the read lock and consume/free serialise under the write lock.
 *
 * The base deliberately knows **nothing** about how to free the pointer:
 * `freePtr` and the `AutoCloseable` / `Cleaner` lifecycle live on the
 * concrete generator-emitted subclasses (e.g. `ZKeyExpr`), each of which
 * statically knows its own destructor. The base is just the pointer +
 * lock + the borrow/consume contract used polymorphically by generated
 * wrappers (params typed as this base class).
 *
 * The mutable pointer lives in a detached [State] holder so a subclass's
 * `Cleaner` action can reference the state **without** referencing the
 * handle instance — a back-reference would pin the handle and the cleaner
 * would never fire.
 *
 * Marked `open` so the generator-emitted typed-handle classes can
 * subclass for type safety while inheriting the lock contract.
 */
public open class JNINativeHandle(initial: Long) {
    /**
     * Detached pointer + lock holder. Kept separate from the enclosing
     * handle so a subclass cleaner can capture only this (plus its own
     * static `freePtr`), never the handle instance.
     */
    internal class State(@Volatile var ptr: Long) {
        val lock = ReentrantReadWriteLock()

        /** Run [freePtr] exactly once under the write lock if still live. */
        fun freeOnce(freePtr: (Long) -> Unit) = lock.write {
            val p = ptr
            if (p != 0L) {
                ptr = 0L
                freePtr(p)
            }
        }
    }

    internal val state = State(initial)

    /**
     * Run [block] with the live pointer under the read lock. Throws
     * [JniBindingError] if the handle has already been released. Multiple
     * concurrent invocations run in parallel; only consume/close are
     * serialised against them.
     */
    @Throws(JniBindingError::class)
    public fun <T> withPtr(block: (Long) -> T): T = state.lock.read {
        val p = state.ptr
        if (p == 0L) throw JniBindingError("Operation on a closed native handle.")
        block(p)
    }

    /**
     * Consume the pointer: take it under the write lock, run [action]
     * with the captured pointer, then null the slot - even if [action]
     * throws. Used by the generator-emitted wrappers whose Rust side
     * runs `*Box::from_raw(...)` - i.e. by-value `T` opaque-handle
     * parameters and `impl Into<T>` arms with `IntoSourceMode::Consume`.
     *
     * The slot stays valid during [action] so the wrapper can pass the
     * typed handle to JNI and have JNI extract the pointer via [peek]
     * - symmetric with [withPtr] for the Borrow path. Unique-ownership
     * is still guaranteed: the write lock excludes every other
     * [withPtr] / [consume], and the `finally` clause unconditionally
     * nulls the slot before the lock is released.
     *
     * After consuming, the subclass cleaner (if any) sees `ptr == 0` and
     * no-ops on GC - no double-free.
     *
     * Throws if the handle has already been closed/consumed.
     */
    @Throws(JniBindingError::class)
    public fun <R> consume(action: (Long) -> R): R = state.lock.write {
        val p = state.ptr
        if (p == 0L) throw JniBindingError("Operation on a closed native handle.")
        try {
            action(p)
        } finally {
            state.ptr = 0L
        }
    }

    /** True iff the handle has been released (closed/consumed/cleaned). */
    public fun isClosed(): Boolean = state.ptr == 0L

    /**
     * Read the current pointer value without holding the lock.
     * Returns `0L` if the handle has been closed/consumed.
     */
    public fun peek(): Long = state.ptr

    public companion object {
        /** One shared cleaner thread for every typed-handle subclass. */
        @JvmStatic
        internal val CLEANER: Cleaner = Cleaner.create()
    }
}
