// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni

import io.zenoh.jni.bytes.ZEncoding
import io.zenoh.jni.bytes.ZZBytes
import io.zenoh.jni.callbacks.Callback
import io.zenoh.jni.callbacks.ZHelloCallback
import io.zenoh.jni.callbacks.ZQueryCallback
import io.zenoh.jni.callbacks.ZReplyCallback
import io.zenoh.jni.callbacks.ZSampleCallback
import io.zenoh.jni.config.WhatAmI
import io.zenoh.jni.config.ZConfig
import io.zenoh.jni.config.ZZenohId
import io.zenoh.jni.keyexpr.SetIntersectionLevel
import io.zenoh.jni.keyexpr.ZKeyExpr
import io.zenoh.jni.liveliness.ZLivelinessToken
import io.zenoh.jni.pubsub.ZPublisher
import io.zenoh.jni.pubsub.ZSubscriber
import io.zenoh.jni.qos.CongestionControl
import io.zenoh.jni.qos.Priority
import io.zenoh.jni.query.ReplyKeyExpr
import io.zenoh.jni.query.ZQuerier
import io.zenoh.jni.query.ZQueryable
import io.zenoh.jni.sample.SampleKind
import io.zenoh.jni.sample.ZSample
import io.zenoh.jni.scouting.ZScout
import io.zenoh.jni.session.ZSession
import io.zenoh.jni.time.ZTimestamp

internal object JNINative {
    external fun initAndroidLogs(filter: String, errorSink: Any)
    external fun initZenohLogsFromEnvOr(fallbackFilter: String, errorSink: Any)
    external fun tryInitZenohLogsFromEnv(errorSink: Any)
    external fun zConfigClone(c: Long, errorSink: Any): Long
    external fun zConfigDefault(errorSink: Any): Long
    external fun zConfigFromFile(path: String, errorSink: Any): Long
    external fun zConfigFromJson(s: String, errorSink: Any): Long
    external fun zConfigFromJson5(s: String, errorSink: Any): Long
    external fun zConfigFromYaml(s: String, errorSink: Any): Long
    external fun zConfigGetJson(c: Long, key: String, errorSink: Any): String
    external fun zConfigInsertJson5(c: Long, key: String, value: String, errorSink: Any)
    external fun zEncodingApplicationCbor(errorSink: Any): Long
    external fun zEncodingApplicationCdr(errorSink: Any): Long
    external fun zEncodingApplicationCoapPayload(errorSink: Any): Long
    external fun zEncodingApplicationJavaSerializedObject(errorSink: Any): Long
    external fun zEncodingApplicationJson(errorSink: Any): Long
    external fun zEncodingApplicationJsonPatchJson(errorSink: Any): Long
    external fun zEncodingApplicationJsonSeq(errorSink: Any): Long
    external fun zEncodingApplicationJsonpath(errorSink: Any): Long
    external fun zEncodingApplicationJwt(errorSink: Any): Long
    external fun zEncodingApplicationMp4(errorSink: Any): Long
    external fun zEncodingApplicationOctetStream(errorSink: Any): Long
    external fun zEncodingApplicationOpenmetricsText(errorSink: Any): Long
    external fun zEncodingApplicationProtobuf(errorSink: Any): Long
    external fun zEncodingApplicationPythonSerializedObject(errorSink: Any): Long
    external fun zEncodingApplicationSoapXml(errorSink: Any): Long
    external fun zEncodingApplicationSql(errorSink: Any): Long
    external fun zEncodingApplicationXWwwFormUrlencoded(errorSink: Any): Long
    external fun zEncodingApplicationXml(errorSink: Any): Long
    external fun zEncodingApplicationYaml(errorSink: Any): Long
    external fun zEncodingApplicationYang(errorSink: Any): Long
    external fun zEncodingAudioAac(errorSink: Any): Long
    external fun zEncodingAudioFlac(errorSink: Any): Long
    external fun zEncodingAudioMp4(errorSink: Any): Long
    external fun zEncodingAudioOgg(errorSink: Any): Long
    external fun zEncodingAudioVorbis(errorSink: Any): Long
    external fun zEncodingClone(e: Long, errorSink: Any): Long
    external fun zEncodingFromString(s: String, errorSink: Any): Long
    external fun zEncodingId(e: Long, errorSink: Any): Int
    external fun zEncodingImageBmp(errorSink: Any): Long
    external fun zEncodingImageGif(errorSink: Any): Long
    external fun zEncodingImageJpeg(errorSink: Any): Long
    external fun zEncodingImagePng(errorSink: Any): Long
    external fun zEncodingImageWebp(errorSink: Any): Long
    external fun zEncodingSchema(e: Long, errorSink: Any): String
    external fun zEncodingTextCss(errorSink: Any): Long
    external fun zEncodingTextCsv(errorSink: Any): Long
    external fun zEncodingTextHtml(errorSink: Any): Long
    external fun zEncodingTextJavascript(errorSink: Any): Long
    external fun zEncodingTextJson(errorSink: Any): Long
    external fun zEncodingTextJson5(errorSink: Any): Long
    external fun zEncodingTextMarkdown(errorSink: Any): Long
    external fun zEncodingTextPlain(errorSink: Any): Long
    external fun zEncodingTextXml(errorSink: Any): Long
    external fun zEncodingTextYaml(errorSink: Any): Long
    external fun zEncodingToString(e: Long, errorSink: Any): String
    external fun zEncodingVideoH261(errorSink: Any): Long
    external fun zEncodingVideoH263(errorSink: Any): Long
    external fun zEncodingVideoH264(errorSink: Any): Long
    external fun zEncodingVideoH265(errorSink: Any): Long
    external fun zEncodingVideoH266(errorSink: Any): Long
    external fun zEncodingVideoMp4(errorSink: Any): Long
    external fun zEncodingVideoOgg(errorSink: Any): Long
    external fun zEncodingVideoRaw(errorSink: Any): Long
    external fun zEncodingVideoVp8(errorSink: Any): Long
    external fun zEncodingVideoVp9(errorSink: Any): Long
    external fun zEncodingWithSchema(e: Long, schema: String, errorSink: Any): Long
    external fun zEncodingZenohBytes(errorSink: Any): Long
    external fun zEncodingZenohSerialized(errorSink: Any): Long
    external fun zEncodingZenohString(errorSink: Any): Long
    external fun zHelloLocators(h: Long, errorSink: Any): List<String>
    external fun zHelloWhatami(h: Long, errorSink: Any): Int
    external fun zHelloZid(h: Long, errorSink: Any): ByteArray
    external fun zKeyexprAutocanonize(s: String, errorSink: Any): Long
    external fun zKeyexprClone(ke: Long, errorSink: Any): Long
    external fun zKeyexprConcat(aSel: Int, a0: String?, a1: Long, b: String, errorSink: Any): Long
    external fun zKeyexprIncludes(aSel: Int, a0: String?, a1: Long, bSel: Int, b0: String?, b1: Long, errorSink: Any): Boolean
    external fun zKeyexprIntersects(aSel: Int, a0: String?, a1: Long, bSel: Int, b0: String?, b1: Long, errorSink: Any): Boolean
    external fun zKeyexprJoin(aSel: Int, a0: String?, a1: Long, b: String, errorSink: Any): Long
    external fun zKeyexprRelationTo(aSel: Int, a0: String?, a1: Long, bSel: Int, b0: String?, b1: Long, errorSink: Any): Int
    external fun zKeyexprToString(ke: Long, errorSink: Any): String
    external fun zKeyexprTryFrom(s: String, errorSink: Any): Long
    external fun zLivelinessDeclareSubscriber(session: Long, keyExprSel: Int, keyExpr0: String?, keyExpr1: Long, history: Boolean, callback: ZSampleCallback, onClose: Callback, errorSink: Any): Long
    external fun zLivelinessDeclareToken(session: Long, keyExprSel: Int, keyExpr0: String?, keyExpr1: Long, errorSink: Any): Long
    external fun zLivelinessGet(session: Long, keyExprSel: Int, keyExpr0: String?, keyExpr1: Long, timeoutMs: Long, callback: ZReplyCallback, onClose: Callback, errorSink: Any)
    external fun zOpen(config: Long, errorSink: Any): Long
    external fun zPublisherDelete(publisher: Long, attachment: ByteArray?, errorSink: Any)
    external fun zPublisherPut(publisher: Long, payload: ByteArray, encoding: String?, attachment: ByteArray?, errorSink: Any)
    external fun zQuerierGet(querier: Long, parameters: String?, payload: ByteArray?, encoding: String?, attachment: ByteArray?, callback: ZReplyCallback, onClose: Callback, errorSink: Any)
    external fun zQueryAcceptsReplies(q: Long, errorSink: Any): Int
    external fun zQueryAttachment(q: Long, errorSink: Any): Long
    external fun zQueryEncoding(q: Long, errorSink: Any): Long
    external fun zQueryKeyexpr(q: Long, errorSink: Any): Long
    external fun zQueryParameters(q: Long, errorSink: Any): String
    external fun zQueryPayload(q: Long, errorSink: Any): Long
    external fun zQueryReplyDelete(query: Long, keyExprSel: Int, keyExpr0: String?, keyExpr1: Long, timestampNtp64: Long?, attachment: ByteArray?, express: Boolean?, errorSink: Any)
    external fun zQueryReplyError(query: Long, payload: ByteArray, encoding: String?, errorSink: Any)
    external fun zQueryReplySuccess(query: Long, keyExprSel: Int, keyExpr0: String?, keyExpr1: Long, payload: ByteArray, encoding: String?, timestampNtp64: Long?, attachment: ByteArray?, express: Boolean?, errorSink: Any)
    external fun zReplyErrorEncoding(r: Long, errorSink: Any): Long
    external fun zReplyErrorPayload(r: Long, errorSink: Any): Long
    external fun zReplyIsOk(r: Long, errorSink: Any): Boolean
    external fun zReplyReplierEid(r: Long, errorSink: Any): Int
    external fun zReplyReplierZid(r: Long, errorSink: Any): ByteArray?
    external fun zReplySample(r: Long, errorSink: Any): Long
    external fun zSampleAttachment(s: Long, errorSink: Any): Long
    external fun zSampleCongestionControl(s: Long, errorSink: Any): Int
    external fun zSampleEncoding(s: Long, errorSink: Any): Long
    external fun zSampleExpress(s: Long, errorSink: Any): Boolean
    external fun zSampleKeyExpr(s: Long, errorSink: Any): Long
    external fun zSampleKind(s: Long, errorSink: Any): Int
    external fun zSamplePayload(s: Long, errorSink: Any): Long
    external fun zSamplePriority(s: Long, errorSink: Any): Int
    external fun zSampleTimestamp(s: Long, errorSink: Any): Long
    external fun zScout(whatami: Int, config: Long, callback: ZHelloCallback, onClose: Callback, errorSink: Any): Long
    external fun zSessionDeclareKeyexpr(session: Long, keyExpr: String, errorSink: Any): Long
    external fun zSessionDeclarePublisher(session: Long, keyExprSel: Int, keyExpr0: String?, keyExpr1: Long, congestionControl: Int?, priority: Int?, express: Boolean?, reliability: Int?, errorSink: Any): Long
    external fun zSessionDeclareQuerier(session: Long, keyExprSel: Int, keyExpr0: String?, keyExpr1: Long, target: Int?, consolidation: Int?, congestionControl: Int?, priority: Int?, express: Boolean?, timeoutMs: Long?, acceptReplies: Int?, errorSink: Any): Long
    external fun zSessionDeclareQueryable(session: Long, keyExprSel: Int, keyExpr0: String?, keyExpr1: Long, complete: Boolean?, callback: ZQueryCallback, onClose: Callback, errorSink: Any): Long
    external fun zSessionDeclareSubscriber(session: Long, keyExprSel: Int, keyExpr0: String?, keyExpr1: Long, callback: ZSampleCallback, onClose: Callback, errorSink: Any): Long
    external fun zSessionDelete(session: Long, keyExprSel: Int, keyExpr0: String?, keyExpr1: Long, congestionControl: Int?, priority: Int?, express: Boolean?, attachment: ByteArray?, reliability: Int?, errorSink: Any)
    external fun zSessionGet(session: Long, keyExprSel: Int, keyExpr0: String?, keyExpr1: Long, parameters: String?, timeoutMs: Long?, target: Int?, consolidation: Int?, acceptReplies: Int?, congestionControl: Int?, priority: Int?, express: Boolean?, payload: ByteArray?, encoding: String?, attachment: ByteArray?, callback: ZReplyCallback, onClose: Callback, errorSink: Any)
    external fun zSessionPeersZid(session: Long, errorSink: Any): List<ByteArray>
    external fun zSessionPut(session: Long, keyExprSel: Int, keyExpr0: String?, keyExpr1: Long, payload: ByteArray, encoding: String?, congestionControl: Int?, priority: Int?, express: Boolean?, attachment: ByteArray?, reliability: Int?, errorSink: Any)
    external fun zSessionRoutersZid(session: Long, errorSink: Any): List<ByteArray>
    external fun zSessionUndeclareKeyexpr(session: Long, keyExpr: Long, errorSink: Any)
    external fun zSessionZid(session: Long, errorSink: Any): ByteArray
    external fun zTimestampId(t: Long, errorSink: Any): ByteArray
    external fun zTimestampNtp64(t: Long, errorSink: Any): Long
    external fun zZbytesClone(z: Long, errorSink: Any): Long
    external fun zZbytesFromVec(bytes: ByteArray, errorSink: Any): Long
    external fun zZbytesToBytes(z: Long, errorSink: Any): ByteArray
    external fun zZenohIdToBytes(z: ByteArray, errorSink: Any): ByteArray
    external fun zZenohIdToString(z: ByteArray, errorSink: Any): String
}
