// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni

import io.zenoh.jni.bytes.Encoding
import io.zenoh.jni.bytes.ZZBytes
import io.zenoh.jni.callbacks.Callback
import io.zenoh.jni.callbacks.HelloCallback
import io.zenoh.jni.callbacks.ZHelloCallback
import io.zenoh.jni.config.WhatAmI
import io.zenoh.jni.config.ZConfig
import io.zenoh.jni.config.ZZenohId
import io.zenoh.jni.keyexpr.KeyExpr
import io.zenoh.jni.keyexpr.SetIntersectionLevel
import io.zenoh.jni.keyexpr.ZKeyExpr
import io.zenoh.jni.scouting.ZScout

internal object JNINative {
    external fun initAndroidLogs(filter: String)
    external fun initZenohLogsFromEnvOr(fallbackFilter: String)
    external fun keyexprAutocanonize(s: String): KeyExpr
    external fun keyexprConcat(a: Any, b: String): KeyExpr
    external fun keyexprIncludes(a: Any, b: Any): Boolean
    external fun keyexprIntersects(a: Any, b: Any): Boolean
    external fun keyexprJoin(a: Any, b: String): KeyExpr
    external fun keyexprRelationTo(a: Any, b: Any): Int
    external fun keyexprTryFrom(s: String): KeyExpr
    external fun scout(whatami: Int, config: Long, callback: HelloCallback, onClose: Callback): Long
    external fun tryInitZenohLogsFromEnv()
    external fun zConfigDefault(): Long
    external fun zConfigFromFile(path: String): Long
    external fun zConfigFromJson(s: String): Long
    external fun zConfigFromJson5(s: String): Long
    external fun zConfigFromYaml(s: String): Long
    external fun zConfigGetJson(c: Long, key: String): String
    external fun zConfigInsertJson5(c: Long, key: String, value: String)
    external fun zEncodingApplicationCbor(): Encoding
    external fun zEncodingApplicationCdr(): Encoding
    external fun zEncodingApplicationCoapPayload(): Encoding
    external fun zEncodingApplicationJavaSerializedObject(): Encoding
    external fun zEncodingApplicationJson(): Encoding
    external fun zEncodingApplicationJsonPatchJson(): Encoding
    external fun zEncodingApplicationJsonSeq(): Encoding
    external fun zEncodingApplicationJsonpath(): Encoding
    external fun zEncodingApplicationJwt(): Encoding
    external fun zEncodingApplicationMp4(): Encoding
    external fun zEncodingApplicationOctetStream(): Encoding
    external fun zEncodingApplicationOpenmetricsText(): Encoding
    external fun zEncodingApplicationProtobuf(): Encoding
    external fun zEncodingApplicationPythonSerializedObject(): Encoding
    external fun zEncodingApplicationSoapXml(): Encoding
    external fun zEncodingApplicationSql(): Encoding
    external fun zEncodingApplicationXWwwFormUrlencoded(): Encoding
    external fun zEncodingApplicationXml(): Encoding
    external fun zEncodingApplicationYaml(): Encoding
    external fun zEncodingApplicationYang(): Encoding
    external fun zEncodingAudioAac(): Encoding
    external fun zEncodingAudioFlac(): Encoding
    external fun zEncodingAudioMp4(): Encoding
    external fun zEncodingAudioOgg(): Encoding
    external fun zEncodingAudioVorbis(): Encoding
    external fun zEncodingId(e: Long): Int
    external fun zEncodingImageBmp(): Encoding
    external fun zEncodingImageGif(): Encoding
    external fun zEncodingImageJpeg(): Encoding
    external fun zEncodingImagePng(): Encoding
    external fun zEncodingImageWebp(): Encoding
    external fun zEncodingSchema(e: Long): String
    external fun zEncodingTextCss(): Encoding
    external fun zEncodingTextCsv(): Encoding
    external fun zEncodingTextHtml(): Encoding
    external fun zEncodingTextJavascript(): Encoding
    external fun zEncodingTextJson(): Encoding
    external fun zEncodingTextJson5(): Encoding
    external fun zEncodingTextMarkdown(): Encoding
    external fun zEncodingTextPlain(): Encoding
    external fun zEncodingTextXml(): Encoding
    external fun zEncodingTextYaml(): Encoding
    external fun zEncodingToString(e: Encoding): String
    external fun zEncodingVideoH261(): Encoding
    external fun zEncodingVideoH263(): Encoding
    external fun zEncodingVideoH264(): Encoding
    external fun zEncodingVideoH265(): Encoding
    external fun zEncodingVideoH266(): Encoding
    external fun zEncodingVideoMp4(): Encoding
    external fun zEncodingVideoOgg(): Encoding
    external fun zEncodingVideoRaw(): Encoding
    external fun zEncodingVideoVp8(): Encoding
    external fun zEncodingVideoVp9(): Encoding
    external fun zEncodingZenohBytes(): Encoding
    external fun zEncodingZenohSerialized(): Encoding
    external fun zEncodingZenohString(): Encoding
    external fun zHelloLocators(h: Long): List<String>
    external fun zHelloWhatami(h: Long): Int
    external fun zHelloZid(h: Long): Long
    external fun zKeyexprAutocanonize(s: String): Long
    external fun zKeyexprConcat(a: Long, b: String): Long
    external fun zKeyexprIncludes(a: Long, b: Long): Boolean
    external fun zKeyexprIntersects(a: Long, b: Long): Boolean
    external fun zKeyexprJoin(a: Long, b: String): Long
    external fun zKeyexprRelationTo(a: Long, b: Long): Int
    external fun zKeyexprTryFrom(s: String): Long
    external fun zPublisherDelete(publisher: Long, attachment: Any?)
    external fun zPublisherPut(publisher: Long, payload: Any, encoding: Any, attachment: Any?)
    external fun zScout(whatami: Int, config: Long, callback: ZHelloCallback, onClose: Callback): Long
    external fun zZbytesFromBytes(bytes: ByteArray): Long
    external fun zZbytesToBytes(z: Long): ByteArray
    external fun zZenohIdToBytes(z: Long): ByteArray
    external fun zZenohIdToString(z: Long): String
}
