// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni

import io.zenoh.jni.Error
import io.zenoh.jni.JniBindingError
import io.zenoh.jni.KeyExpr
import io.zenoh.jni.JNINative

@Throws(Error::class, JniBindingError::class)
public fun keyexprAutocanonize(s: String): KeyExpr =
    JNINative.keyexprAutocanonize(s)

