// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni

import io.zenoh.jni.Error
import io.zenoh.jni.JniBindingError

public object JNIOrphaned {
    @Throws(Error::class, JniBindingError::class)
    public fun keyexprValidate(s: String): String =
        JNINative.keyexprValidate(s)

}
