// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni

public data class KeyExpr(
    val keyExprString: String,
    val keyExprNative: ZKeyExpr?,
) : AutoCloseable {
    override fun close() {
        keyExprNative?.close()
    }

    public companion object {
        @Throws(Error::class, JniBindingError::class)
        public fun keyexprTryFrom(s: String): KeyExpr =
            JNINative.keyexprTryFrom(s)


        @Throws(Error::class, JniBindingError::class)
        public fun keyexprAutocanonize(s: String): KeyExpr =
            JNINative.keyexprAutocanonize(s)


        @Throws(Error::class, JniBindingError::class)
        public fun keyexprIntersects(a: Any, b: Any): Boolean =
            if (a is ZKeyExpr) a.withPtr { _ ->
            if (b is ZKeyExpr) b.withPtr { _ ->
            JNINative.keyexprIntersects(a, b)
        } else {
            JNINative.keyexprIntersects(a, b)
        }
        } else {
            if (b is ZKeyExpr) b.withPtr { _ ->
            JNINative.keyexprIntersects(a, b)
        } else {
            JNINative.keyexprIntersects(a, b)
        }
        }


        @Throws(Error::class, JniBindingError::class)
        public fun keyexprIncludes(a: Any, b: Any): Boolean =
            if (a is ZKeyExpr) a.withPtr { _ ->
            if (b is ZKeyExpr) b.withPtr { _ ->
            JNINative.keyexprIncludes(a, b)
        } else {
            JNINative.keyexprIncludes(a, b)
        }
        } else {
            if (b is ZKeyExpr) b.withPtr { _ ->
            JNINative.keyexprIncludes(a, b)
        } else {
            JNINative.keyexprIncludes(a, b)
        }
        }


        @Throws(Error::class, JniBindingError::class)
        public fun keyexprRelationTo(a: Any, b: Any): Int =
            if (a is ZKeyExpr) a.withPtr { _ ->
            if (b is ZKeyExpr) b.withPtr { _ ->
            JNINative.keyexprRelationTo(a, b)
        } else {
            JNINative.keyexprRelationTo(a, b)
        }
        } else {
            if (b is ZKeyExpr) b.withPtr { _ ->
            JNINative.keyexprRelationTo(a, b)
        } else {
            JNINative.keyexprRelationTo(a, b)
        }
        }


        @Throws(Error::class, JniBindingError::class)
        public fun keyexprJoin(a: Any, b: String): KeyExpr =
            if (a is ZKeyExpr) a.withPtr { _ ->
            JNINative.keyexprJoin(a, b)
        } else {
            JNINative.keyexprJoin(a, b)
        }


        @Throws(Error::class, JniBindingError::class)
        public fun keyexprConcat(a: Any, b: String): KeyExpr =
            if (a is ZKeyExpr) a.withPtr { _ ->
            JNINative.keyexprConcat(a, b)
        } else {
            JNINative.keyexprConcat(a, b)
        }

    }
}
