// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.keyexpr

import io.zenoh.jni.JNINative
import io.zenoh.jni.JniErrorHandler
import io.zenoh.jni.JniErrorHandlerCapture
import io.zenoh.jni.NativeHandle
import io.zenoh.jni.errors.ZErrorHandler
import io.zenoh.jni.errors.ZErrorHandlerCapture
import io.zenoh.jni.withSortedHandleLocks

/** JVM-side surface for the native Rust `SetIntersectionLevel` enum. */
public enum class SetIntersectionLevel(public val value: Int) {
    DISJOINT(0),
    INTERSECTS(1),
    INCLUDES(2),
    EQUALS(3);

    public companion object {
        @JvmStatic
        public fun fromInt(value: Int): SetIntersectionLevel = entries.first { it.value == value }
    }
}

/** Typed handle for a native Zenoh `ZKeyExpr`. */
public class ZKeyExpr(initialPtr: Long) : NativeHandle(initialPtr) {
    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZKeyExpr {
        val p = ptr
        ptr = 0L
        return ZKeyExpr(p)
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}

public fun zKeyexprAsStr(ke: ZKeyExpr, onError: JniErrorHandler<String>): String {
    if (ke.ptr == 0L) return onError.run("Operation on a closed native handle.")
    val __cap = JniErrorHandlerCapture.acquire()
    val __ret = withSortedHandleLocks(ke) {
        val ke_ptr = ke.ptr
        JNINative.zKeyexprAsStr(ke_ptr, __cap)
    }
    if (__cap.failed) return onError.run(__cap.je)
    return __ret
}

public fun zKeyexprTryFrom(s: String, onError: ZErrorHandler<ZKeyExpr>): ZKeyExpr {
    val __cap = ZErrorHandlerCapture.acquire()
    val __ret = ZKeyExpr(JNINative.zKeyexprTryFrom(s, __cap))
    if (__cap.failed) return onError.run(__cap.je, __cap.ze0!!)
    return __ret
}

public fun zKeyexprAutocanonize(s: String, onError: ZErrorHandler<ZKeyExpr>): ZKeyExpr {
    val __cap = ZErrorHandlerCapture.acquire()
    val __ret = ZKeyExpr(JNINative.zKeyexprAutocanonize(s, __cap))
    if (__cap.failed) return onError.run(__cap.je, __cap.ze0!!)
    return __ret
}

public fun zKeyexprIntersects(
    aSel: Int,
    a0: String?,
    a1: ZKeyExpr?,
    bSel: Int,
    b0: String?,
    b1: ZKeyExpr?,
    onError: JniErrorHandler<Boolean>,
): Boolean {
    if (a1 != null && a1.ptr == 0L) return onError.run("Operation on a closed native handle.")
    if (b1 != null && b1.ptr == 0L) return onError.run("Operation on a closed native handle.")
    val __cap = JniErrorHandlerCapture.acquire()
    val __ret = run {
        val __locks = ArrayList<NativeHandle>()
        a1?.let { __locks.add(it) }
        b1?.let { __locks.add(it) }
        withSortedHandleLocks(__locks) {
            val a1_ptr = a1?.ptr ?: 0L
            val b1_ptr = b1?.ptr ?: 0L
            JNINative.zKeyexprIntersects(aSel, a0, a1_ptr, bSel, b0, b1_ptr, __cap)
        }
    }
    if (__cap.failed) return onError.run(__cap.je)
    return __ret
}

public fun zKeyexprIncludes(
    aSel: Int,
    a0: String?,
    a1: ZKeyExpr?,
    bSel: Int,
    b0: String?,
    b1: ZKeyExpr?,
    onError: JniErrorHandler<Boolean>,
): Boolean {
    if (a1 != null && a1.ptr == 0L) return onError.run("Operation on a closed native handle.")
    if (b1 != null && b1.ptr == 0L) return onError.run("Operation on a closed native handle.")
    val __cap = JniErrorHandlerCapture.acquire()
    val __ret = run {
        val __locks = ArrayList<NativeHandle>()
        a1?.let { __locks.add(it) }
        b1?.let { __locks.add(it) }
        withSortedHandleLocks(__locks) {
            val a1_ptr = a1?.ptr ?: 0L
            val b1_ptr = b1?.ptr ?: 0L
            JNINative.zKeyexprIncludes(aSel, a0, a1_ptr, bSel, b0, b1_ptr, __cap)
        }
    }
    if (__cap.failed) return onError.run(__cap.je)
    return __ret
}

public fun zKeyexprRelationTo(
    aSel: Int,
    a0: String?,
    a1: ZKeyExpr?,
    bSel: Int,
    b0: String?,
    b1: ZKeyExpr?,
    onError: JniErrorHandler<SetIntersectionLevel>,
): SetIntersectionLevel {
    if (a1 != null && a1.ptr == 0L) return onError.run("Operation on a closed native handle.")
    if (b1 != null && b1.ptr == 0L) return onError.run("Operation on a closed native handle.")
    val __cap = JniErrorHandlerCapture.acquire()
    val __ret = run {
        val __locks = ArrayList<NativeHandle>()
        a1?.let { __locks.add(it) }
        b1?.let { __locks.add(it) }
        withSortedHandleLocks(__locks) {
            val a1_ptr = a1?.ptr ?: 0L
            val b1_ptr = b1?.ptr ?: 0L
            SetIntersectionLevel.fromInt(
                JNINative.zKeyexprRelationTo(aSel, a0, a1_ptr, bSel, b0, b1_ptr, __cap),
            )
        }
    }
    if (__cap.failed) return onError.run(__cap.je)
    return __ret
}

public fun zKeyexprJoin(
    aSel: Int,
    a0: String?,
    a1: ZKeyExpr?,
    b: String,
    onError: ZErrorHandler<ZKeyExpr>,
): ZKeyExpr {
    if (a1 != null && a1.ptr == 0L) return onError.run("Operation on a closed native handle.", "")
    val __cap = ZErrorHandlerCapture.acquire()
    val __ret = run {
        val __locks = ArrayList<NativeHandle>()
        a1?.let { __locks.add(it) }
        withSortedHandleLocks(__locks) {
            val a1_ptr = a1?.ptr ?: 0L
            ZKeyExpr(JNINative.zKeyexprJoin(aSel, a0, a1_ptr, b, __cap))
        }
    }
    if (__cap.failed) return onError.run(__cap.je, __cap.ze0!!)
    return __ret
}

public fun zKeyexprConcat(
    aSel: Int,
    a0: String?,
    a1: ZKeyExpr?,
    b: String,
    onError: ZErrorHandler<ZKeyExpr>,
): ZKeyExpr {
    if (a1 != null && a1.ptr == 0L) return onError.run("Operation on a closed native handle.", "")
    val __cap = ZErrorHandlerCapture.acquire()
    val __ret = run {
        val __locks = ArrayList<NativeHandle>()
        a1?.let { __locks.add(it) }
        withSortedHandleLocks(__locks) {
            val a1_ptr = a1?.ptr ?: 0L
            ZKeyExpr(JNINative.zKeyexprConcat(aSel, a0, a1_ptr, b, __cap))
        }
    }
    if (__cap.failed) return onError.run(__cap.je, __cap.ze0!!)
    return __ret
}

public fun zKeyexprClone(ke: ZKeyExpr, onError: JniErrorHandler<ZKeyExpr>): ZKeyExpr {
    if (ke.ptr == 0L) return onError.run("Operation on a closed native handle.")
    val __cap = JniErrorHandlerCapture.acquire()
    val __ret = withSortedHandleLocks(ke) {
        val ke_ptr = ke.ptr
        ZKeyExpr(JNINative.zKeyexprClone(ke_ptr, __cap))
    }
    if (__cap.failed) return onError.run(__cap.je)
    return __ret
}

public fun zKeyexprToString(ke: ZKeyExpr, onError: JniErrorHandler<String>): String {
    if (ke.ptr == 0L) return onError.run("Operation on a closed native handle.")
    val __cap = JniErrorHandlerCapture.acquire()
    val __ret = withSortedHandleLocks(ke) {
        val ke_ptr = ke.ptr
        JNINative.zKeyexprToString(ke_ptr, __cap)
    }
    if (__cap.failed) return onError.run(__cap.je)
    return __ret
}
