// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.logger

import io.zenoh.jni.JNINative
import io.zenoh.jni.JniErrorHandler
import io.zenoh.jni.JniErrorHandlerCapture

public fun initAndroidLogs(filter: String, onError: JniErrorHandler<Unit>) {
    val __cap = JniErrorHandlerCapture.acquire()
    JNINative.initAndroidLogs(filter, __cap)
    if (__cap.failed) return onError.run(__cap.je)
}

public fun tryInitZenohLogsFromEnv(onError: JniErrorHandler<Unit>) {
    val __cap = JniErrorHandlerCapture.acquire()
    JNINative.tryInitZenohLogsFromEnv(__cap)
    if (__cap.failed) return onError.run(__cap.je)
}

public fun initZenohLogsFromEnvOr(fallbackFilter: String, onError: JniErrorHandler<Unit>) {
    val __cap = JniErrorHandlerCapture.acquire()
    JNINative.initZenohLogsFromEnvOr(fallbackFilter, __cap)
    if (__cap.failed) return onError.run(__cap.je)
}
