// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.logger

import io.zenoh.jni.JNINative
import io.zenoh.jni.ZException

public fun initAndroidLogs(
    filter: String,
    onError: (je: String?) -> Unit = { __de_je -> throw ZException(__de_je) },
) {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    JNINative.initAndroidLogs(filter, __cap)
    if (__cap_failed) return onError(__cap_je)
}

public fun tryInitZenohLogsFromEnv(
    onError: (je: String?) -> Unit = { __de_je -> throw ZException(__de_je) },
) {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    JNINative.tryInitZenohLogsFromEnv(__cap)
    if (__cap_failed) return onError(__cap_je)
}

public fun initZenohLogsFromEnvOr(
    fallbackFilter: String,
    onError: (je: String?) -> Unit = { __de_je -> throw ZException(__de_je) },
) {
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    JNINative.initZenohLogsFromEnvOr(fallbackFilter, __cap)
    if (__cap_failed) return onError(__cap_je)
}
