// Auto-generated by JniExt - do not edit by hand.
package io.zenoh.jni

import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.InputStream
import java.util.zip.ZipInputStream

internal object NativeLibLoader {
    private const val LIB_NAME = "zenoh-flat-jni"

    init {
        if (tryLoadingLocalLibrary().isFailure) {
            val target = determineTarget().getOrThrow()
            tryLoadingLibraryFromJarPackage(target).getOrThrow()
        }
    }

    private fun determineTarget(): Result<Target> = runCatching {
        val osName = System.getProperty("os.name").lowercase()
        val osArch = System.getProperty("os.arch").lowercase()
        val target = when {
            osName.contains("win") -> when {
                osArch.contains("x86_64") || osArch.contains("amd64") || osArch.contains("x64") ->
                    Target.WINDOWS_X86_64_MSVC
                osArch.contains("aarch64") || osArch.contains("arm64") ->
                    Target.WINDOWS_AARCH64_MSVC
                else -> throw UnsupportedOperationException("Unsupported architecture on Windows: $osArch")
            }
            osName.contains("mac") || osName.contains("darwin") || osName.contains("os x") -> when {
                osArch.contains("x86_64") || osArch.contains("amd64") || osArch.contains("x64") ->
                    Target.APPLE_X86_64
                osArch.contains("aarch64") || osArch.contains("arm64") ->
                    Target.APPLE_AARCH64
                else -> throw UnsupportedOperationException("Unsupported architecture on macOS: $osArch")
            }
            osName.contains("nix") || osName.contains("nux") || osName.contains("aix") -> when {
                osArch.contains("x86_64") || osArch.contains("amd64") || osArch.contains("x64") ->
                    Target.LINUX_X86_64
                osArch.contains("aarch64") || osArch.contains("arm64") ->
                    Target.LINUX_AARCH64
                else -> throw UnsupportedOperationException("Unsupported architecture on Linux/Unix: $osArch")
            }
            else -> throw UnsupportedOperationException("Unsupported platform: $osName")
        }
        target
    }

    private fun unzipLibrary(compressedLib: InputStream): Result<File> = runCatching {
        val zipInputStream = ZipInputStream(compressedLib)
        val buffer = ByteArray(1024)
        val zipEntry = zipInputStream.nextEntry!!
        val library = File.createTempFile(zipEntry.name, ".tmp")
        library.deleteOnExit()
        val parent = library.parentFile
        if (!parent.exists()) parent.mkdirs()
        val fileOutputStream = FileOutputStream(library)
        var len: Int
        while (zipInputStream.read(buffer).also { len = it } > 0) {
            fileOutputStream.write(buffer, 0, len)
        }
        fileOutputStream.close()
        zipInputStream.closeEntry()
        zipInputStream.close()
        library
    }

    private fun loadLibraryAsInputStream(target: Target): Result<InputStream> = runCatching {
        val targetName = "$target/$target.zip"
        val libUrl = ClassLoader.getSystemClassLoader().getResourceAsStream(targetName)
            ?: javaClass.classLoader.getResourceAsStream(targetName)!!
        val uncompressedLibFile = unzipLibrary(libUrl)
        FileInputStream(uncompressedLibFile.getOrThrow())
    }

    @Suppress("UnsafeDynamicallyLoadedCode")
    private fun loadNativeLib(inputStream: InputStream) {
        val tempLib = File.createTempFile("tempLib", ".tmp")
        tempLib.deleteOnExit()
        FileOutputStream(tempLib).use { output -> inputStream.copyTo(output) }
        System.load(tempLib.absolutePath)
    }

    private fun tryLoadingLibraryFromJarPackage(target: Target): Result<Unit> = runCatching {
        val lib: Result<InputStream> = loadLibraryAsInputStream(target)
        lib.onSuccess { loadNativeLib(it) }.onFailure { throw Exception("Unable to load native lib: $it") }
    }

    private fun tryLoadingLocalLibrary(): Result<Unit> = runCatching {
        val lib = ClassLoader.getSystemClassLoader().findLibraryStream(LIB_NAME)
            ?: javaClass.classLoader.findLibraryStream(LIB_NAME)
        if (lib != null) {
            loadNativeLib(lib)
        } else {
            throw Exception("Unable to load local native lib.")
        }
    }
}

private fun ClassLoader.findLibraryStream(libraryName: String): InputStream? {
    val libraryExtensions = listOf(".dylib", ".so", ".dll")
    for (extension in libraryExtensions) {
        val resourcePath = "lib$libraryName$extension"
        val inputStream = getResourceAsStream(resourcePath)
        if (inputStream != null) return inputStream
    }
    return null
}
