// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.pubsub

import io.zenoh.jni.JNINative
import io.zenoh.jni.NativeHandle
import io.zenoh.jni.errors.ZErrorHandler
import io.zenoh.jni.errors.ZErrorHandlerCapture
import io.zenoh.jni.withSortedHandleLocks

/** Typed handle for a native Zenoh `ZPublisher`. */
public class ZPublisher(initialPtr: Long) : NativeHandle(initialPtr) {
    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZPublisher {
        val p = ptr
        ptr = 0L
        return ZPublisher(p)
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}

/** Typed handle for a native Zenoh `ZSubscriber`. */
public class ZSubscriber(initialPtr: Long) : NativeHandle(initialPtr) {
    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZSubscriber {
        val p = ptr
        ptr = 0L
        return ZSubscriber(p)
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}

public fun zPublisherPut(
    publisher: ZPublisher,
    payload: ByteArray,
    encodingPresent: Boolean,
    encodingId: Int,
    encodingSchema: String?,
    attachment: ByteArray?,
    onError: ZErrorHandler<Unit>,
) {
    if (publisher.ptr == 0L) { onError.run("Operation on a closed native handle.", ""); return }
    val __cap = ZErrorHandlerCapture.acquire()
    withSortedHandleLocks(publisher) {
        val publisher_ptr = publisher.ptr
        JNINative.zPublisherPut(
            publisher_ptr,
            payload,
            encodingPresent,
            encodingId,
            encodingSchema,
            attachment,
            __cap,
        )
    }
    if (__cap.failed) return onError.run(__cap.je, __cap.ze0!!)
}

public fun zPublisherDelete(
    publisher: ZPublisher,
    attachment: ByteArray?,
    onError: ZErrorHandler<Unit>,
) {
    if (publisher.ptr == 0L) { onError.run("Operation on a closed native handle.", ""); return }
    val __cap = ZErrorHandlerCapture.acquire()
    withSortedHandleLocks(publisher) {
        val publisher_ptr = publisher.ptr
        JNINative.zPublisherDelete(publisher_ptr, attachment, __cap)
    }
    if (__cap.failed) return onError.run(__cap.je, __cap.ze0!!)
}
