// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.pubsub

import io.zenoh.jni.JNINative
import io.zenoh.jni.NativeHandle
import io.zenoh.jni.ZException
import io.zenoh.jni.withSortedHandleLocks

/** Typed handle for a native Zenoh `ZPublisher`. */
public class ZPublisher(initialPtr: Long) : NativeHandle(initialPtr) {
    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZPublisher {
        val p = ptr
        ptr = 0L
        return ZPublisher(p)
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}

/** Typed handle for a native Zenoh `ZSubscriber`. */
public class ZSubscriber(initialPtr: Long) : NativeHandle(initialPtr) {
    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZSubscriber {
        val p = ptr
        ptr = 0L
        return ZSubscriber(p)
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}

public fun zPublisherPut(
    publisher: ZPublisher,
    payload: ByteArray,
    encoding: String?,
    attachment: ByteArray?,
    onError: (je: String?, message: String) -> Unit = { __de_je, __de_z0 -> throw ZException(__de_je ?: __de_z0) },
) {
    if (publisher.ptr == 0L) { onError("Operation on a closed native handle.", ""); return }
    var __cap_failed = false
    var __cap_je: String? = null
    var __cap_ze0: String? = null
    val __cap = { __je: String?, __ze0: String? -> __cap_failed = true; __cap_je = __je; __cap_ze0 = __ze0 }
    withSortedHandleLocks(publisher) {
        val publisher_ptr = publisher.ptr
        JNINative.zPublisherPut(publisher_ptr, payload, encoding, attachment, __cap)
    }
    if (__cap_failed) return onError(__cap_je, (__cap_ze0 ?: ""))
}

public fun zPublisherDelete(
    publisher: ZPublisher,
    attachment: ByteArray?,
    onError: (je: String?, message: String) -> Unit = { __de_je, __de_z0 -> throw ZException(__de_je ?: __de_z0) },
) {
    if (publisher.ptr == 0L) { onError("Operation on a closed native handle.", ""); return }
    var __cap_failed = false
    var __cap_je: String? = null
    var __cap_ze0: String? = null
    val __cap = { __je: String?, __ze0: String? -> __cap_failed = true; __cap_je = __je; __cap_ze0 = __ze0 }
    withSortedHandleLocks(publisher) {
        val publisher_ptr = publisher.ptr
        JNINative.zPublisherDelete(publisher_ptr, attachment, __cap)
    }
    if (__cap_failed) return onError(__cap_je, (__cap_ze0 ?: ""))
}
