// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.sample

import io.zenoh.jni.qos.CongestionControl
import io.zenoh.jni.JNINative
import io.zenoh.jni.NativeHandle
import io.zenoh.jni.qos.Priority
import io.zenoh.jni.bytes.ZEncoding
import io.zenoh.jni.ZException
import io.zenoh.jni.keyexpr.ZKeyExpr
import io.zenoh.jni.time.ZTimestamp
import io.zenoh.jni.bytes.ZZBytes
import io.zenoh.jni.withSortedHandleLocks

/** JVM-side surface for the native Rust `SampleKind` enum. */
public enum class SampleKind(public val value: Int) {
    PUT(0),
    DELETE(1);

    public companion object {
        @JvmStatic
        public fun fromInt(value: Int): SampleKind = entries.first { it.value == value }
    }
}

/** Typed handle for a native Zenoh `ZSample`. */
public class ZSample(initialPtr: Long) : NativeHandle(initialPtr) {
    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZSample {
        val p = ptr
        ptr = 0L
        return ZSample(p)
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}

public fun zSampleKeyExpr(
    s: ZSample,
    onError: (je: String?) -> ZKeyExpr = { __de_je -> throw ZException(__de_je) },
): ZKeyExpr {
    if (s.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(s) {
        val s_ptr = s.ptr
        ZKeyExpr(JNINative.zSampleKeyExpr(s_ptr, __cap))
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zSamplePayload(
    s: ZSample,
    onError: (je: String?) -> ZZBytes = { __de_je -> throw ZException(__de_je) },
): ZZBytes {
    if (s.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(s) {
        val s_ptr = s.ptr
        ZZBytes(JNINative.zSamplePayload(s_ptr, __cap))
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zSampleEncoding(
    s: ZSample,
    onError: (je: String?) -> ZEncoding = { __de_je -> throw ZException(__de_je) },
): ZEncoding {
    if (s.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(s) {
        val s_ptr = s.ptr
        ZEncoding(JNINative.zSampleEncoding(s_ptr, __cap))
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zSampleKind(
    s: ZSample,
    onError: (je: String?) -> SampleKind = { __de_je -> throw ZException(__de_je) },
): SampleKind {
    if (s.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(s) {
        val s_ptr = s.ptr
        SampleKind.fromInt(JNINative.zSampleKind(s_ptr, __cap))
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zSampleTimestamp(
    s: ZSample,
    onError: (je: String?) -> ZTimestamp? = { __de_je -> throw ZException(__de_je) },
): ZTimestamp? {
    if (s.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(s) {
        val s_ptr = s.ptr
        JNINative.zSampleTimestamp(s_ptr, __cap).let { if (it == 0L) null else ZTimestamp(it) }
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zSampleExpress(
    s: ZSample,
    onError: (je: String?) -> Boolean = { __de_je -> throw ZException(__de_je) },
): Boolean {
    if (s.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(s) {
        val s_ptr = s.ptr
        JNINative.zSampleExpress(s_ptr, __cap)
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zSamplePriority(
    s: ZSample,
    onError: (je: String?) -> Priority = { __de_je -> throw ZException(__de_je) },
): Priority {
    if (s.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(s) {
        val s_ptr = s.ptr
        Priority.fromInt(JNINative.zSamplePriority(s_ptr, __cap))
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zSampleCongestionControl(
    s: ZSample,
    onError: (je: String?) -> CongestionControl = { __de_je -> throw ZException(__de_je) },
): CongestionControl {
    if (s.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(s) {
        val s_ptr = s.ptr
        CongestionControl.fromInt(JNINative.zSampleCongestionControl(s_ptr, __cap))
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zSampleAttachment(
    s: ZSample,
    onError: (je: String?) -> ZZBytes? = { __de_je -> throw ZException(__de_je) },
): ZZBytes? {
    if (s.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(s) {
        val s_ptr = s.ptr
        JNINative.zSampleAttachment(s_ptr, __cap).let { if (it == 0L) null else ZZBytes(it) }
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}
