// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.time

import io.zenoh.jni.JNINative
import io.zenoh.jni.NativeHandle
import io.zenoh.jni.ZException
import io.zenoh.jni.withSortedHandleLocks

/** Typed handle for a native Zenoh `ZTimestamp`. */
public class ZTimestamp(initialPtr: Long) : NativeHandle(initialPtr) {
    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZTimestamp {
        val p = ptr
        ptr = 0L
        return ZTimestamp(p)
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}

public fun zTimestampNtp64(t: ZTimestamp, onError: (String?) -> Long = { __de_je -> throw ZException(__de_je) }): Long {
    if (t.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(t) {
    val t_ptr = t.ptr
    JNINative.zTimestampNtp64(t_ptr, __cap)
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zTimestampId(t: ZTimestamp, onError: (String?) -> ByteArray = { __de_je -> throw ZException(__de_je) }): ByteArray {
    if (t.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(t) {
    val t_ptr = t.ptr
    JNINative.zTimestampId(t_ptr, __cap)
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}
