// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni

/** Typed [JNINativeHandle] for a native Zenoh `ZKeyExpr`. */
public class ZKeyExpr(initialPtr: Long) : JNINativeHandle(initialPtr) {
    public fun free() = free { freePtr(it) }
    private external fun freePtr(ptr: Long)
}
