// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni


/** Typed [JNINativeHandle] for a native Zenoh `ZKeyExpr`. */
public class ZKeyExpr(initialPtr: Long) : JNINativeHandle(initialPtr) {
    public fun free() = free { freePtr(it) }
    private external fun freePtr(ptr: Long)

    @Throws(JniBindingError::class)
    public fun zKeyexprIntersects(b: NativeHandle): Boolean =
        withPtr { a_ptr ->
        b.withPtr { b_ptr ->
        JNINative.zKeyexprIntersects(a_ptr, b_ptr)
    }
    }

    public companion object {
        @Throws(Error::class, JniBindingError::class)
        public fun zKeyexprTryFrom(s: String): NativeHandle =
            ZKeyExpr(JNINative.zKeyexprTryFrom(s))

        @Throws(Error::class, JniBindingError::class)
        public fun zKeyexprAutocanonize(s: String): NativeHandle =
            ZKeyExpr(JNINative.zKeyexprAutocanonize(s))
    }
}
