// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni


/** Typed [JNINativeHandle] for a native Zenoh `ZKeyExpr`. */
public class ZKeyExpr(initialPtr: Long) : JNINativeHandle(initialPtr) {
    public fun free() = free { freePtr(it) }
    private external fun freePtr(ptr: Long)

    @Throws(JniBindingError::class)
    public fun zKeyexprIntersects(b: JNINativeHandle): Boolean =
        withPtr { a_ptr ->
        b.withPtr { b_ptr ->
        JNINative.zKeyexprIntersects(a_ptr, b_ptr)
    }
    }

    @Throws(JniBindingError::class)
    public fun zKeyexprIncludes(b: JNINativeHandle): Boolean =
        withPtr { a_ptr ->
        b.withPtr { b_ptr ->
        JNINative.zKeyexprIncludes(a_ptr, b_ptr)
    }
    }

    @Throws(JniBindingError::class)
    public fun zKeyexprRelationTo(b: JNINativeHandle): Int =
        withPtr { a_ptr ->
        b.withPtr { b_ptr ->
        JNINative.zKeyexprRelationTo(a_ptr, b_ptr)
    }
    }

    @Throws(Error::class, JniBindingError::class)
    public fun zKeyexprJoin(b: String): JNINativeHandle =
        withPtr { a_ptr ->
        ZKeyExpr(JNINative.zKeyexprJoin(a_ptr, b))
    }

    @Throws(Error::class, JniBindingError::class)
    public fun zKeyexprConcat(b: String): JNINativeHandle =
        withPtr { a_ptr ->
        ZKeyExpr(JNINative.zKeyexprConcat(a_ptr, b))
    }

    public companion object {
        @Throws(Error::class, JniBindingError::class)
        public fun zKeyexprTryFrom(s: String): JNINativeHandle =
            ZKeyExpr(JNINative.zKeyexprTryFrom(s))

        @Throws(Error::class, JniBindingError::class)
        public fun zKeyexprAutocanonize(s: String): JNINativeHandle =
            ZKeyExpr(JNINative.zKeyexprAutocanonize(s))
    }
}
