// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni

import io.zenoh.jni.callbacks.Callback
import io.zenoh.jni.callbacks.HelloCallback
import io.zenoh.jni.callbacks.ZHelloCallback

/** Typed [JNINativeHandle] for a native Zenoh `ZScout`. */
public class ZScout(initialPtr: Long) : JNINativeHandle(initialPtr), AutoCloseable {
    private val cleanable: java.lang.ref.Cleaner.Cleanable =
        CLEANER.register(this, Cleanup(state))

    override fun close() = cleanable.clean()

    private class Cleanup(private val state: State) : Runnable {
        override fun run() = state.freeOnce { ZScout.freePtr(it) }
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)

        @Throws(Error::class, JniBindingError::class)
        public fun zScout(whatami: Int, config: ZConfig?, callback: ZHelloCallback, onClose: Callback): ZScout =
            config.withPtrOrZero { config_ptr ->
            ZScout(JNINative.zScout(whatami, config_ptr, callback, onClose))
        }

        @Throws(Error::class, JniBindingError::class)
        public fun scout(whatami: Int, config: ZConfig?, callback: HelloCallback, onClose: Callback): ZScout =
            config.withPtrOrZero { config_ptr ->
            ZScout(JNINative.scout(whatami, config_ptr, callback, onClose))
        }
    }
}
