// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni

/** Typed [JNINativeHandle] for a native Zenoh `ZZenohId`. */
public class ZZenohId(initialPtr: Long) : JNINativeHandle(initialPtr), AutoCloseable {
    private val cleanable: java.lang.ref.Cleaner.Cleanable =
        JNINativeHandle.CLEANER.register(this, Cleanup(state))

    override fun close() = cleanable.clean()

    private class Cleanup(private val state: JNINativeHandle.State) : Runnable {
        override fun run() = state.freeOnce { ZZenohId.freePtr(it) }
    }

    @Throws(JniBindingError::class)
    public fun zZenohIdToBytes(): ByteArray =
        withPtr { z_ptr ->
        JNINative.zZenohIdToBytes(z_ptr)
    }

    @Throws(JniBindingError::class)
    public fun zZenohIdToString(): String =
        withPtr { z_ptr ->
        JNINative.zZenohIdToString(z_ptr)
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}
