// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.pubsub

import io.zenoh.jni.ErrorHolder
import io.zenoh.jni.ErrorSink
import io.zenoh.jni.ZException
import io.zenoh.jni.pubsub.ZPublisher
import io.zenoh.jni.withSortedHandleLocks
import io.zenoh.jni.JNINative

public fun zPublisherPut(publisher: ZPublisher, payload: ByteArray, encoding: String?, attachment: ByteArray?) {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    withSortedHandleLocks(publisher) {
    val publisher_ptr = publisher.ptr
    if (publisher_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zPublisherPut(publisher_ptr, payload, encoding, attachment, __sink)
    }
    __err.message?.let { throw ZException(it) }
}

public fun zPublisherDelete(publisher: ZPublisher, attachment: ByteArray?) {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    withSortedHandleLocks(publisher) {
    val publisher_ptr = publisher.ptr
    if (publisher_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zPublisherDelete(publisher_ptr, attachment, __sink)
    }
    __err.message?.let { throw ZException(it) }
}

