// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.pubsub

import io.zenoh.jni.Error
import io.zenoh.jni.JNINative
import io.zenoh.jni.JniBindingError
import io.zenoh.jni.bytes.ZZBytes

/** Typed handle for a native Zenoh `ZPublisher`. */
public class ZPublisher(initialPtr: Long) : AutoCloseable {
    @Volatile internal var ptr: Long = initialPtr

    public fun peek(): Long = ptr
    public fun isClosed(): Boolean = ptr == 0L

    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZPublisher {
        val p = ptr
        ptr = 0L
        return ZPublisher(p)
    }

    @Throws(Error::class, JniBindingError::class)
    public fun zPublisherDelete(attachment: ZZBytes) {
        val publisher_lo = this.ptr
        val attachment_lo = attachment.ptr
        if (publisher_lo == 0L || attachment_lo == 0L) throw JniBindingError("Operation on a closed native handle.")
        val (lock1, lock2) = if (publisher_lo <= attachment_lo) this to attachment else attachment to this
        synchronized(lock1) {
            synchronized(lock2) {
                val publisher_ptr = this.ptr
                val attachment_ptr = attachment.ptr
                if (publisher_ptr == 0L || attachment_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
                try {
                JNINative.zPublisherDelete(publisher_ptr, attachment_ptr)
            } finally {
                attachment.ptr = 0L
            }
            }
        }
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}
