// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni.pubsub

import io.zenoh.jni.Error
import io.zenoh.jni.JNINative
import io.zenoh.jni.JniBindingError
import io.zenoh.jni.bytes.ZZBytes

/** Typed handle for a native Zenoh `ZPublisher`. */
public class ZPublisher(initialPtr: Long) : AutoCloseable {
    @Volatile internal var ptr: Long = initialPtr

    public fun peek(): Long = ptr
    public fun isClosed(): Boolean = ptr == 0L

    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZPublisher {
        val p = ptr
        ptr = 0L
        return ZPublisher(p)
    }

    @Throws(Error::class, JniBindingError::class)
    public fun zPublisherPut(payload: Any, encodingId: Int, encodingSchema: String?, attachment: Any?) {
        synchronized(this) {
            val publisher_ptr = this.ptr
            if (publisher_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
            if (payload is ZZBytes) synchronized(payload) {
            if (attachment is ZZBytes) synchronized(attachment) {
            JNINative.zPublisherPut(publisher_ptr, payload, encodingId, encodingSchema, attachment)
        } else {
            JNINative.zPublisherPut(publisher_ptr, payload, encodingId, encodingSchema, attachment)
        }
        } else {
            if (attachment is ZZBytes) synchronized(attachment) {
            JNINative.zPublisherPut(publisher_ptr, payload, encodingId, encodingSchema, attachment)
        } else {
            JNINative.zPublisherPut(publisher_ptr, payload, encodingId, encodingSchema, attachment)
        }
        }
        }
    }

    @Throws(Error::class, JniBindingError::class)
    public fun zPublisherDelete(attachment: Any?) {
        synchronized(this) {
            val publisher_ptr = this.ptr
            if (publisher_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
            if (attachment is ZZBytes) synchronized(attachment) {
            JNINative.zPublisherDelete(publisher_ptr, attachment)
        } else {
            JNINative.zPublisherDelete(publisher_ptr, attachment)
        }
        }
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}
