// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.query

import io.zenoh.jni.ErrorHolder
import io.zenoh.jni.ErrorSink
import io.zenoh.jni.NativeHandle
import io.zenoh.jni.ZException
import io.zenoh.jni.bytes.ZEncoding
import io.zenoh.jni.bytes.ZZBytes
import io.zenoh.jni.callbacks.Callback
import io.zenoh.jni.callbacks.ZReplyCallback
import io.zenoh.jni.config.ZZenohId
import io.zenoh.jni.keyexpr.ZKeyExpr
import io.zenoh.jni.query.ReplyKeyExpr
import io.zenoh.jni.query.ZQuerier
import io.zenoh.jni.query.ZQuery
import io.zenoh.jni.query.ZReply
import io.zenoh.jni.sample.ZSample
import io.zenoh.jni.withSortedHandleLocks
import io.zenoh.jni.JNINative

public fun zQuerierGet(querier: ZQuerier, parameters: String?, payload: ByteArray?, encoding: String?, attachment: ByteArray?, callback: ZReplyCallback, onClose: Callback) {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    withSortedHandleLocks(querier) {
    val querier_ptr = querier.ptr
    if (querier_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zQuerierGet(querier_ptr, parameters, payload, encoding, attachment, callback, onClose, __sink)
    }
    __err.message?.let { throw ZException(it) }
}

public fun zQueryReplySuccess(query: ZQuery, keyExprSel: Int, keyExpr0: String?, keyExpr1: ZKeyExpr?, payload: ByteArray, encoding: String?, timestampNtp64: Long?, attachment: ByteArray?, express: Boolean?) {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    run {
    val __locks = ArrayList<NativeHandle>()
    __locks.add(query)
    keyExpr1?.let { __locks.add(it) }
    withSortedHandleLocks(__locks) {
    val query_ptr = query.ptr
    if (query_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val keyExpr1_ptr = keyExpr1?.ptr ?: 0L
    if (keyExpr1 != null && keyExpr1_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zQueryReplySuccess(query_ptr, keyExprSel, keyExpr0, keyExpr1_ptr, payload, encoding, timestampNtp64, attachment, express, __sink)
    }
    }
    __err.message?.let { throw ZException(it) }
}

public fun zQueryReplyError(query: ZQuery, payload: ByteArray, encoding: String?) {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    withSortedHandleLocks(query) {
    val query_ptr = query.ptr
    if (query_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zQueryReplyError(query_ptr, payload, encoding, __sink)
    }
    __err.message?.let { throw ZException(it) }
}

public fun zQueryReplyDelete(query: ZQuery, keyExprSel: Int, keyExpr0: String?, keyExpr1: ZKeyExpr?, timestampNtp64: Long?, attachment: ByteArray?, express: Boolean?) {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    run {
    val __locks = ArrayList<NativeHandle>()
    __locks.add(query)
    keyExpr1?.let { __locks.add(it) }
    withSortedHandleLocks(__locks) {
    val query_ptr = query.ptr
    if (query_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val keyExpr1_ptr = keyExpr1?.ptr ?: 0L
    if (keyExpr1 != null && keyExpr1_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zQueryReplyDelete(query_ptr, keyExprSel, keyExpr0, keyExpr1_ptr, timestampNtp64, attachment, express, __sink)
    }
    }
    __err.message?.let { throw ZException(it) }
}

public fun zQueryKeyexpr(q: ZQuery): ZKeyExpr {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(q) {
    val q_ptr = q.ptr
    if (q_ptr == 0L) throw ZException("Operation on a closed native handle.")
    ZKeyExpr(JNINative.zQueryKeyexpr(q_ptr, __sink))
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zQueryParameters(q: ZQuery): String {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(q) {
    val q_ptr = q.ptr
    if (q_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zQueryParameters(q_ptr, __sink)
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zQueryPayload(q: ZQuery): ZZBytes? {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(q) {
    val q_ptr = q.ptr
    if (q_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zQueryPayload(q_ptr, __sink).let { if (it == 0L) null else ZZBytes(it) }
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zQueryEncoding(q: ZQuery): ZEncoding? {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(q) {
    val q_ptr = q.ptr
    if (q_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zQueryEncoding(q_ptr, __sink).let { if (it == 0L) null else ZEncoding(it) }
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zQueryAttachment(q: ZQuery): ZZBytes? {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(q) {
    val q_ptr = q.ptr
    if (q_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zQueryAttachment(q_ptr, __sink).let { if (it == 0L) null else ZZBytes(it) }
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zQueryAcceptsReplies(q: ZQuery): ReplyKeyExpr {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(q) {
    val q_ptr = q.ptr
    if (q_ptr == 0L) throw ZException("Operation on a closed native handle.")
    ReplyKeyExpr.fromInt(JNINative.zQueryAcceptsReplies(q_ptr, __sink))
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zReplyReplierZid(r: ZReply): ZZenohId? {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(r) {
    val r_ptr = r.ptr
    if (r_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zReplyReplierZid(r_ptr, __sink)?.let { ZZenohId(it) }
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zReplyReplierEid(r: ZReply): Int {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(r) {
    val r_ptr = r.ptr
    if (r_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zReplyReplierEid(r_ptr, __sink)
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zReplyIsOk(r: ZReply): Boolean {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(r) {
    val r_ptr = r.ptr
    if (r_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zReplyIsOk(r_ptr, __sink)
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zReplySample(r: ZReply): ZSample? {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(r) {
    val r_ptr = r.ptr
    if (r_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zReplySample(r_ptr, __sink).let { if (it == 0L) null else ZSample(it) }
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zReplyErrorPayload(r: ZReply): ZZBytes? {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(r) {
    val r_ptr = r.ptr
    if (r_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zReplyErrorPayload(r_ptr, __sink).let { if (it == 0L) null else ZZBytes(it) }
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zReplyErrorEncoding(r: ZReply): ZEncoding? {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(r) {
    val r_ptr = r.ptr
    if (r_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zReplyErrorEncoding(r_ptr, __sink).let { if (it == 0L) null else ZEncoding(it) }
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

