// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.query

import io.zenoh.jni.NativeHandle
import io.zenoh.jni.ZException
import io.zenoh.jni.bytes.ZEncoding
import io.zenoh.jni.bytes.ZZBytes
import io.zenoh.jni.callbacks.Callback
import io.zenoh.jni.callbacks.ZReplyCallback
import io.zenoh.jni.config.ZZenohId
import io.zenoh.jni.keyexpr.ZKeyExpr
import io.zenoh.jni.query.ReplyKeyExpr
import io.zenoh.jni.query.ZQuerier
import io.zenoh.jni.query.ZQuery
import io.zenoh.jni.query.ZReply
import io.zenoh.jni.withSortedHandleLocks
import io.zenoh.jni.JNINative

public fun zQuerierGet(querier: ZQuerier, parameters: String?, payload: ByteArray?, encoding: String?, attachment: ByteArray?, callback: ZReplyCallback, onClose: Callback, onError: (String?, String) -> Unit = { __de_je, __de_z0 -> throw ZException(__de_je ?: __de_z0) }) {
    if (querier.ptr == 0L) { onError("Operation on a closed native handle.", ""); return }
    var __cap_failed = false
    var __cap_je: String? = null
    var __cap_ze0: String? = null
    val __cap = { __je: String?, __ze0: String? -> __cap_failed = true; __cap_je = __je; __cap_ze0 = __ze0 }
    withSortedHandleLocks(querier) {
    val querier_ptr = querier.ptr
    JNINative.zQuerierGet(querier_ptr, parameters, payload, encoding, attachment, callback, onClose, __cap)
    }
    if (__cap_failed) return onError(__cap_je, (__cap_ze0 ?: ""))
}

public fun zQueryReplySuccess(query: ZQuery, keyExprSel: Int, keyExpr0: String?, keyExpr1: ZKeyExpr?, payload: ByteArray, encoding: String?, timestampNtp64: Long?, attachment: ByteArray?, express: Boolean?, onError: (String?, String) -> Unit = { __de_je, __de_z0 -> throw ZException(__de_je ?: __de_z0) }) {
    if (query.ptr == 0L) { onError("Operation on a closed native handle.", ""); return }
    if (keyExpr1 != null && keyExpr1.ptr == 0L) { onError("Operation on a closed native handle.", ""); return }
    var __cap_failed = false
    var __cap_je: String? = null
    var __cap_ze0: String? = null
    val __cap = { __je: String?, __ze0: String? -> __cap_failed = true; __cap_je = __je; __cap_ze0 = __ze0 }
    run {
    val __locks = ArrayList<NativeHandle>()
    __locks.add(query)
    keyExpr1?.let { __locks.add(it) }
    withSortedHandleLocks(__locks) {
    val query_ptr = query.ptr
    val keyExpr1_ptr = keyExpr1?.ptr ?: 0L
    JNINative.zQueryReplySuccess(query_ptr, keyExprSel, keyExpr0, keyExpr1_ptr, payload, encoding, timestampNtp64, attachment, express, __cap)
    }
    }
    if (__cap_failed) return onError(__cap_je, (__cap_ze0 ?: ""))
}

public fun zQueryReplyError(query: ZQuery, payload: ByteArray, encoding: String?, onError: (String?, String) -> Unit = { __de_je, __de_z0 -> throw ZException(__de_je ?: __de_z0) }) {
    if (query.ptr == 0L) { onError("Operation on a closed native handle.", ""); return }
    var __cap_failed = false
    var __cap_je: String? = null
    var __cap_ze0: String? = null
    val __cap = { __je: String?, __ze0: String? -> __cap_failed = true; __cap_je = __je; __cap_ze0 = __ze0 }
    withSortedHandleLocks(query) {
    val query_ptr = query.ptr
    JNINative.zQueryReplyError(query_ptr, payload, encoding, __cap)
    }
    if (__cap_failed) return onError(__cap_je, (__cap_ze0 ?: ""))
}

public fun zQueryReplyDelete(query: ZQuery, keyExprSel: Int, keyExpr0: String?, keyExpr1: ZKeyExpr?, timestampNtp64: Long?, attachment: ByteArray?, express: Boolean?, onError: (String?, String) -> Unit = { __de_je, __de_z0 -> throw ZException(__de_je ?: __de_z0) }) {
    if (query.ptr == 0L) { onError("Operation on a closed native handle.", ""); return }
    if (keyExpr1 != null && keyExpr1.ptr == 0L) { onError("Operation on a closed native handle.", ""); return }
    var __cap_failed = false
    var __cap_je: String? = null
    var __cap_ze0: String? = null
    val __cap = { __je: String?, __ze0: String? -> __cap_failed = true; __cap_je = __je; __cap_ze0 = __ze0 }
    run {
    val __locks = ArrayList<NativeHandle>()
    __locks.add(query)
    keyExpr1?.let { __locks.add(it) }
    withSortedHandleLocks(__locks) {
    val query_ptr = query.ptr
    val keyExpr1_ptr = keyExpr1?.ptr ?: 0L
    JNINative.zQueryReplyDelete(query_ptr, keyExprSel, keyExpr0, keyExpr1_ptr, timestampNtp64, attachment, express, __cap)
    }
    }
    if (__cap_failed) return onError(__cap_je, (__cap_ze0 ?: ""))
}

public fun zQueryReplySample(query: ZQuery, sampleKeyExprSel: Int, sampleKeyExpr0: String?, sampleKeyExpr1: ZKeyExpr?, samplePayload: ByteArray, sampleEncoding: String, onError: (String?, String) -> Unit = { __de_je, __de_z0 -> throw ZException(__de_je ?: __de_z0) }) {
    if (query.ptr == 0L) { onError("Operation on a closed native handle.", ""); return }
    if (sampleKeyExpr1 != null && sampleKeyExpr1.ptr == 0L) { onError("Operation on a closed native handle.", ""); return }
    var __cap_failed = false
    var __cap_je: String? = null
    var __cap_ze0: String? = null
    val __cap = { __je: String?, __ze0: String? -> __cap_failed = true; __cap_je = __je; __cap_ze0 = __ze0 }
    run {
    val __locks = ArrayList<NativeHandle>()
    __locks.add(query)
    sampleKeyExpr1?.let { __locks.add(it) }
    withSortedHandleLocks(__locks) {
    val query_ptr = query.ptr
    val sampleKeyExpr1_ptr = sampleKeyExpr1?.ptr ?: 0L
    try {
    JNINative.zQueryReplySample(query_ptr, sampleKeyExprSel, sampleKeyExpr0, sampleKeyExpr1_ptr, samplePayload, sampleEncoding, __cap)
    } finally {
    sampleKeyExpr1?.let { it.ptr = 0L }
    }
    }
    }
    if (__cap_failed) return onError(__cap_je, (__cap_ze0 ?: ""))
}

public fun zQueryKeyexpr(q: ZQuery, onError: (String?) -> ZKeyExpr = { __de_je -> throw ZException(__de_je) }): ZKeyExpr {
    if (q.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(q) {
    val q_ptr = q.ptr
    ZKeyExpr(JNINative.zQueryKeyexpr(q_ptr, __cap))
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zQueryParameters(q: ZQuery, onError: (String?) -> String = { __de_je -> throw ZException(__de_je) }): String {
    if (q.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(q) {
    val q_ptr = q.ptr
    JNINative.zQueryParameters(q_ptr, __cap)
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zQueryPayload(q: ZQuery, onError: (String?) -> ZZBytes? = { __de_je -> throw ZException(__de_je) }): ZZBytes? {
    if (q.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(q) {
    val q_ptr = q.ptr
    JNINative.zQueryPayload(q_ptr, __cap).let { if (it == 0L) null else ZZBytes(it) }
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zQueryEncoding(q: ZQuery, onError: (String?) -> ZEncoding? = { __de_je -> throw ZException(__de_je) }): ZEncoding? {
    if (q.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(q) {
    val q_ptr = q.ptr
    JNINative.zQueryEncoding(q_ptr, __cap).let { if (it == 0L) null else ZEncoding(it) }
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zQueryAttachment(q: ZQuery, onError: (String?) -> ZZBytes? = { __de_je -> throw ZException(__de_je) }): ZZBytes? {
    if (q.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(q) {
    val q_ptr = q.ptr
    JNINative.zQueryAttachment(q_ptr, __cap).let { if (it == 0L) null else ZZBytes(it) }
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zQueryAcceptsReplies(q: ZQuery, onError: (String?) -> ReplyKeyExpr = { __de_je -> throw ZException(__de_je) }): ReplyKeyExpr {
    if (q.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(q) {
    val q_ptr = q.ptr
    ReplyKeyExpr.fromInt(JNINative.zQueryAcceptsReplies(q_ptr, __cap))
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zReplyReplierZid(r: ZReply, onError: (String?) -> ZZenohId? = { __de_je -> throw ZException(__de_je) }): ZZenohId? {
    if (r.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(r) {
    val r_ptr = r.ptr
    JNINative.zReplyReplierZid(r_ptr, __cap)?.let { ZZenohId(it) }
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zReplyReplierEid(r: ZReply, onError: (String?) -> Int = { __de_je -> throw ZException(__de_je) }): Int {
    if (r.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(r) {
    val r_ptr = r.ptr
    JNINative.zReplyReplierEid(r_ptr, __cap)
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zReplyIsOk(r: ZReply, onError: (String?) -> Boolean = { __de_je -> throw ZException(__de_je) }): Boolean {
    if (r.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(r) {
    val r_ptr = r.ptr
    JNINative.zReplyIsOk(r_ptr, __cap)
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

@Suppress("UNCHECKED_CAST")
public fun <R> zReplySample(r: ZReply, onError: (String?) -> R? = { __de_je -> throw ZException(__de_je) }, build: (ZKeyExpr, String, ByteArray, String, Int, Long?, Boolean, Int, Int, ByteArray?) -> R): R? {
    if (r.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(r) {
    val r_ptr = r.ptr
    (JNINative.zReplySample(r_ptr, build, __cap) as R?)
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zReplyErrorPayload(r: ZReply, onError: (String?) -> ZZBytes? = { __de_je -> throw ZException(__de_je) }): ZZBytes? {
    if (r.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(r) {
    val r_ptr = r.ptr
    JNINative.zReplyErrorPayload(r_ptr, __cap).let { if (it == 0L) null else ZZBytes(it) }
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

public fun zReplyErrorEncoding(r: ZReply, onError: (String?) -> ZEncoding? = { __de_je -> throw ZException(__de_je) }): ZEncoding? {
    if (r.ptr == 0L) return onError("Operation on a closed native handle.")
    var __cap_failed = false
    var __cap_je: String? = null
    val __cap = { __je: String? -> __cap_failed = true; __cap_je = __je }
    val __ret = withSortedHandleLocks(r) {
    val r_ptr = r.ptr
    JNINative.zReplyErrorEncoding(r_ptr, __cap).let { if (it == 0L) null else ZEncoding(it) }
    }
    if (__cap_failed) return onError(__cap_je)
    return __ret
}

