// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni.query

/** JVM-side surface for the native Rust `QueryTarget` enum. */
public enum class QueryTarget(public val value: Int) {
    BEST_MATCHING(0),
    ALL(1),
    ALL_COMPLETE(2);

    public companion object {
        @JvmStatic
        public fun fromInt(value: Int): QueryTarget = entries.first { it.value == value }
    }
}
