// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni.query

import io.zenoh.jni.bytes.Encoding
import io.zenoh.jni.bytes.ZBytes
import io.zenoh.jni.config.ZenohId
import io.zenoh.jni.sample.Sample

public data class Reply(
    val replierZid: ZenohId?,
    val replierEid: Int,
    val sample: Sample?,
    val errorPayload: ZBytes?,
    val errorEncoding: Encoding?,
) {
    public companion object {
    }
}
