// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.query

import io.zenoh.jni.Error
import io.zenoh.jni.JNINative
import io.zenoh.jni.JniBindingError
import io.zenoh.jni.bytes.ZEncoding
import io.zenoh.jni.bytes.ZZBytes
import io.zenoh.jni.callbacks.Callback
import io.zenoh.jni.callbacks.ReplyCallback

/** Typed handle for a native Zenoh `ZQuerier`. */
public class ZQuerier(initialPtr: Long) : AutoCloseable {
    @Volatile internal var ptr: Long = initialPtr

    public fun peek(): Long = ptr
    public fun isClosed(): Boolean = ptr == 0L

    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZQuerier {
        val p = ptr
        ptr = 0L
        return ZQuerier(p)
    }

    @Throws(Error::class, JniBindingError::class)
    public fun querierGet(parameters: String?, payload: Any?, encoding: Any?, attachment: Any?, callback: ReplyCallback, onClose: Callback) {
        synchronized(this) {
            val querier_ptr = this.ptr
            if (querier_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
            if (payload is ZZBytes) synchronized(payload) {
            if (encoding is ZEncoding) synchronized(encoding) {
            if (attachment is ZZBytes) synchronized(attachment) {
            JNINative.querierGet(querier_ptr, parameters, payload, encoding, attachment, callback, onClose)
        } else {
            JNINative.querierGet(querier_ptr, parameters, payload, encoding, attachment, callback, onClose)
        }
        } else {
            if (attachment is ZZBytes) synchronized(attachment) {
            JNINative.querierGet(querier_ptr, parameters, payload, encoding, attachment, callback, onClose)
        } else {
            JNINative.querierGet(querier_ptr, parameters, payload, encoding, attachment, callback, onClose)
        }
        }
        } else {
            if (encoding is ZEncoding) synchronized(encoding) {
            if (attachment is ZZBytes) synchronized(attachment) {
            JNINative.querierGet(querier_ptr, parameters, payload, encoding, attachment, callback, onClose)
        } else {
            JNINative.querierGet(querier_ptr, parameters, payload, encoding, attachment, callback, onClose)
        }
        } else {
            if (attachment is ZZBytes) synchronized(attachment) {
            JNINative.querierGet(querier_ptr, parameters, payload, encoding, attachment, callback, onClose)
        } else {
            JNINative.querierGet(querier_ptr, parameters, payload, encoding, attachment, callback, onClose)
        }
        }
        }
        }
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}
