// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.query

import io.zenoh.jni.Error
import io.zenoh.jni.JNINative
import io.zenoh.jni.JniBindingError
import io.zenoh.jni.NativeHandle
import io.zenoh.jni.bytes.Encoding
import io.zenoh.jni.bytes.ZBytes
import io.zenoh.jni.bytes.ZEncoding
import io.zenoh.jni.bytes.ZZBytes
import io.zenoh.jni.keyexpr.KeyExpr
import io.zenoh.jni.keyexpr.ZKeyExpr
import io.zenoh.jni.withSortedHandleLocks

/** Typed handle for a native Zenoh `ZQuery`. */
public class ZQuery(initialPtr: Long) : NativeHandle(initialPtr) {
    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZQuery {
        val p = ptr
        ptr = 0L
        return ZQuery(p)
    }

    @Throws(Error::class, JniBindingError::class)
    public fun zQueryReplySuccess(keyExpr: ZKeyExpr, payload: ZZBytes, encoding: ZEncoding?, timestampNtp64: Long?, attachment: ZZBytes, express: Boolean?) {
        val __locks = ArrayList<NativeHandle>()
        __locks.add(this)
        __locks.add(keyExpr)
        __locks.add(payload)
        encoding?.let { __locks.add(it) }
        __locks.add(attachment)
        withSortedHandleLocks(__locks) {
        val query_ptr = this.ptr
        if (query_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        val keyExpr_ptr = keyExpr.ptr
        if (keyExpr_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        val payload_ptr = payload.ptr
        if (payload_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        val encoding_ptr = encoding?.ptr ?: 0L
        if (encoding != null && encoding_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        val attachment_ptr = attachment.ptr
        if (attachment_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        try {
        JNINative.zQueryReplySuccess(query_ptr, keyExpr_ptr, payload_ptr, encoding_ptr, timestampNtp64, attachment_ptr, express)
        } finally {
        payload.ptr = 0L
        attachment.ptr = 0L
        }
        }
    }

    @Throws(Error::class, JniBindingError::class)
    public fun zQueryReplyError(payload: ZZBytes, encoding: ZEncoding?) {
        val __locks = ArrayList<NativeHandle>()
        __locks.add(this)
        __locks.add(payload)
        encoding?.let { __locks.add(it) }
        withSortedHandleLocks(__locks) {
        val query_ptr = this.ptr
        if (query_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        val payload_ptr = payload.ptr
        if (payload_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        val encoding_ptr = encoding?.ptr ?: 0L
        if (encoding != null && encoding_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        try {
        JNINative.zQueryReplyError(query_ptr, payload_ptr, encoding_ptr)
        } finally {
        payload.ptr = 0L
        }
        }
    }

    @Throws(Error::class, JniBindingError::class)
    public fun zQueryReplyDelete(keyExpr: ZKeyExpr, timestampNtp64: Long?, attachment: ZZBytes, express: Boolean?) {
        withSortedHandleLocks(this, keyExpr, attachment) {
        val query_ptr = this.ptr
        if (query_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        val keyExpr_ptr = keyExpr.ptr
        if (keyExpr_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        val attachment_ptr = attachment.ptr
        if (attachment_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        try {
        JNINative.zQueryReplyDelete(query_ptr, keyExpr_ptr, timestampNtp64, attachment_ptr, express)
        } finally {
        attachment.ptr = 0L
        }
        }
    }

    @Throws(JniBindingError::class)
    public fun zQueryKeyexpr(): ZKeyExpr {
        return withSortedHandleLocks(this) {
        val q_ptr = this.ptr
        if (q_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        ZKeyExpr(JNINative.zQueryKeyexpr(q_ptr))
        }
    }

    @Throws(JniBindingError::class)
    public fun zQueryParameters(): String {
        return withSortedHandleLocks(this) {
        val q_ptr = this.ptr
        if (q_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zQueryParameters(q_ptr)
        }
    }

    @Throws(JniBindingError::class)
    public fun zQueryPayload(): ZZBytes? {
        return withSortedHandleLocks(this) {
        val q_ptr = this.ptr
        if (q_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zQueryPayload(q_ptr).let { if (it == 0L) null else ZZBytes(it) }
        }
    }

    @Throws(JniBindingError::class)
    public fun zQueryEncoding(): ZEncoding? {
        return withSortedHandleLocks(this) {
        val q_ptr = this.ptr
        if (q_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zQueryEncoding(q_ptr).let { if (it == 0L) null else ZEncoding(it) }
        }
    }

    @Throws(JniBindingError::class)
    public fun zQueryExpand(): Query {
        return withSortedHandleLocks(this) {
        val query_ptr = this.ptr
        if (query_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        try {
        JNINative.zQueryExpand(query_ptr)
        } finally {
        ptr = 0L
        }
        }
    }

    @Throws(Error::class, JniBindingError::class)
    public fun queryReplySuccess(keyExpr: KeyExpr, payload: ZBytes, encoding: Encoding?, timestampNtp64: Long?, attachment: ZBytes?, express: Boolean?) {
        withSortedHandleLocks(this) {
        val query_ptr = this.ptr
        if (query_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        try {
        JNINative.queryReplySuccess(query_ptr, keyExpr, payload.bytes, encoding != null, encoding?.id ?: 0, encoding?.schema, timestampNtp64, attachment?.bytes, express)
        } finally {
        ptr = 0L
        }
        }
    }

    @Throws(Error::class, JniBindingError::class)
    public fun queryReplyError(payload: ZBytes, encoding: Encoding?) {
        withSortedHandleLocks(this) {
        val query_ptr = this.ptr
        if (query_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        try {
        JNINative.queryReplyError(query_ptr, payload.bytes, encoding != null, encoding?.id ?: 0, encoding?.schema)
        } finally {
        ptr = 0L
        }
        }
    }

    @Throws(Error::class, JniBindingError::class)
    public fun queryReplyDelete(keyExpr: KeyExpr, timestampNtp64: Long?, attachment: ZBytes?, express: Boolean?) {
        withSortedHandleLocks(this) {
        val query_ptr = this.ptr
        if (query_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        try {
        JNINative.queryReplyDelete(query_ptr, keyExpr, timestampNtp64, attachment?.bytes, express)
        } finally {
        ptr = 0L
        }
        }
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}
