// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.query

import io.zenoh.jni.JNINative
import io.zenoh.jni.JniBindingError

/** Typed handle for a native Zenoh `ZQuery`. */
public class ZQuery(initialPtr: Long) : AutoCloseable {
    @Volatile internal var ptr: Long = initialPtr

    public fun peek(): Long = ptr
    public fun isClosed(): Boolean = ptr == 0L

    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZQuery {
        val p = ptr
        ptr = 0L
        return ZQuery(p)
    }

    @Throws(JniBindingError::class)
    public fun zQueryExpand(): Query {
        synchronized(this) {
            val query_ptr = this.ptr
            if (query_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
            return try {
                JNINative.zQueryExpand(query_ptr)
            } finally {
                ptr = 0L
            }
        }
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}
