// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.query

import io.zenoh.jni.JNINative
import io.zenoh.jni.JniBindingError
import io.zenoh.jni.NativeHandle
import io.zenoh.jni.bytes.ZEncoding
import io.zenoh.jni.bytes.ZZBytes
import io.zenoh.jni.config.ZZenohId
import io.zenoh.jni.config.ZenohId
import io.zenoh.jni.sample.ZSample
import io.zenoh.jni.withSortedHandleLocks

/** Typed handle for a native Zenoh `ZReply`. */
public class ZReply(initialPtr: Long) : NativeHandle(initialPtr) {
    @Synchronized
    override fun close() {
        val p = ptr
        if (p != 0L) {
            ptr = 0L
            freePtr(p)
        }
    }

    @Synchronized
    public fun take(): ZReply {
        val p = ptr
        ptr = 0L
        return ZReply(p)
    }

    @Throws(JniBindingError::class)
    public fun replyReplierZid(): ZenohId? {
        return withSortedHandleLocks(this) {
        val r_ptr = this.ptr
        if (r_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.replyReplierZid(r_ptr)?.let { ZenohId(it) }
        }
    }

    @Throws(JniBindingError::class)
    public fun zReplyReplierZid(): ZZenohId? {
        return withSortedHandleLocks(this) {
        val r_ptr = this.ptr
        if (r_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zReplyReplierZid(r_ptr)?.let { ZZenohId(it) }
        }
    }

    @Throws(JniBindingError::class)
    public fun zReplyReplierEid(): Int {
        return withSortedHandleLocks(this) {
        val r_ptr = this.ptr
        if (r_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zReplyReplierEid(r_ptr)
        }
    }

    @Throws(JniBindingError::class)
    public fun zReplyIsOk(): Boolean {
        return withSortedHandleLocks(this) {
        val r_ptr = this.ptr
        if (r_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zReplyIsOk(r_ptr)
        }
    }

    @Throws(JniBindingError::class)
    public fun zReplySample(): ZSample? {
        return withSortedHandleLocks(this) {
        val r_ptr = this.ptr
        if (r_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zReplySample(r_ptr).let { if (it == 0L) null else ZSample(it) }
        }
    }

    @Throws(JniBindingError::class)
    public fun zReplyErrorPayload(): ZZBytes? {
        return withSortedHandleLocks(this) {
        val r_ptr = this.ptr
        if (r_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zReplyErrorPayload(r_ptr).let { if (it == 0L) null else ZZBytes(it) }
        }
    }

    @Throws(JniBindingError::class)
    public fun zReplyErrorEncoding(): ZEncoding? {
        return withSortedHandleLocks(this) {
        val r_ptr = this.ptr
        if (r_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zReplyErrorEncoding(r_ptr).let { if (it == 0L) null else ZEncoding(it) }
        }
    }

    @Throws(JniBindingError::class)
    public fun zReplyExpand(): Reply {
        return withSortedHandleLocks(this) {
        val r_ptr = this.ptr
        if (r_ptr == 0L) throw JniBindingError("Operation on a closed native handle.")
        JNINative.zReplyExpand(r_ptr)
        }
    }

    public companion object {
        @JvmStatic
        external fun freePtr(ptr: Long)
    }
}
