// Auto-generated by JniGen — do not edit by hand.
package io.zenoh.jni.session

import io.zenoh.jni.ErrorHolder
import io.zenoh.jni.ErrorSink
import io.zenoh.jni.NativeHandle
import io.zenoh.jni.ZException
import io.zenoh.jni.bytes.ZEncoding
import io.zenoh.jni.bytes.ZZBytes
import io.zenoh.jni.callbacks.Callback
import io.zenoh.jni.callbacks.ZQueryCallback
import io.zenoh.jni.callbacks.ZReplyCallback
import io.zenoh.jni.callbacks.ZSampleCallback
import io.zenoh.jni.config.ZConfig
import io.zenoh.jni.config.ZZenohId
import io.zenoh.jni.keyexpr.ZKeyExpr
import io.zenoh.jni.liveliness.ZLivelinessToken
import io.zenoh.jni.pubsub.ZPublisher
import io.zenoh.jni.pubsub.ZSubscriber
import io.zenoh.jni.qos.CongestionControl
import io.zenoh.jni.qos.Priority
import io.zenoh.jni.qos.Reliability
import io.zenoh.jni.query.ConsolidationMode
import io.zenoh.jni.query.QueryTarget
import io.zenoh.jni.query.ReplyKeyExpr
import io.zenoh.jni.query.ZQuerier
import io.zenoh.jni.query.ZQueryable
import io.zenoh.jni.session.ZSession
import io.zenoh.jni.withSortedHandleLocks
import io.zenoh.jni.JNINative

public fun zOpen(config: ZConfig): ZSession {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(config) {
    val config_ptr = config.ptr
    if (config_ptr == 0L) throw ZException("Operation on a closed native handle.")
    try {
    ZSession(JNINative.zOpen(config_ptr, __sink))
    } finally {
    config.ptr = 0L
    }
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zSessionDeclarePublisher(session: ZSession, keyExpr: ZKeyExpr, congestionControl: CongestionControl?, priority: Priority?, express: Boolean?, reliability: Reliability?): ZPublisher {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(session, keyExpr) {
    val session_ptr = session.ptr
    if (session_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val keyExpr_ptr = keyExpr.ptr
    if (keyExpr_ptr == 0L) throw ZException("Operation on a closed native handle.")
    try {
    ZPublisher(JNINative.zSessionDeclarePublisher(session_ptr, keyExpr_ptr, congestionControl?.value, priority?.value, express, reliability?.value, __sink))
    } finally {
    keyExpr.ptr = 0L
    }
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zSessionPut(session: ZSession, keyExpr: ZKeyExpr, payload: ZZBytes, encoding: ZEncoding?, congestionControl: CongestionControl?, priority: Priority?, express: Boolean?, attachment: ZZBytes?, reliability: Reliability?) {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    run {
    val __locks = ArrayList<NativeHandle>()
    __locks.add(session)
    __locks.add(keyExpr)
    __locks.add(payload)
    encoding?.let { __locks.add(it) }
    attachment?.let { __locks.add(it) }
    withSortedHandleLocks(__locks) {
    val session_ptr = session.ptr
    if (session_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val keyExpr_ptr = keyExpr.ptr
    if (keyExpr_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val payload_ptr = payload.ptr
    if (payload_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val encoding_ptr = encoding?.ptr ?: 0L
    if (encoding != null && encoding_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val attachment_ptr = attachment?.ptr ?: 0L
    if (attachment != null && attachment_ptr == 0L) throw ZException("Operation on a closed native handle.")
    try {
    JNINative.zSessionPut(session_ptr, keyExpr_ptr, payload_ptr, encoding_ptr, congestionControl?.value, priority?.value, express, attachment_ptr, reliability?.value, __sink)
    } finally {
    payload.ptr = 0L
    attachment?.let { it.ptr = 0L }
    }
    }
    }
    __err.message?.let { throw ZException(it) }
}

public fun zSessionDelete(session: ZSession, keyExpr: ZKeyExpr, congestionControl: CongestionControl?, priority: Priority?, express: Boolean?, attachment: ZZBytes?, reliability: Reliability?) {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    run {
    val __locks = ArrayList<NativeHandle>()
    __locks.add(session)
    __locks.add(keyExpr)
    attachment?.let { __locks.add(it) }
    withSortedHandleLocks(__locks) {
    val session_ptr = session.ptr
    if (session_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val keyExpr_ptr = keyExpr.ptr
    if (keyExpr_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val attachment_ptr = attachment?.ptr ?: 0L
    if (attachment != null && attachment_ptr == 0L) throw ZException("Operation on a closed native handle.")
    try {
    JNINative.zSessionDelete(session_ptr, keyExpr_ptr, congestionControl?.value, priority?.value, express, attachment_ptr, reliability?.value, __sink)
    } finally {
    attachment?.let { it.ptr = 0L }
    }
    }
    }
    __err.message?.let { throw ZException(it) }
}

public fun zSessionDeclareSubscriber(session: ZSession, keyExpr: ZKeyExpr, callback: ZSampleCallback, onClose: Callback): ZSubscriber {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(session, keyExpr) {
    val session_ptr = session.ptr
    if (session_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val keyExpr_ptr = keyExpr.ptr
    if (keyExpr_ptr == 0L) throw ZException("Operation on a closed native handle.")
    try {
    ZSubscriber(JNINative.zSessionDeclareSubscriber(session_ptr, keyExpr_ptr, callback, onClose, __sink))
    } finally {
    keyExpr.ptr = 0L
    }
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zSessionDeclareQuerier(session: ZSession, keyExpr: ZKeyExpr, target: QueryTarget?, consolidation: ConsolidationMode?, congestionControl: CongestionControl?, priority: Priority?, express: Boolean?, timeoutMs: Long?, acceptReplies: ReplyKeyExpr?): ZQuerier {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(session, keyExpr) {
    val session_ptr = session.ptr
    if (session_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val keyExpr_ptr = keyExpr.ptr
    if (keyExpr_ptr == 0L) throw ZException("Operation on a closed native handle.")
    try {
    ZQuerier(JNINative.zSessionDeclareQuerier(session_ptr, keyExpr_ptr, target?.value, consolidation?.value, congestionControl?.value, priority?.value, express, timeoutMs, acceptReplies?.value, __sink))
    } finally {
    keyExpr.ptr = 0L
    }
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zSessionDeclareQueryable(session: ZSession, keyExpr: ZKeyExpr, complete: Boolean?, callback: ZQueryCallback, onClose: Callback): ZQueryable {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(session, keyExpr) {
    val session_ptr = session.ptr
    if (session_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val keyExpr_ptr = keyExpr.ptr
    if (keyExpr_ptr == 0L) throw ZException("Operation on a closed native handle.")
    try {
    ZQueryable(JNINative.zSessionDeclareQueryable(session_ptr, keyExpr_ptr, complete, callback, onClose, __sink))
    } finally {
    keyExpr.ptr = 0L
    }
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zSessionDeclareKeyexpr(session: ZSession, keyExpr: String): ZKeyExpr {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(session) {
    val session_ptr = session.ptr
    if (session_ptr == 0L) throw ZException("Operation on a closed native handle.")
    ZKeyExpr(JNINative.zSessionDeclareKeyexpr(session_ptr, keyExpr, __sink))
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zSessionUndeclareKeyexpr(session: ZSession, keyExpr: ZKeyExpr) {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    withSortedHandleLocks(session, keyExpr) {
    val session_ptr = session.ptr
    if (session_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val keyExpr_ptr = keyExpr.ptr
    if (keyExpr_ptr == 0L) throw ZException("Operation on a closed native handle.")
    try {
    JNINative.zSessionUndeclareKeyexpr(session_ptr, keyExpr_ptr, __sink)
    } finally {
    keyExpr.ptr = 0L
    }
    }
    __err.message?.let { throw ZException(it) }
}

public fun zSessionGet(session: ZSession, keyExpr: ZKeyExpr, parameters: String?, timeoutMs: Long?, target: QueryTarget?, consolidation: ConsolidationMode?, acceptReplies: ReplyKeyExpr?, congestionControl: CongestionControl?, priority: Priority?, express: Boolean?, payload: ZZBytes?, encoding: ZEncoding?, attachment: ZZBytes?, callback: ZReplyCallback, onClose: Callback) {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    run {
    val __locks = ArrayList<NativeHandle>()
    __locks.add(session)
    __locks.add(keyExpr)
    payload?.let { __locks.add(it) }
    encoding?.let { __locks.add(it) }
    attachment?.let { __locks.add(it) }
    withSortedHandleLocks(__locks) {
    val session_ptr = session.ptr
    if (session_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val keyExpr_ptr = keyExpr.ptr
    if (keyExpr_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val payload_ptr = payload?.ptr ?: 0L
    if (payload != null && payload_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val encoding_ptr = encoding?.ptr ?: 0L
    if (encoding != null && encoding_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val attachment_ptr = attachment?.ptr ?: 0L
    if (attachment != null && attachment_ptr == 0L) throw ZException("Operation on a closed native handle.")
    try {
    JNINative.zSessionGet(session_ptr, keyExpr_ptr, parameters, timeoutMs, target?.value, consolidation?.value, acceptReplies?.value, congestionControl?.value, priority?.value, express, payload_ptr, encoding_ptr, attachment_ptr, callback, onClose, __sink)
    } finally {
    payload?.let { it.ptr = 0L }
    attachment?.let { it.ptr = 0L }
    }
    }
    }
    __err.message?.let { throw ZException(it) }
}

public fun zSessionZid(session: ZSession): ZZenohId {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(session) {
    val session_ptr = session.ptr
    if (session_ptr == 0L) throw ZException("Operation on a closed native handle.")
    ZZenohId(JNINative.zSessionZid(session_ptr, __sink))
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zSessionPeersZid(session: ZSession): List<ZZenohId> {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(session) {
    val session_ptr = session.ptr
    if (session_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zSessionPeersZid(session_ptr, __sink).map { ZZenohId(it) }
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zSessionRoutersZid(session: ZSession): List<ZZenohId> {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(session) {
    val session_ptr = session.ptr
    if (session_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zSessionRoutersZid(session_ptr, __sink).map { ZZenohId(it) }
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zLivelinessDeclareToken(session: ZSession, keyExpr: ZKeyExpr): ZLivelinessToken {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(session, keyExpr) {
    val session_ptr = session.ptr
    if (session_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val keyExpr_ptr = keyExpr.ptr
    if (keyExpr_ptr == 0L) throw ZException("Operation on a closed native handle.")
    try {
    ZLivelinessToken(JNINative.zLivelinessDeclareToken(session_ptr, keyExpr_ptr, __sink))
    } finally {
    keyExpr.ptr = 0L
    }
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

public fun zLivelinessGet(session: ZSession, keyExpr: ZKeyExpr, timeoutMs: Long, callback: ZReplyCallback, onClose: Callback) {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    withSortedHandleLocks(session, keyExpr) {
    val session_ptr = session.ptr
    if (session_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val keyExpr_ptr = keyExpr.ptr
    if (keyExpr_ptr == 0L) throw ZException("Operation on a closed native handle.")
    JNINative.zLivelinessGet(session_ptr, keyExpr_ptr, timeoutMs, callback, onClose, __sink)
    }
    __err.message?.let { throw ZException(it) }
}

public fun zLivelinessDeclareSubscriber(session: ZSession, keyExpr: ZKeyExpr, history: Boolean, callback: ZSampleCallback, onClose: Callback): ZSubscriber {
    val __err = ErrorHolder()
    val __sink = ErrorSink { __m -> __err.message = __m }
    val __ret = withSortedHandleLocks(session, keyExpr) {
    val session_ptr = session.ptr
    if (session_ptr == 0L) throw ZException("Operation on a closed native handle.")
    val keyExpr_ptr = keyExpr.ptr
    if (keyExpr_ptr == 0L) throw ZException("Operation on a closed native handle.")
    try {
    ZSubscriber(JNINative.zLivelinessDeclareSubscriber(session_ptr, keyExpr_ptr, history, callback, onClose, __sink))
    } finally {
    keyExpr.ptr = 0L
    }
    }
    __err.message?.let { throw ZException(it) }
    return __ret
}

