// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni

/** Typed [NativeHandle] for a native Zenoh `Queryable`. */
public class JNIQueryable(initialPtr: Long) : NativeHandle(initialPtr) {
    public fun close() = close { freePtrViaJNI(it) }
    private external fun freePtrViaJNI(ptr: Long)
}
