// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni

/** Typed [NativeHandle] for a native Zenoh `Subscriber`. */
public class JNISubscriber(initialPtr: Long) : NativeHandle(initialPtr) {
    public fun close() = close { freePtrViaJNI(it) }
    private external fun freePtrViaJNI(ptr: Long)
}
