// Auto-generated by JniExt — do not edit by hand.
package io.zenoh.jni

import io.zenoh.exceptions.ZError
import java.util.concurrent.locks.ReentrantReadWriteLock
import kotlin.concurrent.read
import kotlin.concurrent.write

/**
 * Race-free wrapper around a raw `Arc<T>` pointer obtained from native
 * code via `Arc::into_raw(Arc::new(v))`. Pairs the pointer with a
 * `ReentrantReadWriteLock` so that borrow-style JNI calls run in
 * parallel under the read lock and consume/close serialise against
 * them under the write lock.
 *
 * This is the Java-side half of the type-conversion rule for opaque
 * handles: `&T` parameters route through [withPtr] (borrow); by-value
 * `T` parameters route through [consume] (write lock + atomic null);
 * destructor entry points without a matching `#[prebindgen]` fn use
 * [close]. The auto-generated wrappers in `JNIWrappers.kt` are the
 * only callers that need to know which mode applies.
 *
 * Marked `open` so the hand-maintained `JNI*.kt` typed-handle classes
 * can subclass for type safety while inheriting the lock contract.
 */
public open class NativeHandle(initial: Long) {
    private val lock = ReentrantReadWriteLock()

    /** Volatile so [peek] is atomic on 32-bit JVMs and observes the
     *  write done by [close] / [consume] without holding the lock. */
    @Volatile private var ptr: Long = initial

    /**
     * Run [block] with the live pointer under the read lock. Throws
     * [ZError] if [close] has already released the handle. Multiple
     * concurrent invocations run in parallel; only [close]/[consume]
     * are serialised against them.
     */
    @Throws(ZError::class)
    public fun <T> withPtr(block: (Long) -> T): T = lock.read {
        val p = ptr
        if (p == 0L) throw ZError("Operation on a closed native handle.")
        block(p)
    }

    /**
     * Take the pointer under the write lock and pass it to [freeFn]
     * exactly once. Subsequent [close] calls are no-ops. Blocks until
     * all in-flight [withPtr] calls finish.
     */
    public fun close(freeFn: (Long) -> Unit) {
        lock.write {
            val p = ptr
            if (p == 0L) return@write
            ptr = 0L
            freeFn(p)
        }
    }

    /**
     * Consume the pointer: take it under the write lock, atomically
     * null the field, and pass the captured pointer to [action]. Used
     * by the generator-emitted wrappers whose Rust side runs
     * `Arc::try_unwrap(Arc::from_raw(...))` — i.e. by-value `T`
     * opaque-handle parameters. The write lock + atomic-null give Rust
     * a unique-ownership guarantee so `try_unwrap` always succeeds.
     * Throws if the handle has already been closed/consumed.
     */
    @Throws(ZError::class)
    public fun <R> consume(action: (Long) -> R): R = lock.write {
        val p = ptr
        if (p == 0L) throw ZError("Operation on a closed native handle.")
        ptr = 0L
        action(p)
    }

    /** True iff [close] has run. */
    public fun isClosed(): Boolean = lock.read { ptr == 0L }

    /**
     * Read the current pointer value without holding the lock.
     * Returns `0L` if the handle has been closed/consumed.
     */
    public fun peek(): Long = ptr
}
